### ISSUE TITLE
Determine correct reference

### ISSUE THREAD

**Issue by chmille4** [tonydisera/gene.iobio#1]
snpeff assumes reference grch37
freebayes assumes reference ?

we need to give the user the ability to choose which reference their data was aligned/called against

**Comment by AlistairNWard** [comment]
It appears that the regularly updated clinvar vcf is mapped to GRCh38. Do we need to include liftover capability if we want to keep an up to date clinvar reference?

**Comment by chmille4** [comment]
The clinvar api has a flag for either grch38 or grch37 coordinates. I assumed that the results would be the same for either but just with different coordinates. But they may not be mapping the new clinvar records to grch37?

**Comment by AlistairNWard** [comment]
So long as they're doing a liftover, that's fine. I was just pulling the vcf that they update every week and it is only maintained in GRCh38 coordinates. If the API can give it to you in 37, there are no problems.

**Comment by AlistairNWard** [comment]
See #226 for reference genome related improvements.
