### ISSUE TITLE
Coverage data is 'truncated' (zero-filled) at end of region for local files

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#106]
When we use http instead of web sockets for getting coverage for remotely served files, the truncation problem goes away.  For local files, we must use web sockets to stream the local file data from the client to the server.  

The bug is intermittent, but consistently occurs every ~6-12 service calls to the coverage service.  Yi surmises that the first leg of samtools view which gets the bam records for the region is ending the stream before the second leg, the coverage service, has been able to read from standard input to samtools -mpileup.

**Comment by AlistairNWard** [comment]
I'm seeing this consistently on Safari for local files over Samba.

**Comment by tonydisera** [comment]
I have a workaround for this which requires a deployment of coverage.sh to production services.
