### ISSUE TITLE
Inheritance for missing variants

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#11]
MYLK2 - call missing variants on proband and a new likely pathogenic variant is discovered. The variant is de novo, but the inheritance column is not populated in the rank variants.

**Comment by tonydisera** [comment]
Fixed.  But it leaves me wondering if we just call for missing variants on the full trio, since marking it as denovo may be misleading if the missing variant shows up in mom or dad.

**Comment by AlistairNWard** [comment]
My personal preference would be to remove the 'call missing variants' from the proband card and make it a global action. Not sure where the button goes, but once selected, I think we should be calling variants on all available BAM files.
