### ISSUE TITLE
Strange behaviour with local files

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#112]
This behaviour is observed for local files being selected over a samba mount to CHPC.

1. On Firefox, after selecting the files, they do not populate the field and so no data gets loaded.
2. On Chrome, I can select the files, but if I select variant files for the Mother, the 'Load' button is greyed out and I can't get the data loaded.

**Comment by AlistairNWard** [comment]
I'm seeing other strange behaviour with these local files. Variants are being displayed that are not present in the file.

**Comment by tonydisera** [comment]
This sounds bad.  Can I get to this samba mount to reproduce the problem?

**Comment by tonydisera** [comment]
Should be fixed now.
