### ISSUE TITLE
gene model tooltip

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#115]
The tooltip for gene features appears in the wrong when the screen is scrolled.

**Comment by tonydisera** [comment]
I can't reproduce this problem, but it may be that I don't understand the issue.  I tried hovering over the gene button to show the gene description in the tooltip.  When I scroll, the tooltip continues to be visible for a few seconds.

**Comment by AlistairNWard** [comment]
I don't even understand my own comment. Missing works and as clear as mud. I'll reopen if I ever figure out what I was talking about.
