### ISSUE TITLE
Gene cards

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#122]
Slightly unfair since they're brand new, but here are a couple of observations from the 1000G example trio.

Go to PDGFB and select the transcript that generates a high impact frameshift annotation. Two problems:

1. The badge in the gene card is a high impact SNP, not indel.
2. Move to another gene and then back to PDGFB and it defaults back to the canonical transcript and the annotation reverts to the original modifier and the badge disappears. We should discuss how to handle badges that result from actions that will be reverted.

**Comment by tonydisera** [comment]
Excellent point, Al.  I noticed this yesterday as well as I was going through the use cases with the new gene badges.  Should be easy to fix by keeping track of the selected transcript associated with the last time the gene was selected.

**Comment by tonydisera** [comment]
Fixed both of these issues.  Pushed to dev-slideout branch.
