### ISSUE TITLE
Tool tips

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#125]
I wonder if it would be better to have the three tool tips (proband, mother and father) stacked together rather than hovering over the respective panels. On my laptop, it isn't always possible to get all the panels on the screen and I can't see the called genotype for the father. If the tool tips were stacked, this would never be an issue.

**Comment by AlistairNWard** [comment]
In addition, if you hover over a variant in either of the parents, you don't see the tool tips for the other parent and the proband. Also, the allele counts for both parents are omitted from the tool tip.

**Comment by tonydisera** [comment]
What would you think about just showing one tooltip with the trio info integrated in?  We already do that with the allele counts on the proband.

**Comment by AlistairNWard** [comment]
Yes that would work. The benefit of the current setup is that all samples are separated so it's easy to see what belongs to what. We should consider what would happen if we have more than three samples, we would to see the basic zygosity and quality info for all samples (I'm assuming), so we should try and lay out the info in the integrated tooltip in a way that scales with increasing samples.

**Comment by AlistairNWard** [comment]
Closing this issue to open an issue on tooltip and inspection panel development.
