### ISSUE TITLE
Variant subtraction or intersection

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#127]
Used for inclusion of larger pedigrees (and akin to ARUP current) methods, provide a filter to subtract or intersect variants from other samples from the proband. For example, if a variant is hom in a parent (or both), remove the variant from the proband track.

**Comment by tonydisera** [comment]
After working with the Guthery datasets, I concur.  This would be a very helpful feature!  Also, including Zygosity in the feature matrix (Rank Variants) would help.

**Comment by AlistairNWard** [comment]
Our current filtering provides much of this. Extra variant filtering will likely move to another app.
