### ISSUE TITLE
Gene list behaviour

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#139]
1. When a gene is being analyzed, no un-analyzed genes can be selected until the analysis is complete.

**Comment by tonydisera** [comment]
I've reworked the state logic for the variant card so that even if the user clicks on multiple gene buttons, only the last gene selected will show in the variant cards.  Also, the caching of genes ('Analyze all' link next to gene buttons) can happen in parallel with the clicking of genes.
