### ISSUE TITLE
Tooltips and inspection panel

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#141]
Rework the tooltips.

1. Hovering over the variant shows a reduced tooltip with minimal information.
2. Select to lock and the option to 'Inspect' is available like the option to 'Unlock'.
3. Selection of inspect opens the 'Variant Inspection' panel on the left. If this is the first time the 'Variant Inspection' panel has been opened, the dropdown at the top of the panel now includes the 'Inspection' option (along with 'Filter' etc.)
4. Inspection panel shows detailed variant information, variant bookmarking and reporting options.

**Comment by tonydisera** [comment]
Implemented. Question:  should we include the allele count bars in the tooltip?  I like to see these at a quick glance at the high impact variants, so I kept them in the tooltip.

<img width="987" alt="screen shot 2016-01-03 at 7 42 21 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082599/47ca7a82-b252-11e5-9766-ec12f977e2c2.png">

**Comment by AlistairNWard** [comment]
Yes, I agree that we should keep the allele count bars in the tooltip. I also think we should keep the position in the tooltip. If I'm looking for a particular variant by position, I shouldn't have to click the variant to examine and see the position. I'm not sure if there are any other values that you really want to see on a scan through, but the counts and positions seem to me to be important. I appreciate that I pushed for removing a lot of the information, so I apologise for going back on that a bit!!!!
