### ISSUE TITLE
Left panel drop down menu

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#144]
Include a drop down menu at the top of the left panel. This will include 'Filter' by default, but will be expanded as other options are exercised (e.g. Phenolyzer, Variant Inspector etc.).

**Comment by tonydisera** [comment]
Implemented as an icon sidebar with the following buttons:  Filter variants, Genes (copy/paste gene set or run Phenolyzer), Bookmark variants, Learn more (links to screen casts, tour, blog posts).
Screen Shot 2016-01-03 at 7.03.16 PM
<img width="497" alt="screen shot 2016-01-03 at 7 03 16 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082536/3cd3299a-b251-11e5-8b87-752fe8deb197.png">
