### ISSUE TITLE
Refseq

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#149]
Include both GenCode and RefSeq transcripts.

**Comment by tonydisera** [comment]
1. Implemented new geneinfo that has transcripts in its sqlite db for both gencode and refseq.  This new geneinfo is deployed on nv-dev and needs to be deployed (along with new db) to production.
2. The refseq annotations are only implemented for vep (not snpEff) at this time.  A new vep refseq db needs to be installed on production.  (It is installed on nv-dev.)

<img width="900" alt="screen shot 2016-01-03 at 7 29 36 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082493/c4bc1aac-b250-11e5-8e84-c5594feac1d8.png">

**Comment by tonydisera** [comment]
Implemented.
