### ISSUE TITLE
Tooltip on AIRE - Also, so variant position on tooltip, all samples when showing tooltip for Mom or Dad's variant

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#150]
In the use case for gene AIRE, Mum and Dad have a het SNP at 21:45,706,924 and the proband has very low coverage and no call. The tooltip (hovering over the variant in Mum or Dad) shows the allele count for the proband only, even though only the parents have the mutation. The AC numbers given for the proband are also not the correct values.

**Comment by tonydisera** [comment]
Fixed.
<img width="612" alt="screen shot 2016-01-03 at 7 28 19 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082453/390b9294-b250-11e5-912a-54f37607dca6.png">

**Comment by AlistairNWard** [comment]
Couple of comments.

1. Maybe we should leave the position in the standard tooltip info. I was looking for this variant, but since we agreed to reduce the info in the tooltip and move to the bookmarks, I had to bookmark variants to determine their position. Probably a bit of info we should keep in the tooltip.

2. Hovering over Mum, I get the info for Mum, but not Dad. I think it would be better if we see the same tooltip as we see when hovering over the proband, e.g. one tooltip with info all all samples.

3. Finally, in the tooltip, the three AF bars are marked as blank, 'mother' and 'father'. I think the proband should be marked as 'proband' rather than blank, but we should probably use the defined names. In the absence of names, we could use 'proband', 'mother', 'father', but as we expand the pedigrees, we would probably want to use the names.

**Comment by AlistairNWard** [comment]
I'm reopening this since I think the previous comments need to be resolved. Specifically, comment 2 above. The tooltip when hovering over a parent gives info for that sample only and not the whole pedigree. Regardless of who you hover over, we should see data for all samples. Consider a case where Mum is a het, but the proband was hom ref. The variant doesn't appear in the proband can't and since hovering over Mum only gives data on Mum, I can't quickly see if there are any alt calls for the child.

**Comment by tonydisera** [comment]
agreed.

**Comment by tonydisera** [comment]
Should we should the allele count bars in the same order (proband, mother, father) when hovering over the variant for mother or father?

**Comment by AlistairNWard** [comment]
I think so. I would just say we show the exact same mouseover regardless of whose variants you're hovering over.

**Comment by AlistairNWard** [comment]
The comments in this issue are fixed, but we still have blank for the proband. This is because the proband is a no call. Issue #274 handles the no call issue, so this can be closed.
