### ISSUE TITLE
How to install gene.iobio locally

### ISSUE THREAD

**Issue by abdoukadri** [tonydisera/gene.iobio#156]
Hi there, 
Is there any instructions on how to install gene.iobio locally? is there a docker installation as for bam.iobio and vcf?

Thanks in advance!!!

**Comment by tonydisera** [comment]
Thanks for your interest.  We don’t have a docker installation for the services required for gene.iobio.  It is on our roadmap.

If you would like to subscribe to our email list, we will let you know about new apps, our dev kit, and new docker installations.

Please feel free to contact me or Chase Miller (chmille4), the IOBIO author and project lead, for more information.

**Comment by AlistairNWard** [comment]
Local install is a beast on its own. Not something to be concerned about in gene.iobio dev.
