### ISSUE TITLE
AF filtering

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#157]
I'm seeing a discrepancy in the AF filter. In the following:

http://goo.gl/zICreC

you should be in the TTPA gene. Select 1000G AF and then we can hover over <0.1% and one variant is left. If we hover over <1%, a different variant is shown and the one that is <0.1% is not as it should be.

**Comment by tonydisera** [comment]
Good catch, Al.  Yeah, it makes sense that we would want the <1% to show all variants <1%, including the lower ranges.  
Implemented.
