### ISSUE TITLE
Rework sidebar so that the background color is different than the cards.  Consider a vertical icon bar that always stays in view rather than the 'tab' button.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#161]

**Comment by tonydisera** [comment]
<img width="447" alt="screen shot 2016-01-03 at 7 03 03 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082252/c7fdf6c6-b24c-11e5-9d8f-454d3130f204.png">
<img width="497" alt="screen shot 2016-01-03 at 7 03 16 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082254/ca6f5648-b24c-11e5-847c-6f1fc29c7a42.png">

**Comment by AlistairNWard** [comment]
Do we want the actual opened panel to also have a different colour, or just the panel with the buttons?

**Comment by AlistairNWard** [comment]
Prior to version 2.0 release, would it be worth looking at the actual panel having a background colour that distinguishes it from the main gene.iobio panel background (white). I spoke with Chase and this was what he meant in our original design meeting on the panel. Might be worth playing before the release.

**Comment by tonydisera** [comment]
I tried that out and wasn't happy with the results.  The problem is the Bookmark panel and the Filter panel.  Both show a number of colored glyphs.  It was hard to find a background color that offered enough contrast.  I'll give it another try and propose some alternative background colors to the team.

**Comment by tonydisera** [comment]
How about a grey background that isn't too dark?  (The problem with going dark is that it makes the colors of the glyphs look off.)

<img width="1367" alt="screen shot 2016-02-02 at 12 58 05 pm" src="https://cloud.githubusercontent.com/assets/8420103/12762528/cacfcbb4-c9ac-11e5-887b-d9dd039cec69.png">
<img width="1367" alt="screen shot 2016-02-02 at 12 58 15 pm" src="https://cloud.githubusercontent.com/assets/8420103/12762530/ccbf8374-c9ac-11e5-959c-63655a0e1cb1.png">
<img width="1373" alt="screen shot 2016-02-02 at 12 58 23 pm" src="https://cloud.githubusercontent.com/assets/8420103/12762540/d41b441e-c9ac-11e5-89ca-3dacbf7a591b.png">

**Comment by AlistairNWard** [comment]
Yeah, I see what you mean. I think Chase's input would be more valuable than mine on this...

**Comment by tonydisera** [comment]
I have the sass variables set up, so this is now easy to change.  I've tried different background colors, but white seems to look the best.

**Comment by tonydisera** [comment]
<img width="211" alt="screen shot 2016-03-06 at 2 57 20 pm" src="https://cloud.githubusercontent.com/assets/8420103/13557337/cae05308-e3ab-11e5-9eb2-0071500cf801.png">
<img width="501" alt="screen shot 2016-03-06 at 2 57 28 pm" src="https://cloud.githubusercontent.com/assets/8420103/13557339/d1347a22-e3ab-11e5-83b7-35c16eed08c5.png">
