### ISSUE TITLE
Phenolyzer

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#164]
1. Add disclaimer to the 'Add genes' button. This is the text from the license agreement. Maybe this should be shortened with just that this function is only for academic and non-profit use, with an additional 'disclaimer' link to the full text?

By using the software, you acknowledge that you agree to the terms below:

For academic and non-profit use, you are free to fork, download, modify, distribute and use the software without restriction.

For commercial use, you are required to contact Stevens Institute of Innovation at USC directly to discuss licensing options.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

2. Implement auto-fill and prompt for phenolyzer terms.

**Comment by tonydisera** [comment]
Added abbreviated text to the right of 'Run' button.  When disclaimer link clicked, full license agreement text displays in side panel, below abbreviated message and run button.
