### ISSUE TITLE
Gene card mouseover expires too quickly

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#173]
When hovering over a gene name, you get a nice description of the gene which you cannot read before the tooltip disappears. Maybe this tooltip should remain in place until the mouse is moved? Or supply a lock, so you can force is to stay long enough to read?

**Comment by tonydisera** [comment]
How much time do you need?!? geez. Working on it.  You are soooo demanding.

**Comment by AlistairNWard** [comment]
I'm a moron, so it takes a good long while for me to read long words...

**Comment by tonydisera** [comment]
You know, you don't have to read out loud. I realize that the gene 'methylenetetrahydrofolate reductase' an atrocious number of syllables.

**Comment by tonydisera** [comment]
Reworked all tooltips on gene buttons.  The tooltip remains as long as the cursor stays over the glyph.

<img width="400" alt="screen shot 2016-02-02 at 12 45 20 pm" src="https://cloud.githubusercontent.com/assets/8420103/12762126/fc6fbaaa-c9aa-11e5-9958-9836728d242c.png">
<img width="268" alt="screen shot 2016-02-02 at 12 45 26 pm" src="https://cloud.githubusercontent.com/assets/8420103/12762129/ffb5c66e-c9aa-11e5-8f2d-6e45891d58d7.png">
<img width="285" alt="screen shot 2016-02-02 at 12 45 34 pm" src="https://cloud.githubusercontent.com/assets/8420103/12762133/02cfc336-c9ab-11e5-8331-a6f7b7900f25.png">
<img width="337" alt="screen shot 2016-02-02 at 12 45 41 pm" src="https://cloud.githubusercontent.com/assets/8420103/12762141/071c2754-c9ab-11e5-91a0-abe8021bc746.png">

**Comment by tonydisera** [comment]
I didn't implement a lock tooltip feature because the click needs to be tied to clicking on the gene button, thereby selecting the gene.  However, we could have a "lock" (and "unlock") link on the tooltip.

**Comment by AlistairNWard** [comment]
The only reason that I could think of for the "lock" / "unlock" functionality would be if we think anyone would ever want to copy and paste the contents of the tooltip. I'm thinking probably not, but if you think it's important we could add that. As far as I'm concerned, this is enough.

**Comment by tonydisera** [comment]
Cool.  I concur.
