### ISSUE TITLE
Clear all filters button

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#174]
If we apply a whole range of filters, it would be nice to have a clear button, to reset all filters to the defaults.

**Comment by tonydisera** [comment]
Implemented.
<img width="244" alt="screen shot 2016-03-06 at 2 57 28 pm" src="https://cloud.githubusercontent.com/assets/8420103/13560823/883fd560-e3e1-11e5-96b8-d22ab3c7d7b9.png">
