### ISSUE TITLE
Bugs with Guthery data set

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#175]
1. Open gene.iobio and add the 4 samples from the UGP12 study.
2. Go to gene GBE1.
3. I'm seeing 'no variants' fairly often and need to keep reanalyzing (just noting that that problem still persists).
4. There is a variant just past 81.64M. Hover over it and only the proband variant shows. It is present in Mum and Dad, though. Hover over the variant for Mum, and it's highlighted in both Mum and proband (but not Dad). Finally hover over Dad and it's highlighted in all three.
5. The tooltip always appears in odd places.

**Comment by tonydisera** [comment]
I can't find a UGP12 study.  Did you mean the UGP02 (A45) Guthery data set?

**Comment by AlistairNWard** [comment]
Odd. There is a UGP12, but the data isn't there. I'm sure I was looking at
that one. Anyway, looked at in A45 and the variant is there, but hovering
over Mum just shows Mum, Dad just shows Dad and Proband shows all three. I
still think we should be seeing all three people regardless of whose
variant is hovered over, but the bug reported isn't showing up here.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
Awesome.   Thanks for hunting down this so I can reproduce it!  You are the best!
