### ISSUE TITLE
Cannot select variant called by Freebayes

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#177]
In the MYLK2 use case, a variant is called with Freebayes, but I cannot select the variant and see the detailed information about the variant in the left panel.

**Comment by tonydisera** [comment]
I can't reproduce this.  I recall fixing some 'called variant' code a few weeks back.  Would you mind trying again to see if this is fixed?

**Comment by AlistairNWard** [comment]
I just tried to recreate this, and couldn't so I guess it was inadvertently fixed.
