### ISSUE TITLE
Displayed badges in analyzed genes refer to highest rank in all transcripts

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#179]
We should think this through before release. It can currently be confusing to see that a gene harbors an interesting variant, but it is difficult to find the offending variant when you move to the gene.

**Comment by tonydisera** [comment]
Would this help?  When the highest impact for the gene's variants is on the canonical transcript, hovering over the impact symbol on the gene button will look like this:
<img width="249" alt="screen shot 2016-02-02 at 12 32 58 pm" src="https://cloud.githubusercontent.com/assets/8420103/12761716/5c54a630-c9a9-11e5-8a41-c2f90dd8ec0d.png">

But if the highest impact for the gene's variants is for a transcript other than the canonical transcript, the tooltip will look like this:
<img width="474" alt="screen shot 2016-02-02 at 12 32 38 pm" src="https://cloud.githubusercontent.com/assets/8420103/12761768/8993f6b4-c9a9-11e5-920b-05ad5dc0ff0b.png">

**Comment by AlistairNWard** [comment]
Not sure. I probably wouldn't read the mouse over. I'd just see there's an interesting variant and click on the gene. Then I look in the ranked variants table for the interesting variant and can't find it. I'll give this some thought.

**Comment by tonydisera** [comment]
Hi Al -  Did you think of a good way to communicate that that the highest impact variant exists on another transcript?  I think you may have mentioned putting an extra column in the Rank Variants matrix....

**Comment by AlistairNWard** [comment]
No, haven't thought about it! I definitely will tomorrow.

**Comment by AlistairNWard** [comment]
I think that this works. Maybe we can revisit later if we think it needs it. Need to update the usecase to explain this feature and maybe put out a blog post. I'll do that.
