### ISSUE TITLE
Release 2.0 blog posts

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#187]
Write blog posts for the following topics:
1. Gene.iobio redesign.
2. Refseq / gencode transcripts
3. Gene cards and analyze all
4. Bookmarks
5. Phenolyzer

**Comment by AlistairNWard** [comment]
1. and 5. are done.

**Comment by AlistairNWard** [comment]
Version 2 post is up. Moving this to the next release milestone as blog posts need to be written for the rest of the series.

**Comment by tonydisera** [comment]
Hi Al --  were all the blogs you wrote posted?

**Comment by AlistairNWard** [comment]
All the written ones were posted, but I need to finish the series. I will put up another post this week and another next week.
