### ISSUE TITLE
Queue Phenolyzer requests so that simultaneous phenolyzer runs don't flood servers

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#188]
Need queue support and testing.

**Comment by tonydisera** [comment]
We have decided to use Yi's new queuing mechanism for the Phenolyzer caching server.

**Comment by tonydisera** [comment]
Well, Chewey did it again.  By Friday morning, he had the damned thing implemented.  Way to go Yi!  It was super easy to make the small changes on the client side to deal with 2 possible states leading up to phenolyzer results (queued and pending).
