### ISSUE TITLE
Question mark in allele counts

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#190]
Example Guthery case A110 - gene HLA-DRB1. In the big pile of variants above 32.552M, I'm seeing quite a few cases where there is a question mark.

**Comment by AlistairNWard** [comment]
I just looked in the VCF file at one of these. After subsetting on the parents and proband, we still have a multiallelic site (genotypes are 0/3, 1/3 and 1/2), so this might be the problem. How are we getting the depth info at the moment? In these files, the AD field (in the genotypes) gives the depth at ref and all alternate alleles, so a 1/3 genotype means we pull from the AD field the values in the 2nd and 4th positions.

This also means that all samples have data in the AD field, so we can still pull depth info for 0/0 individuals and hence show all samples in the tooltip, not just samples with a non reference allele.

**Comment by tonydisera** [comment]
Hi Al,
I'm in the process of fixing the VCF parsing to parse allele counts on multi-allelic records.  I've got it working for GATK, but I'm wondering about the AO field for Freebayes.  If there the vcf record is a multi-allelic, will this field be a comma separated list of allele counts or is it just a total?

Also, is DP considered the filtered depth for Freebayes (as it is for GATK)?  The reason I ask is that I want to use the sum of ref counts + allele counts to show as the total and only show the DP field as "filtered depth" in the Examine Variants side panel.
Thanks!
Tony

**Comment by AlistairNWard** [comment]
AO is defined as a comma separated list, so should be so for any tool that
generates a multi-allelic record. I just took a look at a Freebayes file
and it does have a comma separated list.

Yes, DP is the filtered depth, e.g. only the count of reads used in the
call. Counting up all reads at a locus may be more than DP. For example,
duplicate reads are not counted in DP since they are not considered in the
call.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
Hi Al,
I had to rework the way multi-allelics show allele counts in the variant tooltip.  Here is how it would look.

<img width="333" alt="screen shot 2016-02-01 at 2 18 47 pm" src="https://cloud.githubusercontent.com/assets/8420103/12731595/ebb8c3da-c8ee-11e5-8ec8-b4b4005d44ab.png">

Does that make sense?

Cheers,
Tony

**Comment by AlistairNWard** [comment]
It isn't clear what the three colours represent. I am assuming that the
green represents the allele represented in the record (e.g. the G->GA
insertion), but it isn't clear. Also, I think it should be mentioned what
allele the grey bar supports. Maybe we include an extra line in the tooltip
to state that another allele was observed at this locus and state what it
is.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
Excellent points as always.  How about something like which only shows when we are dealing with a multi-allelic:
![gene-tooltip-multiallelic](https://cloud.githubusercontent.com/assets/8420103/12738839/981a4176-c921-11e5-9fc3-2a533d14b40b.png)

**Comment by AlistairNWard** [comment]
This may or may not have been an opportunity to start learning Illustrator,
but perhaps we include a legend with the read counts. Something along the
following lines? I'm thinking that we should probably include the count of
reference alleles as well for completeness?





Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
4 blank lines?  How will that help? ;-)

**Comment by AlistairNWard** [comment]
I wrote it as an email and included the picture. Looks like it didn't carry over to github though! Let's try this...

![image](https://cloud.githubusercontent.com/assets/523111/12754032/9590fb22-c997-11e5-82a3-53bbdd8d701b.png)

**Comment by AlistairNWard** [comment]
That didn't seem to work. One more try...

![ac-bar](https://cloud.githubusercontent.com/assets/523111/12754058/afd61918-c997-11e5-922b-75dcbfbc28c1.png)

**Comment by tonydisera** [comment]
I like that.   I'll give it a try.

**Comment by tonydisera** [comment]
How does this look?
<img width="353" alt="screen shot 2016-02-02 at 5 25 41 pm" src="https://cloud.githubusercontent.com/assets/8420103/12770180/909996e4-c9db-11e5-8bd7-ce20dcddca1b.png">
<img width="339" alt="screen shot 2016-02-02 at 6 32 20 pm" src="https://cloud.githubusercontent.com/assets/8420103/12770192/971a53e6-c9db-11e5-9aa6-c5840830a4cb.png">

**Comment by AlistairNWard** [comment]
Looks good to me!
