### ISSUE TITLE
iobio services deployment

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#191]
Deploy the following changes to production iobio instances (nv-green and nv-blue)

1.  Coverage services fix for truncated samtools data.
2.  geneinfo - new server code and sqlite3 db to support refseq transcript sets.
3.  Phenolyzer changes - relax timeout, caching
4. genetopheno server
5. hpo server
6. vep server (command line options)
7. vt (new command line options to support vt subset)
8. new annot.db with latest exac allele freqencies

**Comment by tonydisera** [comment]
Yi text:

some more changed I made on nv-dev. Since we need to package up the database used for gene2phenotype and hpo, the *.db files need to be in separate directories. So I changed the server.js file to, instead of e.g. opening ./hpo.db, open ./hpo/hpo.db. I also created these directories and moved the db file into them.  gene2pheno and hpo nv-dev needs to be restarted because of these changes, but I’m not sure which of the scripts listed by ‘forever list’ are the corresponding ones. When you get a chance, can you restart them on nv-dev? I’ll in the meanwhile package them up for deployment
also just want to make sure, the db file for hpo and genetophenotypes, as well as the db file in /mnt that is for af, are ready for packaging right?
ok and gene info too (which I believe it is now called genewidget.iobio)

**Comment by tonydisera** [comment]
So I guess this means that we don't want to start hpo, genetopheno, or geneinfo with the --workingDir ~/workdir command link argument for forever start on production, right?

Should we do the same thing for afgblive?  Right now, it assumes that that annot.db is in workdir/data.

**Comment by yiq** [comment]
we still would want this switch. This is for all dockerized services so
that, when needed, temporary files are created in ~/workdir instead of ~/.
The actual path to the database file is actually specified at the beginning
of the server.js files (e,g, "./afdata/af.db", which becomes
~/workdir/afdata/af.db since ~/workdir is the current directory)
