### ISSUE TITLE
Disclaimer for gene

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#193]
We need to include a disclaimer that gene.iobio is intended for research purposes, is not a clinical app and shouldn't drive any treatment decisions. I'll do a search around to try and find good terminology.

Maybe we include this disclaimer at the bottom of the "Learn more" panel, but include a disclaimer link at the bottom of the page that opens up the panel?

**Comment by AlistairNWard** [comment]
I ripped the following text and updated it for our use. This may well be sufficient for a collapsible disclaimer.

The University of Utah makes no claims that iobio applications, including gene.iobio are approved for clinical use. All users of iobio applications including gene.iobio understand and accept that any information gained by using these applications, whether the information comes from visualization, processing, internal or external databases, or analysis, may not in any way be used for clinical purposes. The University of Utah makes no representation that iobio or gene.iobio is either safe or effective for any intended use for which research may currently be performed.

iobio, or any iobio applications ARE TO BE USED FOR RESEARCH PURPOSES ONLY. USE FOR CLINICAL PURPOSES IS EXPRESSLY FORBIDDEN. Approval of iobio applications for clinical use has neither been applied for, nor received, in any country, including the United States of America.

**Comment by tonydisera** [comment]
<img width="288" alt="screen shot 2016-03-03 at 10 14 10 am" src="https://cloud.githubusercontent.com/assets/8420103/13502617/e6dcad7a-e128-11e5-9281-e12d2f5ff9c0.png">
<img width="273" alt="screen shot 2016-03-03 at 10 14 18 am" src="https://cloud.githubusercontent.com/assets/8420103/13502623/ea53b002-e128-11e5-8095-f594aee05f85.png">

**Comment by AlistairNWard** [comment]
I think we probably need a link to the disclaimer somewhere more prominently also. Does it make sense to put the disclaimer right at the top of the page next to or under the 'gene.iobio' title? Or down at the bottom with the 'powered by' stuff?

**Comment by tonydisera** [comment]
I agree.  What do you think about this?
<img width="338" alt="screen shot 2016-03-03 at 8 38 49 pm" src="https://cloud.githubusercontent.com/assets/8420103/13517384/24e19fd4-e180-11e5-836a-5ae97081aa2b.png">
<img width="742" alt="screen shot 2016-03-03 at 8 39 02 pm" src="https://cloud.githubusercontent.com/assets/8420103/13517388/2cb7f1c2-e180-11e5-8c29-5b9c05b8338c.png">

**Comment by AlistairNWard** [comment]
Yes, I think that would do it.
