### ISSUE TITLE
'Variant details' button for left panel

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#195]
I think this would be very useful. Let's say I click on a variant and bring up the details in the left panel. I now jump to 'Filter' and mess about with some filters. I now want to go back to the variant I was looking at. I actually have to go back and select the variant from the main card. It would be better if I could click on a 'Variant details' button and go back to the details I was previously looking at.

Similarly, if I then bookmark the variant, I want to be able to get from the bookmarks panel back to the variant details without having to go back to the main card. I'm not sure what the desired method of implementation would be. If in bookmarks, I click on a variant, the variant is highlighted on the main card, but do I want to jump to variant detail panel to see the details of the variant as well? Alternatively, when I select a bookmarked variant, it is now highlighted. If I now click on the 'Variant details' button, this bookmarked variant is displayed in the panel.

**Comment by tonydisera** [comment]
I added the icon sidebar button 'Inspect Variant'.  
<img width="282" alt="screen shot 2016-02-05 at 9 55 44 pm" src="https://cloud.githubusercontent.com/assets/8420103/12864766/e77b9596-cc53-11e5-83cb-cb5bd1fc2702.png">

**Comment by tonydisera** [comment]
Yi suggested that sidebar show 2 panels, vertically split.  So each icon button would have a checkmark, allowing 2 panels to be visible at one time.  I'm going to add this as a new issue for 2.1.

I agree that when a user clicks on a bookmarked variant, it would be good to show the details.  For now, how about if we show the variant details at the bottom of the bookmark panel when the user clicks on the bookmarked variant.

It would also be good for the column in the Rank Variants matrix to be highlighted.

**Comment by AlistairNWard** [comment]
We should certainly trial this idea, but make sure we test on laptops as
well as large screens. Most of the buttons lead to significant
functionality / information, so we don't want to be sure things are
implemented in a way that doesn't compromise function. Obviously, you have
to choose to have two panels open simultaneously, but we should just be
sure we don't overcomplicate the interface.

I don't know that it's necessary for an intermediate solution. For now, if
we have an 'Inspect variant' panel, we can just jump to this once a variant
has been selected. Even if we implement the option to show two panels
simultaneously, we don't necessarily want to default to opening the info at
the bottom of the bookmarks panel for the reasons above. On a laptop, this
may not be helpful functionality.


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
Agreed.  Let's try to figure out the best UI for this when you are out next week.
