### ISSUE TITLE
Mark gene badges that cannot be analyzed

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#198]
Select a gene list including PDHA1 and then run 'Analyze all' using the Platinum genome data set. Gene then marches through all the genes marking them as analyzed, except 'PDHA1' since chrX is not included in the data set. We should mark the badge with something to indicate that the gene is analyzed, but no data exists.

**Comment by tonydisera** [comment]
This has been fixed.  An alert glyph shows for those genes that cannot be analyzed.

<img width="566" alt="screen shot 2016-03-15 at 10 29 54 am" src="https://cloud.githubusercontent.com/assets/8420103/13785380/f5ff5cde-ea98-11e5-9b1c-a566f199a7f4.png">
