### ISSUE TITLE
Filtering of uploaded vcf file

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#2]
Check for filter tags in the 'FILTER' field of the uploaded vcf file. It is likely that the uploaded vcf file will contain records that have failed filters and should not be displayed. Here are a couple of use cases for vcf files generated by the gkno pipelines for freebayes and gatk (these will not be unusual):

*Freebayes

Variants are called and the resulting vcf is filtered, but the records that fail the filter are not removed. Instead, those passing filters are marked with 'PASS'.

*GATK

Variants called with GATK are usually filtered using VQSR. This applies different tags to the filter field based on the confidence in the variant. Thus, if the choice is to display the most conservative set, only those marked with a particular value should be displayed. There will be multiple values that the user may wish to display, picking from successfully less conservative filtering criteria.

It would probably be beneficial when parsing the uploaded vcf to keep track of the observed values in the FILTER field. Once parsing is complete, all variants could be shown, all the observed tags in the FILTER field populate a drop down menu that the user can select. If the tag 'PASS' is present, only those records should be shown. Maybe a 'Removing failed variant sites...' dialogue appears to keep the user informed of additional steps being taken by gene.

**Comment by AlistairNWard** [comment]
I think this is something we should move up the priority list. The VCF files usually contain lots of variants that failed filters and by default we should remove them. This could be part of the 'Call Variants' tab, included as a filter.

**Comment by tonydisera** [comment]
Rename to quality tag.

**Comment by tonydisera** [comment]
How about . (unassigned) rather than . (unknown) since unknown implies that the status could not be determined?

**Comment by AlistairNWard** [comment]
Yes, that works.

**Comment by AlistairNWard** [comment]
Sorry to reopen! Feel free to just ignore me and close, but thought I'd air a thought. Since, by default, we only display PASS variants if they are present, maybe we should also include PASS at the top of the list of different values. I can't test right now (poor internet, I assume), but is the PASS value in the filter panel boxed and the blue 'Filter status' tag shown in the variant cards by default?

**Comment by AlistairNWard** [comment]
Ok, managed to get gene open and yes, PASS is boxed and the filter tag appears, so this is just a question about the order.

**Comment by tonydisera** [comment]
I will change the sort order so that PASS always appears first, followed by other entries, sorted alphabetically.
