### ISSUE TITLE
Add 'Demo it' to top of Help Sidebar, change Help Resources to Examples

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#201]

**Comment by tonydisera** [comment]
<img width="282" alt="screen shot 2016-02-04 at 1 04 00 pm" src="https://cloud.githubusercontent.com/assets/8420103/12828072/e329204a-cb3f-11e5-915f-cc6c227db6a7.png">

**Comment by AlistairNWard** [comment]
Yeah, I think that this should just override whatever you have loaded and load up the example data in the current tab. This brings up one other issue that is beyond my understanding. When running gene.iobio, the history is filled up with a thousand gene.iobio entries. Is this something that can be avoided? The reason I bring it up here is that perhaps you have a data set loaded and you click 'Try it out' and the sample data overwrites yours. You might just want to click back, to return to your original data, but that isn't really feasible.

**Comment by tonydisera** [comment]
I created a separate issue (#210) for the gene.iobio history problem.
