### ISSUE TITLE
Did behaviour of gene badges change on import of bookmarks?

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#204]
In the workshop, I used Phenolyzer to generate a gene list, then imported variants from Gemini. The gene badges then drove which bookmarks I looked at. This seems to have changed so that now all the gene badges are replaced with those for which there are bookmarks and the ranked gene list is lost. I would argue for the previous functionality of leaving the gene badges as is. Maybe if there is no gene list entered, we can populate with the bookmarked genes, otherwise, I would argue that we want to see the list of genes already entered.

**Comment by tonydisera** [comment]
Oh, sorry about that!  Yes, that behavior was most likely changed by me when I introduced the check marks for the phenolyzer list.  I will change the logic back so that existing genes are not lost.  If the bookmark glyph is in the gene button, it will be apparent which one come from phenolyzer vs bookmark.  Come to think of it, it would be cool to have a glyph that indicates that the gene came from a phenolyzer gene list.

**Comment by AlistairNWard** [comment]
I agree! I wonder if we should maybe change the gene badge outline colour
or something to indicate presence in the Phenolyzer list etc.? I'm just
thinking that the more glyphs we introduce, the bigger the badges get.
Keeping them smaller might keep it simple and clean.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
I'm working on this right now.

**Comment by AlistairNWard** [comment]
A suggestion for the gene panel:

![img_3222](https://cloud.githubusercontent.com/assets/523111/13228980/a5e8222c-d96c-11e5-8619-dcfb1bf1d261.JPG)

We have a display section at the top with check boxes for each gene set (Phenolyzer has its own gene set, then a check box for each imported set). Optionally, we can let the user define a colour that will outline the gene badge. Here we can select which genes appear as badges. So if you want to work through Phenolyzer genes only, you just check it and no other gene sets. 

We could (not sure if this is a good suggestion) do away with the Import gene set drop down and just keep the box to paste into always present. We then paste a list of genes into the box, give the set a name and click 'Done'. The set now appears with a check box in the Display list (default unchecked) and in a list (sorry, I added this afterwards and is scrunched!). Each set can then be removed, or edited.

In the bookmarks panel, we could also add the same display field at the top with a list of selectable bookmark sets whose genes should be shown as badges. Maybe the same deal as with importing gene sets, we allow a name for a bookmark set, a list of sets that can be edited, deleted. Maybe this list also lets us choose which bookmarks to display in the left panel?

**Comment by AlistairNWard** [comment]
Sorry, image was cropped and on its side!

![img_3223](https://cloud.githubusercontent.com/assets/523111/13229161/7d491492-d96d-11e5-80db-e475f066afad.JPG)

**Comment by tonydisera** [comment]
Great suggestions as always, Al!  I have a few questions:

1.  Where do we show the gene names for the imported gene sets?  
2.  What do we color of border do we show for genes that come from multiple sources; for example a gene that is both in the phenolyzer list and the gene set list, or the bookmarks and phenolyzer.

**Comment by AlistairNWard** [comment]
Let's talk about this on the call today. But:

1. I was thinking that if you click 'Edit' next to a defined gene set, it expands to show all the genes in the set. You can then delete individual genes or add new genes to the set. This is a bit clunky though. Means you need to click edit just to see the genes. Maybe need to think this through a bit more.

2. Yeah, you mentioned this and I totally ignored it! We could always do something like instead of putting a coloured border around the whole badge, we colour the top edge based on gene set and the bottom from bookmark set. If the gene is in multiple sets, we use black, for example, and hovering over the badge shows the lists it is in? We could also just do the border for gene list and use a glyph for presence in a bookmark set. Again, if the gene is in multiple gene (or bookmark) sets we use a a black border or a different glyph and you have to hover to get the info.

All that said, I think we might be trying to overload too much information into the badges. It might be worth having the option to display the gene/bookmark sets of choice as badges, but the badge itself is left alone. We could put a glyph to indicate a bookmarked variant exists in the gene and leave it at that.
