### ISSUE TITLE
Clear all gene badges

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#216]
Can remove gene badges one by one, but need to be able to clear all.

**Comment by tonydisera** [comment]
I have added a 'Clear all' link to the right of the 'Analyze all' link.  When clicked, the user must confirm before all of the genes are removed from the list.
<img width="1320" alt="screen shot 2016-03-17 at 12 08 19 pm" src="https://cloud.githubusercontent.com/assets/8420103/13856070/20d63ea4-ec39-11e5-83db-05be70672710.png">
