### ISSUE TITLE
Include support for GRCh38

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#226]

**Comment by AlistairNWard** [comment]
I propose that we try and implement an iobio wide solution to genome references here. We could create our own file/database that we host that contains information on a whole range of reference genomes that we can update periodically.

1. BAM files provide a list of all reference sequences. We could create a key consisting of, for example, the top 20 sequences in the BAM along with their lengths. When a BAM is selected, we parse the header and build the key, then see if this exists in the database. If not, the user will need to select the reference genome, picking from those defined in the database.

2. VCF files can optionally include the 'reference=<file>' line in the header. If present, we could check this against the database. If the user has modified the filename from standard, we wouldn't be able to determine this.

bam.iobio.io
No explicit need to check for references. Just ensure that the chromosome wheel is not hardcoded, but picks the longest reference sequences from the header.

vcf.iobio.io
As bam.iobio.io above.

gene.iobio.io
1. If we parse the headers of the three BAM files and can determine the genome reference, include a check to make sure they all come from the same one.

2. Allow the reference genome to be selectable. Maybe this appears in the data modal, but we should have the genome name appear clearly somewhere on the gene page. The available genomes would be pulled from the iobio database.

3. The iobio database should, along with reference genome name and key, should include the URLs and parameters for external tools or databases, e.g. clinVar and VEP, so that the correct annotations are pulled once the reference genome is defined. Each stored reference genome should also include the gff file to define the exon coordinates in that build.

4. We will need to store the location of the FASTA file so that variant calling can call against the correct genome.

**Comment by tonydisera** [comment]
You've outlined a great plan, Al.

**Comment by tonydisera** [comment]
I've made quite a bit of progress here.  I probably only need a few more days to get this finished.

**Comment by tonydisera** [comment]
TODO for IOBIO backend:
1.  Update gene.iobio local install to include new clinvar vcf files all all backend changes mentioned below
2.  New genomeBuild server
3.  Update geneinfo (and db)
4. New fasta files for GRCh38
5. New vep cache for GRCh38 (gencode and refseq)

**Comment by tonydisera** [comment]
Hi Al,

The genome build feature is ready to validate on gene.iobio.  (I haven't made the changes to vcf.iobio yet.)

I've asked Yi to deploy all of the backend changes on nv-blue (stage), but until then, you can validate by either checking out gene.iobio on the dev-genomebuild or by running gene.iobio on nv-dev.  

I won't be able to merge dev-genomebuild back to the dev branch until the staging server has all of the backend changes.

Thanks!
Tony

**Comment by tonydisera** [comment]
Here is the list of backend changes to support genome builds:
1. genomebuild - new server.js and genomebuild.db.  This has the meta data on species and builds supported by IOBIO.  

2. geneinfo - new server.js (in ~/genewidget.iobio) and gene.iobio.db (in ~/workdir).  The gene and transcript tables now have species and build columns.  Also, transcript table has columns for ccds_id and is_canonical which will be used in a later release to correctly flag the ‘canonical’ transcript based on the criteria documented by Gencode and RefSeq.

3.  af - changes to afServer.js and af.db (in ~/workdir/data/).  The tables exec and g1k have been renamed to exac and g1k_GRCh37 and exac_GRCh37.  Tables for exac_GRCh38 and g1k_GRCh38 have been added.  (Eventually, it would be nice to generalize this to extend beyond allele frequencies and incorporate different genome builds.)

4. New vep cache files for GRCh38, for both gencode and refseq gene transcripts.

5. Small change to vep.sh to remove hardcoded assembly command line arg.

6. New reference fasta files for GRCh38 and hg19 (UCSC).

7. New clinvar vcf files for GRCh38 (and GRCh37 has been renamed) that will need to be included in the gene.iobio local instance (for offline access).  
https://s3.amazonaws.com/iobio/samples/vcf/clinvar.GRCh38.vcf.gz
https://s3.amazonaws.com/iobio/samples/vcf/clinvar.GRCh37.vcf.gz

**Comment by AlistairNWard** [comment]
Ok, testing can be performed on this now using all GRCh38 files. Note that the BAM files are generated by taking the GRCh37 alignments, reverting to FASTQ and then realigned to GRCh38. The VCF file was generated as a liftover from the GRCh37 VCF. So do not expect the BAM coverage to match the VCF coverage!

http://nv-dev.iobio.io/gene.iobio/?species=Human&rel0=proband&rel1=mother&rel2=father&build=GRCh38&name0=&bam0=https://s3.amazonaws.com/iobio/samples/bam/NA12878.GRCh38.bam&affectedSibs=&unaffectedSibs=&genes=PMS2&gene=PMS2&vcf0=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.GRCh38.vcf.gz&sample0=NA12878&name1=&vcf1=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.GRCh38.vcf.gz&name2=&vcf2=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.GRCh38.vcf.gz&bam1=https://s3.amazonaws.com/iobio/samples/bam/NA12878.GRCh38.bam&bam2=https://s3.amazonaws.com/iobio/samples/bam/NA12878.GRCh38.bam&sample2=NA12891&sample1=NA12892

**Comment by AlistairNWard** [comment]
Everything seems to be working well for me.
