### ISSUE TITLE
Proband only polymorphism / Proband only homozygous

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#23]
Add new rows in matrix for inheritance -
1. 'Proband only polymorphism'. This would be any variant that is present in the proband as either a heterozygous or homozygous alternate, but is homozygous reference in all other samples - just the parents in this case.
2.  'Proband only homozygous' would be a homozygous alternate site in the proband, where all other samples show homozygous reference or are heterozygous.

**Comment by AlistairNWard** [comment]
Are these necessary?

**Comment by tonydisera** [comment]
I don't think so, but this is your call as you understand the subtleties here.  Since we show the HOM badge in the feature matrix, this may be not as necessary.

**Comment by AlistairNWard** [comment]
I'm going to close this. I don't think this really adds to much. We already have the zygosity filters and inheritance models, so I think we're covered. We will add stuff for sibs from a different issue.
