### ISSUE TITLE
gene.iobio URL needs to be able to specify gene transcript set (gencode vs refseq) and the transcript used for the current gene

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#230]
In addition to providing the gene source in the URL, a site specific setting should be allowed.  (The URL parameter would override the site specific setting.)

**Comment by tonydisera** [comment]
Hi Al.  I have a question about the auto-switching to the different gene source.  I'm adding code so that a site can set the default gene source.  For example, ARUP will want to default to RefSeq.  So as it stands, all genes will bring up the RefSeq transcript set until a Gencode only gene is encountered.  Then the user is warned and the transcript set (and dropdown) is changed to Gencode.  All subsequent gene selection then use the Gencode transcript set.  Does this seem right?  I hate to complicate things, but in ARUP's case, since the site defaults to using RefSeq, shouldn't all genes except the Gencode only ones use RefSeq transcripts?

**Comment by tonydisera** [comment]
Hi Al.  Tony again.  I think I've answered my own question.  If a site specific gene source is provided, the app will always default to that unless a gene is selected that isn't in that gene set.

**Comment by tonydisera** [comment]
To validate:  

1.  in genesDeployment.js, set siteGeneSource = "refseq".

2. run gene with this url
http://localhost/gene.iobio/?rel0=proband&rel1=mother&rel2=father&genes=BRCA2,TP53,AC002429.5,BLACAT1,BRCA1&name0=NA12878&affectedSibs=&unaffectedSibs=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&rel=mother&sample0=NA12878&name1=NA19238&sample1=NA19238&name2=NA19239&sample2=NA19239&gene=BRCA2

3. Notice that when you click on AC002429.5, you will see this warning label.


4.  Now when you click on another gene, the transcripts default back to refseq.

**Comment by AlistairNWard** [comment]
Testing now. But before I go digging in, I agree with your earlier comment. If you're working with refseq, you should always see refseq, unless a gene doesn't have a refseq transcript. You should be switched to gencode for that gene only and returned to refseq for subsequent genes.

**Comment by AlistairNWard** [comment]
Put in the URL and I'm looking at the NM... refseq transcript, but the drop down still says Gencode. Clicking on AC002429.5 creates the desired behaviour as described. Clicking back on BRCA2 resets the dropdown to refseq. Just need to fix it in the initial load.

Using geneSource=refseq seems to work without this problem.

**Comment by tonydisera** [comment]
Excellent catch!!

**Comment by AlistairNWard** [comment]
This is working.
