### ISSUE TITLE
Rank variants order

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#235]
The ordering of rows for ranking has changed. We should keep ClinVar on top by default, not SnpEff.

**Comment by tonydisera** [comment]
My rationale is that a high impact variant trumps a moderate variant with clinvar annotations.  But you make a valid point.  There are so few clinvar variants that they should stand out.  Perhaps gene.iobio should only rank only on 'pathogenic' variants and 'likely pathogenic' but not on 'uncertain significance'.

**Comment by AlistairNWard** [comment]
I thought we were only ranking on pathogenic and likely_pathogenic. If not, yes we should.
