### ISSUE TITLE
Odd behaviour when filtering on filter status

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#242]
Try the following vcf:

http://nv-dev.iobio.io/gene.iobio/?rel0=proband&rel1=mother&rel2=father&genes=BRCA1&gene=BRCA1&name0=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.platinum.vcf.gz&affectedSibs=&unaffectedSibs=

And select the filter panel. There are three filter status values. Select both the non-PASS values. The table has white space between columns.

<img width="451" alt="screen shot 2016-03-08 at 12 06 56 pm" src="https://cloud.githubusercontent.com/assets/523111/13609305/52a24988-e526-11e5-99d8-7c5c71c7aecb.png">

**Comment by tonydisera** [comment]
How weird is that?!?  Yes, I see the same problem.  I’ll write up an issue.

Tony
