### ISSUE TITLE
Number of variants loaded is erratic

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#247]
Internet is super slow so I haven't tested extensively, but I seem to get a different number of variants loaded every time I open this:

http://nv-dev.iobio.io/gene.iobio/?rel0=proband&rel1=mother&rel2=father&genes=BRCA1&gene=BRCA1&name0=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.platinum.vcf.gz&affectedSibs=&unaffectedSibs=

First time was 156 with 150 displayed (only the PASS variants):

<img width="219" alt="screen shot 2016-03-10 at 2 47 40 pm" src="https://cloud.githubusercontent.com/assets/523111/13682273/1c96cc38-e6cf-11e5-80e4-3621467e69db.png">

Then I only show OverlapConflict from the filter status and I now load 147 of which 4 are displayed:

<img width="189" alt="screen shot 2016-03-10 at 2 48 33 pm" src="https://cloud.githubusercontent.com/assets/523111/13682316/3bf3cff4-e6cf-11e5-8f50-5a07c266ff08.png">

I went back to PASS variants and now have 166/176 shown:

<img width="249" alt="screen shot 2016-03-10 at 2 49 14 pm" src="https://cloud.githubusercontent.com/assets/523111/13682339/5664af48-e6cf-11e5-811a-5434f1a86884.png">

Next load, with default PASS has 155/165 shown.

**Comment by AlistairNWard** [comment]
Follow up. It looks like some variants got dropped on some iterations. The SNP (seen four times and listed as overlapConflict each time) at 41,273,095 was not seen the first time I ran this set. I only saw 4 variants. Now I see 8 as there should be.

**Comment by tonydisera** [comment]
Yes, I see this same problem with the proband alternating between 176 and 156 variant.  The good news is that when I point gene.iobio to nv-green with Chewey's heroic fix, the variant count consistently comes back at 176.

**Comment by AlistairNWard** [comment]
Yep. Will do.

**Comment by tonydisera** [comment]
Hi Al.  The latest gene.iobio with Yi's minion fix is out on nv-dev.  http://nv-dev.iobio.io/gene.iobio.  So you can give this another try to see if the counts are consistent now.

**Comment by AlistairNWard** [comment]
I've tried this a few times now and consistently get 176 variants, so I'm happy to call this fixed.
