### ISSUE TITLE
snpEff errors - ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#249]
Select gene PDHA1 on spiked in platinum wgs variants for training session.  The following errors are produced in the snpEff error log:

Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: Error while processing VCF entry (line 151) :
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: X        19369471        .        G        T        1039.74        PASS        AC=1;AF=0.001282;AN=780;BaseQRankSum=1.46;ClippingRankSum=0.391;DP=53498;FS=0.814;GQ_MEAN=109.63;GQ_STDDEV=53.79;InbreedingCoeff=-0.002;MLEAC=1;MLEAF=0.001282;MQ=60;MQ0=0;MQRankSum=0.303;NCC=0;QD=12.23;ReadPosRankSum=1.12;SOR=0.578;VQSLOD=2.15;culprit=FS;set=Intersection;VT_AC=1;VT_AN=4;BGAF_1KG=0;BGAF_EXAC=0        GT:AD:DP:GQ:PL        0/0:52,0:52:99:0,104,1642        0/1:44,41:85:99:1087,0,1161
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: java.lang.ArrayIndexOutOfBoundsException: 1
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: WARNINGS: Some warning were detected
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: Warning type        Number of warnings
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: WARNING_TRANSCRIPT_INCOMPLETE        1
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: WARNING_TRANSCRIPT_NO_START_CODON        1
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: java.lang.ArrayIndexOutOfBoundsException: 1
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: at ca.mcgill.mcb.pcingola.stats.TsTvStats.sample(TsTvStats.java:97)
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: at ca.mcgill.mcb.pcingola.stats.VcfStats.sample(VcfStats.java:57)
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.iterateVcf(SnpEffCmdEff.java:301)
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.runAnalysis(SnpEffCmdEff.java:1026)
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: at edu.bostoncollege.chase.VariantMultiThread.run(VariantMultiThread.java:44)
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: Error while processing VCF entry (line 151) :
Mar 11 16:53:30 ip-172-32-45-253.ec2.internal docker[5307]: X        19369471        .        G        T        1039.74        PASS

**Comment by tonydisera** [comment]
Full log is here.

[snpeff-err.log.txt](https://github.com/tonydisera/gene.iobio/files/169653/snpeff-err.log.txt)

**Comment by AlistairNWard** [comment]
Add this into the SnpEff discussion. Let's figure out the future of SnpEff in gene before spending time on issues.
