### ISSUE TITLE
When multiple snpEff impacts or effects exist for a variant, force highest impact one to show first (for coloring)

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#25]
For example, if a variant has both a 'high' and 'moderate' snpEff impact for a transcript (e.g. mutation causes both a splicing impact and is a missense variant) make sure that the most deleterious impact/effect is used to color the variant.  Right now, the variant might be colored as 'Moderate', but filter both on 'Moderate' and 'High' impact.

**Comment by AlistairNWard** [comment]
snpEff has been removed, so this really isn't pressing!
