### ISSUE TITLE
Hover over help for filter status

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#254]
I'll write the text and add here.

**Comment by tonydisera** [comment]
I've put in my clumsy text for now, attempting to explain the VCF filter status field.  Please feel free to revise, Al. :-)

<img width="184" alt="screen shot 2016-03-13 at 4 38 37 pm" src="https://cloud.githubusercontent.com/assets/8420103/13731887/2e627e40-e93a-11e5-8b7d-fc3ba707385b.png">
