### ISSUE TITLE
ClinVar - not provided has the same symbol as benign

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#266]
This should be the same as Other.

**Comment by tonydisera** [comment]
I think that this might be a variant in clinvar with different categories.  In this case, the color of the glyph should probably be gray.  Let's discuss.  This is a super easy fix so we can slip it in tomorrow am.

This is an example of multiple clinvar categories -

<img width="379" alt="screen shot 2016-03-13 at 11 18 59 pm" src="https://cloud.githubusercontent.com/assets/8420103/13735709/6a37f58e-e972-11e5-8910-e5da6f559d8c.png">

**Comment by tonydisera** [comment]
This is a tricky one.  So there is a summary classification in ClinVar that does NOT correspond to specific disease/disorder categories:

<img width="790" alt="screen shot 2016-03-22 at 9 11 13 am" src="https://cloud.githubusercontent.com/assets/8420103/13956397/31e52a10-f00e-11e5-8259-4c6e0ee109ff.png">

And then detailed submissions, which then associate a summary classification with the disease/disorder:
<img width="1132" alt="screen shot 2016-03-22 at 9 11 22 am" src="https://cloud.githubusercontent.com/assets/8420103/13956448/66c270a8-f00e-11e5-9417-b6ff96253aff.png">

**Comment by tonydisera** [comment]
Here are the entries to parse to get the key for the submission reports from the eutils summary query:
<img width="762" alt="clinvar_summary" src="https://cloud.githubusercontent.com/assets/8420103/13956828/c5d02d82-f00f-11e5-8499-f47bc74502a2.png">

Use these RCV ids to run the query to get the submissions:
<img width="885" alt="clinvar_submission_detail" src="https://cloud.githubusercontent.com/assets/8420103/13956836/d5066c1c-f00f-11e5-9e36-2e1bf8a867c6.png">

**Comment by AlistairNWard** [comment]
I wonder if the best thing to do is get all the clinical significance terms
and display the most severe in the tooltip/rank variants table, but
distinguish between those that have more than one term. Then in the inspect
panel, we can build in all this extra information. Basically, when looking
in the rank variants table, variants with any high impact clinical
significance will be highly ranked, but the user is informed that they need
to look into it in more detail in the inspect panel.


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
I like this idea.  Once snag is that the individual Clinical Significance categories are not provided on the summary record, only on the individual submission entries.  But this wouldn't cost that much in terms of response time if the app only grabs the individual ClinVar clinical significance categories in cases reported in the summary as 'Conflicting interpretations of pathogenicity'.

**Comment by tonydisera** [comment]
Back to original use case, should we ignore 'other' and 'not provided' in this case?  It seems like these categories are not as concrete as 'benign'.  Tough call.

<img width="349" alt="screen shot 2016-03-22 at 10 39 26 am" src="https://cloud.githubusercontent.com/assets/8420103/13959678/b4afe154-f01a-11e5-94ac-cafe2bec1717.png">

Here's the ClinVar page for this variant:
[http://www.ncbi.nlm.nih.gov/clinvar/variation/21030/](http://www.ncbi.nlm.nih.gov/clinvar/variation/21030/)

**Comment by AlistairNWard** [comment]
Yeah, it's tough. I think having multiple terms listed like that is
confusing, but only supplying a single category implies consensus. If there
are multiple categories, maybe we pick the most important (pathogenic, then
likely pathogenic, etc), and then indicate that there are multiple values
and suggest looking in the inspect panel where we provide more detail?


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
This sheds some light on the ClinVar Clinical Significance summary:

http://www.ncbi.nlm.nih.gov/clinvar/docs/clinsig/

Based on this, I think we can safely ignore 'other' and 'not provided' and only grab the clinical significance from the detailed submissions when the summary shows 'Conflicting interpretations...'.

I'm thinking of punting on this for now....

**Comment by AlistairNWard** [comment]
Agreed, I think we can ignore other and not provided. I'm happy for this to
be pushed back to a later release.


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC
