### ISSUE TITLE
Bookmarks updates

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#277]
1. Should we make the text for the gene a different colour to the variant so that they stand out more?

**Comment by tonydisera** [comment]
Agreed. I changed the color and font size of the gene link in bookmarks and decreased the vertical padding.  
<img width="261" alt="screen shot 2016-03-17 at 10 35 55 am" src="https://cloud.githubusercontent.com/assets/8420103/13853430/467c0010-ec2c-11e5-8617-a052db84e2c8.png">
