### ISSUE TITLE
Phenolyzer autocomplete menu

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#278]
If I'm typing a term, the menu of autocomplete options appears and this obscures the 'Run' button. If the term I want is not in the box, I have to click somewhere else on the screen, to get the autocomplete options to go away, so that I can get to 'Run'. Maybe we should put the 'Run' button where it doesn't get obscured, or have an 'x' in the drop down to kill it.

**Comment by tonydisera** [comment]
This should be fixed now that we have switched over to the selectize.js dropdown library.  Now, the enter button will make the list disappear.
