### ISSUE TITLE
Clearing genes can leave a gap between cards

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#279]
Open the demo exome dataset and let the data load. We should be sat in the RAI1 gene, so manually remove the other gene badges, so that RAI1 is the only remaining badge. On removal of the last gene, the row of badges disappears since there are no longer multiple genes, making the top card vertically smaller. The other cards don't move up to fill the space though and a gray hole is left behind.

**Comment by tonydisera** [comment]
Fixed many moons ago.
