### ISSUE TITLE
Support multiple gene sets from Phenolyzer/Bookmarks

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#282]
When Phenolyzer is run for different phenotypes, we need a way to distinguish between the genes selected for each run/phenotype.  Also, we need a way to identify bookmarked 'sets'.  

It would be nice to have a way to union or intersect these gene sets, perhaps with a series of checkboxes or a multi-select dropdown from the main navigation area (or perhaps a side panel).

This feature needs a UI design session.

See related issues #204 for more information.

**Comment by AlistairNWard** [comment]
This should be pushed to the gene list generation app.
