### ISSUE TITLE
Bookmarked variant doesn't show highest impact transcript

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#285]
Go to:

**Comment by AlistairNWard** [comment]
No idea why that posted. Go to:

http://gene.iobio.io/?rel0=proband&rel1=mother&rel2=father&name0=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.bam&name1=&vcf1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12892.bam&name2=&vcf2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12891.bam&sample0=NA12878&sample1=NA12891&sample2=NA12892&genes=RAI1,AIRE,PDGFB,MYLK2,PDHA1&gene=PDGFB

Change transcript to one ending in 551.4. A deletion is now a high impact. Bookmark and open the bookmarks panel. The symbol for the deletion in the bookmark is not high impact.

![screen shot 2016-03-22 at 9 46 44 am](https://cloud.githubusercontent.com/assets/523111/13953586/0ef65506-f013-11e5-8db9-6ce931a2efdc.png)

**Comment by tonydisera** [comment]
Thank you for your great testing! I will look into this.

**Comment by tonydisera** [comment]
Weird.  This works for me.  I tried bookmarking the variant both before and after I changed transcripts.  It shows the harmful symbol as expected.

<img width="1402" alt="screenshot 2016-06-16 12 04 29" src="https://cloud.githubusercontent.com/assets/8420103/16127645/9921b8c0-33ba-11e6-89c6-156fa3818323.png">

**Comment by tonydisera** [comment]
Aha.  So if I change the transcript back to the canonical, the bookmarked variant symbol does change back to yellow.  I guess what we really need to do is register the transcript at the time of the bookmark.  Then when the bookmark is selected, the transcript should change.  Perhaps the bookmark shows the transcript ID is the case where the non-default transcript was selected when the variant was bookmarked.  Does that make sense, Al?

**Comment by AlistairNWard** [comment]
Perhaps we should have a team discussion on this. The reason I bookmarked the variant is because it shows as high impact in the gene badge. I changed to the indicated transcript, it becomes high impact and I bookmark. I'm thinking that the bookmark should be fixed for the selected transcript when the variant was bookmarked. But you're right, I may have multiple variants in a gene that I bookmark from different transcripts getting the max impact for both. So maybe the bookmark should indicate the associated transcript and highlight somehow when this isn't the canonical. If I select a bookmarked variant, we should probably change to the associated transcript, otherwise I could select a high impact and see it in the card as something else. Make sense?

**Comment by tonydisera** [comment]
Yes, I agree.  I think this is how we should fix it.

**Comment by tonydisera** [comment]
I like Chase's and Al's suggestion.  The idea was to highlight this variant in the ranked variants table.  How about this?  In the ranked variants table, show the highest impact, clinvar, snpeff, and polyphen.  Either highlight or add a row to the table to indicate that this is from the non canonocial (or non-selected) transcript.  The variant card will continue to show the color of the impact based on the currently selected transcript.  In the tooltip have a link to switch to this transcript.
