### ISSUE TITLE
Displayed variant count should equal filtered (loaded) vcf count + called variant count.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#290]

**Comment by tonydisera** [comment]
This isn't really the correct issue.  Displayed variant count represents the number of (loaded) variants that have passed filtering.   The called variant count are those 'missing' or 'new' variants called.  For now, I have added some space between 'Displayed' and 'Called' to make it clear that 'Loaded' and 'Displayed' go together.

**Comment by AlistairNWard** [comment]
What do you think about putting a very light box around the grouped categories? So Variants Loaded / Displayed would be together in one box. Variants called would be in a second. I'm thinking to future dev where we can then modify the parameter/filtering on called variants and then may have another category to deal with calling on suggested variants.

**Comment by AlistairNWard** [comment]
I'm going to leave this open. My last comment is an open question.

**Comment by tonydisera** [comment]
Oh right!  I'm going to move it back to in progress.

**Comment by tonydisera** [comment]
Wow, I found a few bugs with the variant counts.  These are now fixed.  I tried adding a box around Variants loaded xx Displayed xx, but it looked out of place.  So instead, I added a displayed count to Called variants, as you suggested.  Now the counts make sense.  What do you think?

**Comment by AlistairNWard** [comment]
Yes, this looks good to me. All I was looking for was to see that things clustered, so if we add new categories, it's clear what belongs with what. This works for me.
