### ISSUE TITLE
Mislabeled gene badge

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#293]
Go to:

http://gene.iobio.io/?rel0=proband&rel1=mother&rel2=father&name0=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.bam&name1=&vcf1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12892.bam&name2=&vcf2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12891.bam&sample0=NA12878&sample1=NA12891&sample2=NA12892&genes=BRCA1,BRCA2,TP53,STK11,MLH1,MSH2,MSH6,PMS2,APC,MUTYH,VHL,MEN1,RET,PTEN,RB1,SDHD,SDHAF2,SDHC,SDHB,TSC1,TSC2,WT1,NF2,COL3A1,FBN1,TGFBR1,TGFBR2,SMAD3,ACTA2,MYLK,MYH11,MYBPC3,MYH7,TNNT2,TNNI3,TPM1,MYL3,ACTC1,PRKAG2,GLA,MYL2,LMNA,RYR2,PKP2,DSP,DSC2,TMEM43,DSG2,KCNQ1,KCNH2,SCN5A,LDLR,APOB,PCSK9,RYR1,CACNA1S&gene=APOB

then go to the APOB gene. The badge indicates an orange Polyphen glyph, but when in the gene, the glyph is red in the rank variants table. I saw this after analyze all, in case that effects things.

**Comment by tonydisera** [comment]
I suspect this bug is in the code that parses the vcf record.  It grabs the SIFT and PolyPhen score(s) to determine the most pathogenic entry.  But perhaps the scores are the inverse (highest means lowest pathogenicity?).  I'll look into this.

**Comment by tonydisera** [comment]
Fixed.   The PolyPhen score lowest to highest (damaging).  
<img width="1402" alt="screenshot 2016-06-16 12 04 29" src="https://cloud.githubusercontent.com/assets/8420103/16133730/a8ed2188-33d6-11e6-91aa-15ac4ce76884.png">
