### ISSUE TITLE
Reduce number of genes in Phenolyzer list

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#297]
Run Phenolyzer and the top 10 genes are given badges. Reduce this to 5 and the genes no longer included are just removed from the ordering, but still have badges. We should physically remove the gene badges for the removed genes.

**Comment by tonydisera** [comment]
I found two more bugs related to Phenolyzer selection. 

1.  Run phenolyzer and the top 10 genes are selected.  Now de-select one of the top 10 genes.  The blue highlight around the gene goes away.

2. Also, when I was just selected genes in the phenolyzer list, they weren't being added as gene buttons.

**Comment by AlistairNWard** [comment]
Everything seems to be working as expected.
