### ISSUE TITLE
Select sample drop down behind affected sibs

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#302]
Select variants for the last sample in the data entry modal. The 'Choose a sample' drop down is behind the 'Affected siblings' box, so not all samples can be selected.

**Comment by AlistairNWard** [comment]
<img width="303" alt="screen shot 2016-06-05 at 1 38 04 pm" src="https://cloud.githubusercontent.com/assets/523111/15807117/c501c70a-2b22-11e6-84aa-c81dcf20080d.png">

**Comment by tonydisera** [comment]
This has been fixed now that we are using the selectize.js dropdown library.
<img width="590" alt="screenshot 2016-06-07 13 49 55" src="https://cloud.githubusercontent.com/assets/8420103/15872485/f337b892-2cb6-11e6-8dd0-4f39d8f36725.png">
