### ISSUE TITLE
HGVSc term is incorrect

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#304]
For NHMU example, mutated NFKB2 gene includes the variant c.2557C>T. gene.iobio shows this as a C/T SNP, but the HGSVc value is G>T.
![screen shot 2016-04-27 at 8 14 30 am](https://cloud.githubusercontent.com/assets/523111/14851782/26c5be66-0c50-11e6-9534-6bc36912d59e.png)

**Comment by tonydisera** [comment]
Interesting.  I wrote up an issue on this last week, but can't seem to reproduce.  I moved my issue over to 'Needs test' column.  I will reference this issue.
