### ISSUE TITLE
Check exome data

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#306]
CD19 is not in any of the exome data. Need to look at recalling and updating the data set.

**Comment by AlistairNWard** [comment]
Hey Tony, I've recalled the exome in CD19 and moved the new vcf to AWS, but I'm going to start weening gene onto the new directory structure so we can start cleaning it up.  I only saw (and changed on the exhibit branch, so you might need to do a git pull) reference to the exome trio in:

help_resources.html
app/card/dataCard.js

I copied the NA19238, NA19239 and the NA19240 bam files as well, so the current links still work, but will also work once we move over. Are there are any other references that you know of? When this branch is merged back into gh-pages, we can delete the old exome trio data.

**Comment by tonydisera** [comment]
Yep. Those are the 2 files that reference vcf and bam URLs in gene.iobio.

**Comment by AlistairNWard** [comment]
I just pushed exome changes to exhibit.

**Comment by tonydisera** [comment]
Awesome.  Thanks Al!  This is a thankless job trying to make order our of our garbage dump on S3!

**Comment by AlistairNWard** [comment]
Not a problem. It will all be worth it in the end!
