### ISSUE TITLE
Inform user if there bam or vcf files or urls are not found or cannot be accessed.

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#310]
We should also consider checking for the existence of files from the URL. We are often going to be distributing URLs and not directly inputting data into gene. As was the case with the expired links from GNomEx, we only found the problem after exhaustive searching. When the URL is pasted, we should check that the files in the URL exist.

**Comment by tonydisera** [comment]
I have added code to validate both vcf and bam files and urls.  I will work on reporting errors for calling variants next.

**Comment by AlistairNWard** [comment]
We should also consider checking for the existence of files from the URL. We are often going to be distributing URLs and not directly inputting data into gene. As was the case with the expired links from GNomEx, we only found the problem after exhaustive searching. When the URL is pasted, we should check that the files in the URL exist.

**Comment by tonydisera** [comment]
Yes, this validation code is in place as well.

**Comment by tonydisera** [comment]
I'm going to revise this issue for validating file and URLs.  I'll create another issue for capturing errors on calling variants, annotating variants since this is a trickier issue to solve.

**Comment by AlistairNWard** [comment]
First up, apology for 'there' in the title, when clearly it should be 'their'! This works.

**Comment by tonydisera** [comment]
I didn't notice!
