### ISSUE TITLE
Ensure that high impact intron variants aren't filtered out

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#311]
In large genes, we filter out intronic variants so that the gene isn't overwhelmed. We want to be sure that we don't remove important variants though. Below, the badge for RYR2 shows a red Polyphen probably damaging variant (mouse over doesn't indicate it's in another transcript), but there is no probably_damaging variant in the Rank Variants table. Was this removed as it is intronic?

http://gene.iobio.io/?rel0=proband&rel1=mother&rel2=father&name0=&bam0=https://s3.amazonaws.com/iobio/platinum/spikein/jan2016/Sample12.bam&vcf0=https://s3.amazonaws.com/iobio/platinum/spikein/jan2016/Sample12_combined_filtered_normalized.vcf.gz&affectedSibs=&unaffectedSibs=&gene=RYR2&genes=RYR2

![screen shot 2016-06-06 at 9 52 31 am](https://cloud.githubusercontent.com/assets/523111/15828410/6c8f5a9c-2bcc-11e6-87d4-25f5dc88f82e.png)

**Comment by tonydisera** [comment]
The missense/splice region variant was being filtered out because the filter field was set to '.' and the 'PASS' filter was automatically turned on.

There is now an Exonic Only checkbox to toggle the intronic filter.

**Comment by tonydisera** [comment]
I'm  closing this issue since it is described in #286.
