### ISSUE TITLE
Zooming into region problematic

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#312]
For gene RYR2, I was trying to zoom into see a splice region variant in context to the surrounding exons, but couldn't do it.  
The variant has the filter field of '.', so I had to turn off the filter to only show PASS filter variants.  But then when I tried to zoom in, the filter was turned back on.

See file: https://s3.amazonaws.com/iobio/platinum/spikein/jan2016/Sample12_combined_filtered_normalized.vcf.gz

Try zooming in to see the moderate impact variant showing missense & splice region consequences with filter = '.'.

**Comment by AlistairNWard** [comment]
Is the update here, the box that appears around the variant in the proband card? I have two comments:

1. Since the zoom selector is still a distance from the card, it is easier, but not easy. What do you think about putting a marked in the top gene model when a variant is selected (either from rank variants or the variant cards)? Then, when we select the variant, a marker appears where the variant exists and it would be super easy to zoom in exactly where we need.

2. In this case, the box in the variant card is not rescaled when zoomed in. In this example, there is a big stack of variants. When you zoom in, there is only a single variant and now the box extends a long way into gray space.

**Comment by AlistairNWard** [comment]
<img width="711" alt="screen shot 2016-07-12 at 7 30 19 pm" src="https://cloud.githubusercontent.com/assets/523111/16787059/57ec36b6-4867-11e6-9efb-f6a2c72be6df.png">

<img width="599" alt="screen shot 2016-07-12 at 7 30 13 pm" src="https://cloud.githubusercontent.com/assets/523111/16787061/5ce517aa-4867-11e6-9b21-bac653cfcc83.png">

**Comment by tonydisera** [comment]
I like your idea.  So when the user clicks on a gene, it would show a mark (perhaps a vertical line?)  in the top gene model to indicate the variant's position.

In regards to #2, are you talking about the rectangle that is supposed to represent the selection?  I agree with you that the rectangle should redraw to be around the selected variant.

**Comment by tonydisera** [comment]
The other idea I was thinking about was just a 'zoom to variant' link on the tooltip.  But your idea offers the user more control over the region selected and fits better with our overall functionality.

**Comment by tonydisera** [comment]
Or we could just extend the rectangle up the the gene model.  Like this:
<img width="425" alt="screenshot 2016-07-12 20 17 34" src="https://cloud.githubusercontent.com/assets/8420103/16789804/c0f3f31e-486d-11e6-80b0-c0db8e470c92.png">

**Comment by tonydisera** [comment]
Scratch that idea.  It wouldn't make sense once we zoomed in b/c the top gene model will be in a different coordinate space than the variant card gene model.  A separate rectangle or line is a better approach.

**Comment by tonydisera** [comment]
Now the gene model has a rectangle that tracks with the position of the moused over/selected variant.  Would you mind giving it a try and letting me know what you think?

I'm still working on the bug where the rectangle is not repositioned after zoom.

**Comment by AlistairNWard** [comment]
How about a little pointer in the top model?
![gene iobio](https://cloud.githubusercontent.com/assets/523111/16814165/986e13a8-4902-11e6-83ef-e558630b2587.png)

**Comment by AlistairNWard** [comment]
Then we could ditch the boxes entirely.

**Comment by tonydisera** [comment]
I like the pointer.  So get rid of the rectangle that spans the variant cards as well?

**Comment by AlistairNWard** [comment]
Might as well.


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by tonydisera** [comment]
I just pushed some improvements based on your excellent suggestions.  Give it a whirl.
:-)

**Comment by tonydisera** [comment]
Actually, wait for one more check-in.  :-)  I just remembered that I have to make one more fix so that the mother and father variant circles/x's position correctly before and after zoom.

**Comment by AlistairNWard** [comment]
I like it!

**Comment by tonydisera** [comment]
Awesome.  It was a good suggestion.  Much cleaner interface. :-)  Oh, and it should be working now.  Looks like I didn't need to push any fixes after all.
