### ISSUE TITLE
Phenolyzer gene list isn't cleared when a new phenotype is entered

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#315]
I changed the phenotype and the new list is tacked onto the bottom. Note how the score jumps back to 1 at position 301.

![screen shot 2016-06-08 at 6 08 00 pm](https://cloud.githubusercontent.com/assets/523111/15915138/fa230240-2da3-11e6-941b-b14597a69453.png)

**Comment by tonydisera** [comment]
Wow.  I'm not able to reproduce this.  Can you think of anything unusual you did (It's your fault) that caused this to happen?

**Comment by AlistairNWard** [comment]
Now I can't reproduce it either. I'll try to figure out what was different and work with it, but it definitely did mess up before!!

**Comment by AlistairNWard** [comment]
Can't reproduce, so this is closed unless we see it come back.
