### ISSUE TITLE
Cilnvar benign symbol not shown in rank variants

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#316]

**Comment by AlistairNWard** [comment]
Gene WFS1

https://s3.amazonaws.com/iobio/platinum/spikein/jan2016/Sample12_combined_filtered_normalized.vcf.gz
https://s3.amazonaws.com/iobio/platinum/spikein/jan2016/Sample12.bam

![screen shot 2016-06-08 at 6 17 10 pm](https://cloud.githubusercontent.com/assets/523111/15915498/e8584ee6-2da6-11e6-98a1-780264b14085.png)

**Comment by tonydisera** [comment]
This was on purpose.  To make the causative glyphs stand-out, the code excludes showing symbols for benign.  But I see your point.  Looking at this data, the app doesn't follow the same convention for SIFT and PolyPhen, nor AF.  I'll change the code.

**Comment by tonydisera** [comment]
Fixed.  It turns out that there were multiple clinvar entries ('none', and 'benign') and the ordering caused the none entry to be considered rather than the benign entry.
