### ISSUE TITLE
MYLK2 tutorial case (Auto-filtering of non-PASS on called variants)

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#317]
Run Freebayes as instructed in the tutorial. A new variant is discovered, but does not get into the rank variants table.

http://gene.iobio.io/?rel0=proband&rel1=mother&rel2=father&name0=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.bam&name1=&vcf1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12892.bam&name2=&vcf2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12891.bam&sample0=NA12878&sample1=NA12891&sample2=NA12892&genes=RAI1,AIRE,PDGFB,MYLK2,PDHA1&gene=MYLK2

![screen shot 2016-06-08 at 6 30 37 pm](https://cloud.githubusercontent.com/assets/523111/15915526/1907567c-2da7-11e6-8df7-050f49cdf3af.png)

**Comment by tonydisera** [comment]
Aha.  It is the darned auto-filtering on non-PASS variants again.  Weird.  When I toggle the PASS filter, the variant shows up.  We need to re-think the automatic filter on PASS....  If you have time, Let's try to talk this over today.

**Comment by tonydisera** [comment]
See #286

**Comment by AlistairNWard** [comment]
Yup. Problem solved.

**Comment by AlistairNWard** [comment]
Actually I had a couple of questions and observations. Shocker!!

1. After variants are called, the new variant is discovered and marked as a low quality variant and is greyed out in the table. How do we decide this is low quality? If you go to Data and clear all the variant files, calling is done automatically and now all variants are called, and none of them are grey. I'm guessing that this is because when we call, the filter is ".". So if there are no variants already, everything is '.', so nothing is greyed out. But if PASS variants are loaded, the '.' is now grey.

The reason I bring this up is that if a loaded file has PASS set and we call a variant, it is always going to appear as low quality, even if this is not the case. Maybe there was an error in the original file and the variant was deleted. So... I would suggest that after calling, we pipe through something like vt (vt filter -f "" -t "IOBIO" -d "Variants called by gene.iobio"). Then the resulting vcf will have the filter tag 'IOBIO' for all called variants. So, if we are showing all filter tags, we see it, but we're not making a claim that it's low quality.

Also, '.' doesn't mean low quality, so maybe the message should read as potentially low quality?

2. Tooltip has analyzing for Mum and Dad for the called variant when vcfs are loaded. When no vcfs are loaded, Mum and Dad allele counts are blank. Is Freebayes giving a no call here? Seems unlikely since there is good coverage.

**Comment by AlistairNWard** [comment]
![screen shot 2016-08-04 at 10 31 33 am](https://cloud.githubusercontent.com/assets/523111/17405788/edeea256-5a2e-11e6-90ba-cf65035cc810.png)
![screen shot 2016-08-04 at 10 32 33 am](https://cloud.githubusercontent.com/assets/523111/17405791/ef2947de-5a2e-11e6-813f-6933b2631b82.png)

**Comment by tonydisera** [comment]
Excellent comments and suggestions.

**Comment by AlistairNWard** [comment]
Blank AC records are, I am sure, because we are calling separately and so we are getting no variant for those cases. This part will be handled by #385, e.g. joint calling variants. The vt commands for filtering are in there too.

**Comment by tonydisera** [comment]
Question 1 -  Should we keep to filter of called variants to only show those with quality > 0?

Question 2 - Is there a better label to use rather than 'potentially low quality'?  I couldn't come up with one that was succinct.  How about something like 'VARIANT DID NOT PASS CALLING FILTER'?

**Comment by AlistairNWard** [comment]
1. We could put in a QUAL != 0 filter. I think that would be totally reasonable.

2. This is difficult since the filter value of '.' doesn't mean anything specifically. For example, if you annotated the vcf to mark all bad variants, you'd have all bad variants marked as 'FAIL' and '.' would mean high quality variant. All '.' means is that whatever filters were applied to the file, this particular variant didn't meet the criteria (and those could be positive or negative criteria). I think your suggest is pretty good, but I would prefer to steer clear of the term PASS in there. Maybe 'DID NOT MEET FILTERING CRITERIA'? When we change to joint calling (#385), I added a vt filter line to tag all variants called with the 'IOBIO' filter value, so it doesn't get muddied in the world of the '.' filter tag!

**Comment by tonydisera** [comment]
Yes, this is a better label.   Too clarify that this is not gene.iobio filtering, how about this?
FLAGGED FOR NOT MEETING FILTERING CRITERIA
or
DID NOT MEET CALLER'S FILTERING CRITERIA
or
DID NOT METT PIPELINE FILTERING CRITERIA

**Comment by AlistairNWard** [comment]
I prefer 'FLAGGED FOR NOT MEETING FILTERING CRITERIA'.
