### ISSUE TITLE
Call variants automatically when only bams are loaded

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#323]

**Comment by AlistairNWard** [comment]
In this use case, we should ensure that clicking 'Analyze all' triggers calling variants in each gene as well.

**Comment by tonydisera** [comment]
Good thinking.

**Comment by AlistairNWard** [comment]
Calling Freebayes automatically is successfully triggered, but I'm seeing problems with the returned results, including the allele counts in mouseovers etc. I'm not sure if this is related to some of the server problems Chewy and Chase are messing with, but this can't yet be closed. Some of the errors:

genesCard.js:821 Uncaught (in promise) problem getting gene info from ncbi. No data returned from eutils request http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=gene&query_ke…30.14.18.34_9001_1470226355_1619682984_0MetA0_S_MegaStore_F_1&usehistory=y

vcf.iobio.js:1593 error while annotating vcf records vep Error: stderr - UNIVERSAL->import is deprecated and will be removed in a future perl at /home/ubuntu/ensembl/BioPerl-1.6.1/Bio/Tree/TreeFunctionsI.pm line 94.

**Comment by AlistairNWard** [comment]
![screen shot 2016-08-03 at 8 53 16 am](https://cloud.githubusercontent.com/assets/523111/17366162/ca3c367a-5957-11e6-9ea3-2d9e9e029bf7.png)

**Comment by AlistairNWard** [comment]
In screenshot above (demo data, vcf files cleared, AIRE gene), variants called = 10 for proband, but none are shown. Hovering over mother, father and proband are shown as analyzing.

**Comment by tonydisera** [comment]
Looking at this now.

**Comment by tonydisera** [comment]
It looks like last night's 'site specific gene source' commit is causing the problem.  For now, comment out this line in globalsDeployment.js:

`//var siteGeneSource    = "refseq";       // what should the gene source default to: refseq or gencode?
`

**Comment by AlistairNWard** [comment]
I'm going to move this one back to in progress. 

1. I just reran and I'm now seeing variants for the proband, but the numbers don't add up! 12 called, but only 5 shown. 

2. Mouse over on the proband doesn't bring up a tooltip.

3. Still seeing a blank AC for some people in the tooltip when hovering over mothers variants. There is a lot of coverage, so if this is a no call, I'm concerned. I'll run this on the command line to investigate, but if we have ~40x coverage, we want to be able to confirm no variant and should have sufficient data to do so.

**Comment by AlistairNWard** [comment]
I just reran everything and the first two went away. Now I'm seeing 21 calls for the proband and that stacks up with the number of variants. Seeing the tooltips as well now.

Working on 3 though. I've manually called (I added on slack a request for the exact way that we call) and where I'm seeing a blank AC, there is a homozygous reference call. Once I confirm that we are calling in the same way, this looks like it isn't a no call issue, but a failure to display the reference call.

**Comment by tonydisera** [comment]
Does Freebayes show genotypes for homozygous reference?

**Comment by AlistairNWard** [comment]
The issue will be addressed by #385. The vcf file only contains records for positions that have a variant. So if you only call the individual, and they are hom ref, no, you will not generate a call and so you have no data. If you joint call, then there is a variant in one of the samples, so they have a 0/1 or 1/1 genotype. In this case, since the calls for all samples are provided, you will have a 0/0 for the hom ref samples. Make sense? So we really need joint calling to resolve this.

**Comment by tonydisera** [comment]
Got it.  I'm going to mark this as fixed since the other issues should be addressed.  Then we can tackle #385 joint called ASAP after release.
