### ISSUE TITLE
The allele count bars don't show correctly for called variants.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#325]
I only loaded the alignment files, then called the variants.  Now when clicking on the variant, the allele counts don't show correctly.
<img width="375" alt="screenshot 2016-06-19 12 55 13" src="https://cloud.githubusercontent.com/assets/8420103/16179270/8b8f578e-361d-11e6-88e6-06f7513ac0c7.png">

**Comment by tonydisera** [comment]
This turned out to be a bit tricky.  Basically, the logic is a bit different when only alignments are loaded in that we are not merging the loading and called variants.  This resulted in a bug where the maxAlleleCount was not getting calculated for the called variants (on the second pass, after the called variants were cached.)  I also fixed another bug where the feature matrix wasn't loading when a full trio of called variants was displayed (after click on the gene button once variants were called.)  So in general for testing, try calling the variants and then going back and forth to different genes by clicking on the gene buttons.

**Comment by AlistairNWard** [comment]
This seems fixed and is superseded by #329.
