### ISSUE TITLE
Blank variant chart (alignments only) - Call variants and click gene button before variant chart has finished refreshing

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#327]
There seems to be a period of time between when variants are called and the variant chart is displayed where the called variants are cleared from the cache.  Load a bam file only.  Call variants and as the variants are displaying, click on the gene button.  Now the variant chart is blank.

**Comment by AlistairNWard** [comment]
I can't replicate this, so am closing.
