### ISSUE TITLE
Seeing some inconsistent results when pulling from GNomEx

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#331]
Running multiple times on one gene is generating different results. From GNomEx, so I'm not listing study or links, so this is more difficult to track and reproduce. No variants loaded for Father (variants do exist) and while variants are loaded for the proband, the card tells me 0 were loaded.

<img width="1397" alt="screen shot 2016-06-21 at 1 58 16 pm" src="https://cloud.githubusercontent.com/assets/523111/16240701/6a8a6ac8-37b8-11e6-9cbe-f47e3939ce5a.png">

Here is a rerun:

<img width="1400" alt="screen shot 2016-06-21 at 1 59 05 pm" src="https://cloud.githubusercontent.com/assets/523111/16240741/88f3ef84-37b8-11e6-8b36-40ba3f5b0d77.png">

**Comment by AlistairNWard** [comment]
Here is looking at the RAI1 gene.

<img width="1400" alt="screen shot 2016-06-21 at 5 35 10 pm" src="https://cloud.githubusercontent.com/assets/523111/16247186/a4eab2e0-37d6-11e6-9b09-c41f101af7b4.png">

Proband shows zero variants loaded, although there are clearly variants displayed. They look exactly the same as for the Father.

**Comment by AlistairNWard** [comment]
This is primarily on the dev branch.

**Comment by tonydisera** [comment]
This should be working on devkit now.

**Comment by AlistairNWard** [comment]
Not see any reoccurrence of this problem, so closing it.
