### ISSUE TITLE
Ordering of allele counts should match the ordering of the cards

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#332]
Variant cards are ordered as proband, father then mother, but the allele counts in the tooltip are proband, mother then father. The order should be consistent. I looked at this and thought there was an error because the middle allele count is hom ref, but the middle variant card shows the variant.

<img width="345" alt="screen shot 2016-06-21 at 2 26 32 pm" src="https://cloud.githubusercontent.com/assets/523111/16241606/6d74c9e6-37bc-11e6-8b56-7fb7ab6e4f82.png">

**Comment by AlistairNWard** [comment]
In a continuing snub of my efforts, I note you just open a new issue for my issues, solve that and leave mine hanging. I assume that this is some kind of message to me - not pleased with my incessant issue raising!!!

Looks like #356 was created and is an exact duplicate of this, so I'm closing this one.

**Comment by tonydisera** [comment]
You omit the most obvious cause -- your colleague failed to review the issues before adding a new one. Shame on me!

**Comment by AlistairNWard** [comment]
I considered that, but considered more likely you were making a point!!!
