### ISSUE TITLE
Check entered gene names

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#333]
I copied an ARUP gene panel list and pasted into gene.iobio. Some of the gene names have alternatives, so I pasted, for example, XIAP/BIRC4. gene.iobio allows this, but it hangs when trying to process it. XIAP exists in the gene list, but BIRC4 does not. When a list of genes is entered, we should process the list and give warnings errors before loading into gene.

**Comment by AlistairNWard** [comment]
We need to ensure we check the list of genes supplied in the URL, not just from manual import. If we share a URL with a bad gene name, it needs to be caught.

**Comment by tonydisera** [comment]
Duplicate #522
