### ISSUE TITLE
Not seeing allele count for father

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#341]
Go to:

/uufs/chpc.utah.edu/common/home/marth-d1/data/projects/A259_EIEE/eiee_genedx_urls.txt
and copy and paste the 4th URL (should be family 42610 - the family id appears after all the names). Go to gene SCN1A. Hover over the variants in the rank variants table. The first ~20 seem fine, but after the hom alt variants, the next few do not show counts for the father.

**Comment by AlistairNWard** [comment]
From Slack.

I think that there is a disconnect between data loading and when things (e.g. inheritance) are calculated

[11:29]  
I just watched a gene get analyzed and the proband data all got loaded in and the rank variants matrix was populated

[11:29]  
But the mother and father had yet to complete processing

[11:30]  
When they did complete, the rank variants table wasn’t updated

[11:30]  
If I then click on the gene again, with all data available a variant was then given the de novo badge in the table and in the gene badge

[11:30]  
I think this is happening a lot on the analyze all. I am running through Rufus variants and each gene badge just gets a tick mark

[11:31]  
When I physically click on the gene badge, the de novo glyph then gets added

**Comment by AlistairNWard** [comment]
I think that this is related to the allele count for the father. If the glyphs are missing etc, hovering over the variants only shows the proband. Click the gene again and then the glyphs appear and all three members of the trio are now visible in the mouse over.

**Comment by tonydisera** [comment]
Okay.  I fixed a number of bugs related to post variant processing on the exhibit branch.  Are you seeing this on the dev branch?

**Comment by AlistairNWard** [comment]
No, this is all on production. If you want, you can put this over to the validate and I can look on the dev branch and see?

**Comment by tonydisera** [comment]
That is okay.  Let me give this a go on the dev branch once I get the code stabilized after the devkit changes.

**Comment by tonydisera** [comment]
Hey Al.  What would you think about the allele counts showing 'processing...' in the tooltip while the trio is analyzed?

**Comment by AlistairNWard** [comment]
For it. I think it's always good to see that something's happening. So either data constantly filling in and updating, or something indicating processing is happening is always beneficial in my book.

**Comment by tonydisera** [comment]
Here is the change to tooltip. 

Before the full trio has been analyzed:
<img width="317" alt="screenshot 2016-07-26 20 33 05" src="https://cloud.githubusercontent.com/assets/8420103/17162125/5d9f8e6e-5370-11e6-9fcb-4b4bd2d8c93d.png">

After trio has been analyzed:
<img width="316" alt="screenshot 2016-07-26 20 33 13" src="https://cloud.githubusercontent.com/assets/8420103/17162128/6b28bc40-5370-11e6-8266-6e41e7279750.png">

**Comment by AlistairNWard** [comment]
+1

**Comment by tonydisera** [comment]
There is still a problem with the missing allele counts when hovering over or clicking on a variant from the variant cards.  The app needs to refresh the variant charts after inheritance is determined as well as coverage is returned.  I'm working on a fix right now.

**Comment by AlistairNWard** [comment]
Ok, I'm not 100% sure that I should be putting this in this issue, or if there is a more relevant one, but here goes. I'm looking at data from A204 (John Carey) and am seeing a couple of problems (can't share the link, but I've seen this before). I mentioned on Slack yesterday, so maybe they can be reproduced in the demo dataset. I'll try after lunch.

1. Mother and proband appear to share the same set of variants.

2. Mouseover for some variants have 'analyzing...' that never goes away. Hovering over different proband variants sometimes shows different combinations, e.g. just Mum analyzing, or both Mum and Dad.

3. If I hover over mothers variant, I see (sometimes) AC for all three samples, but no coverage is shown in the proband coverage track.

4. Click on a de novo (from the ranking table) and the variant is not present in the proband, since we seem to be showing the mothers variants for the proband.

**Comment by AlistairNWard** [comment]
![screen shot 2016-07-27 at 11 43 59 am](https://cloud.githubusercontent.com/assets/523111/17182107/6cda0604-53f0-11e6-8303-a62d76cf1b1e.png)
![screen shot 2016-07-27 at 11 47 12 am](https://cloud.githubusercontent.com/assets/523111/17182110/6f5392f6-53f0-11e6-8e96-21a68dcacb92.png)
![screen shot 2016-07-27 at 11 49 38 am](https://cloud.githubusercontent.com/assets/523111/17182118/72b69d26-53f0-11e6-9070-175a3996f69f.png)

**Comment by tonydisera** [comment]
Yes, I'm glad you entered this as a separate issue.  I noticed this last night and started digging into the code to fix it.  Good timing!

**Comment by AlistairNWard** [comment]
I haven't seen the reoccur, so I'm going to close.
