### ISSUE TITLE
When local storage exceeded, check for error message

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#343]
Look at line 1074 of VariantModel:

    	if (success) {
	    	try {
		      	localStorage.setItem(this._getCacheKey(dataKind, geneName, transcript), dataStringCompressed);
	    	} catch(e) {
				if (e == QUOTA_EXCEEDED_ERR) {
	    			// TODO - keep track of times that gen

The variable QUOTA_EXCEEDED_ERR is not defined.

**Comment by AlistairNWard** [comment]
To fix, localStorage.clear()

**Comment by tonydisera** [comment]
Here is the message when the local storage size is exceeded:
uotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of

**Comment by tonydisera** [comment]
I've been working on a remedial feature to address the issue of the local storage exceeding the browser limit.  A new link called 'Clear cache...' has been added after the gene buttons.  This will bring up a dialog that allows the cache to be cleared.  Cached bam data can be cleared, data for genes without significant impact variants (genes without badges) can be cleared, or all cache can be cleared.

**Comment by tonydisera** [comment]
<img width="505" alt="screenshot 2016-06-30 20 50 59" src="https://cloud.githubusercontent.com/assets/8420103/16510551/54bf7906-3f04-11e6-9d9c-59bca9133f7d.png">
<img width="581" alt="screenshot 2016-06-30 20 51 10" src="https://cloud.githubusercontent.com/assets/8420103/16510555/59bfa1e2-3f04-11e6-96fc-a9c2e137cc20.png">

**Comment by AlistairNWard** [comment]
Will the user be prompted to do this if the cache is full?

**Comment by tonydisera** [comment]
Yes.  The user will see this warning:

Error XXXX occurred when caching analyzed data for gene BRCA2. Click on 'Clear cache...' to clear cache."

**Comment by AlistairNWard** [comment]
I actually just went in and looked at the code before I closed the issue
and saw that the 'TODO' had been replaced with a real condition!! That was
what convinced me to close it!


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC
