### ISSUE TITLE
Hanging while analysing a gene

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#344]
Ran Analyze All on a trio from A259 family after replacing the proband with the Rufus VCF. Analysis proceeds ok and then hangs on a gene (it did this a few times). I see the error:

matrixCard.js:336 Uncaught TypeError: Cannot read property 'forEach' of undefined

while hung. If I click on a previously analyzed gene, we move to that gene and the hung gene now goes back to blank. If I click on the hung gene again, the data loads fine. Click Analyze all and analysis continues.

**Comment by tonydisera** [comment]
Ok.  Thanks for your testing.  Sorry about all of these bugs!!!

**Comment by AlistairNWard** [comment]
No apologies required. This project has become huge and we haven't been able to test as much as we should. Getting an analyst will certainly help!

**Comment by tonydisera** [comment]
Do you remember which proband you were analyzing?

**Comment by AlistairNWard** [comment]
Go to GNomEx and open the demo_urls.txt file and then take the final URL. This uses Rufus calls for the proband and hanging occurred a lot for me.

**Comment by AlistairNWard** [comment]
And if yours works the same way as mine, you'll note that each gene will be processed and furnished with only a check mark. They should all be de novo calls. Click on an analyzed gene and then it will put the de novo glyph in.

**Comment by AlistairNWard** [comment]
I just reran this myself and, obviously, it ran to completion this time! The above comment about the de novo glyphs still stands. I need to go back and click on the genes to see that glyph. I'm wondering if I just had so many tabs open that gene was being very slow giving the impression that it had hung?

This is a longer term idea, is it possible to have the gene slowly colour from left to right like a progress part instead of the spinning cube? That way you can see that progress is being made, and you would see that it hasn't hung. Not sure if that is straight forward or not.

**Comment by tonydisera** [comment]
I like the suggestion about making progress more visible.   
I will try to reproduce the hanging Analyze all problem with the Rufus calls.  Thanks!

**Comment by tonydisera** [comment]
I'm having problems getting 'Analyze all' to hang on Rufus calls.   So for now, I'll work on the  better highlighting the gene currently being analyzed and the missing glyph issue.

**Comment by AlistairNWard** [comment]
I'm still seeing hanging, but unfortunately it isn't always on the same gene. Some of these may be caused by running out of local storage (#343), so I have to manually clear it from time to time.

Also, my guess is that in analyze all, the glyphs are added and gene moves on to the next gene when the variants are loaded for the proband. In the case that the parents take longer to load (always the case in the Rufus calls, since the proband has a single variant), this means the gene is marked as completed and we move on every time before being able to determine the inheritance.

**Comment by tonydisera** [comment]
There have been a number of bug fixes, so hopefully this issue has been addressed.

**Comment by AlistairNWard** [comment]
I think this was a local storage issue, so should be fixed by #342.

**Comment by AlistairNWard** [comment]
Sorry #343.
