### ISSUE TITLE
If gene list is large, you can't scroll down to variant cards

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#346]
<img width="1434" alt="screenshot 2016-06-24 11 01 14" src="https://cloud.githubusercontent.com/assets/8420103/16344679/fa900e86-39fa-11e6-8177-063424b5aa8d.png">

**Comment by AlistairNWard** [comment]
I'm starting work on analyzing the CVID cases for Karl and this is a problem. I have subsetted to smaller sets for now.

As well as just being able to scroll, we may want to think about changing how and what we display. For example, we could have the option to set how many gene badges we want to see and change which ones we are viewing, e.g. page 1 is the first 20, page 2, the next 20 etc. We may also consider having a toggle to only show 'interesting' genes which we would define as something with some clinVar/impact or functional prediction. What do you think?

**Comment by tonydisera** [comment]
How about adding a vertical scrollbar for the short term?  I favor that over navigating through pages.  I also like the idea of filtering to only show interesting genes, but that is probably better addressed with your email discussion you started this weekend.

**Comment by AlistairNWard** [comment]
Yes, I agree. Scrollbar is better than pages. Not sure why I even suggested that.

And yes, the filtering is really part of the larger discussion, so we should not worry about that for this issue. A vertical scrollbar should close this one out.

**Comment by tonydisera** [comment]
Okay.  I've moved this issue over to 'Work in Progress'.  I'll tackle this one next.

**Comment by tonydisera** [comment]
[94ba7b4]

**Comment by tonydisera** [comment]
So the vertical scrollbar was confusing because there is already a vertical scrollbar for the variant card scrolling.  So instead, I implemented paging using the Bootstrap component.  Al, give it a try and let me know what you think.  Each page has 50 genes.

<img width="1177" alt="screenshot 2016-07-12 13 43 04" src="https://cloud.githubusercontent.com/assets/8420103/16781049/99507724-4836-11e6-97a2-ff69d1759906.png">

**Comment by AlistairNWard** [comment]
Yep - works! We should open this to Chase to see if he has any major reservations, but this is operational and so I'm closing the issue.

**Comment by AlistairNWard** [comment]
@chmille4: Comment?

**Comment by chmille4** [comment]
just talking with Al and I think a good solution would be to add a couple options on sorting and viewing to this box in the upper right hand above the genes. Like the image below.

<img width="381" alt="screen shot 2016-07-14 at 10 03 58 am" src="https://cloud.githubusercontent.com/assets/88370/16842230/ad91709c-49aa-11e6-97f2-f67d8ce51bed.png">

When selected _view 20_ the genes would be paginated, but when selected view all the genes would have a vertical scroll. This lets the users quickly look at all the genes and do cmd-f finds if needed.

Sort would sort via the variants across all the genes, but could also be expanded to sort via other criteria

**Comment by tonydisera** [comment]
yes, this is a great suggestion.

**Comment by AlistairNWard** [comment]
Additionally, if we do show multiple pages of genes, analyze all will stop at the end of the first page. We would want analyze all to analyze all genes, not just those on the current page. In the event of multiple pages, how would we indicate that analysis is still ongoing on genes that we can't see?

**Comment by AlistairNWard** [comment]
Also - I have multiple pages of genes and click Analyze all on page 1. When it finished, I  moved to page 2 and noted that analysis is not continuing. Go back to page 1 and all the glyphs have disappeared from the gene badges. I'm assuming analysis has been flagged as complete, since now analyze all has no function.

**Comment by tonydisera** [comment]
Oops.  I wouldn't have expected analysis to stop. I will look into this

**Comment by tonydisera** [comment]
You can now sort by gene name or relevance, view 50 at a time, or view all (vertical scroll).  The vertical scroll is awkward because it also scrolls the outer container as well.  

I've re-arranged all controls for analyzing, removing, paging, and sorting to a line above the gene buttons.

**Comment by tonydisera** [comment]
I just found a bug with the new feature.  The 'view all' doesn't work until a page is selected.

**Comment by AlistairNWard** [comment]
This is working well.
