### ISSUE TITLE
Coverage scale across samples (and large deletions)

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#351]
If a sample has a large deletion across a gene, it has ~half the coverage of the two parents in the gene. Since the coverage scales are scaled to the max in the sample, you can't see this difference. It would be great to include a view where we can see the coverage for all samples in a single view.

In a similar vein, if there is a large deletion, all of the calls in the proband should be homozygous in the deleted segment. We could add an user triggered operation that assesses the number of het and hom calls in all samples.

For example, in GNomEx study A259 (EIEE), go to the file eiee_genedx_urls.txt and copy and paste the sixth link (family 42609) and go to gene UBE3A. Hover over any SNP and you'll see the proband is hom alt and has ~half coverage.

**Comment by AlistairNWard** [comment]
![screen shot 2016-06-29 at 2 13 23 pm](https://cloud.githubusercontent.com/assets/523111/16463405/b363218a-3e03-11e6-8c3d-ed8dccc850f0.png)

**Comment by AlistairNWard** [comment]
As a first step, can we try just setting the scale for the coverage for each sample to be the max of all samples, so they're all on the same scale?

**Comment by tonydisera** [comment]
Hi Al.  I might need to have you explain this to me.  I'll look at the example you mentioned and see if I can understand this issue....

**Comment by tonydisera** [comment]
I see.  Let me give that a try on this data and send you a screen print to see if the coverage difference stands out.

**Comment by AlistairNWard** [comment]
Ok, whenever you're ready. I'm going to be out of the office pretty soon today, but we can Skype tomorrow if you want to talk this over.

**Comment by AlistairNWard** [comment]
Yes, this works. It isn't massively noticeable, but this may not be the place to focus on this. Hopefully multibam will help in the coverage comparison.
