### ISSUE TITLE
Zoom into region of a selected gene

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#360]
For gene RYR2, I was trying to zoom into see a splice region variant in context to the surrounding exons, but couldn't do it.  

This gene was large and had a lot of exons, so it was hard to zoom in to the correct region.  It would be nice to click on a selected variant and be able to automatically zoom in to that variant +- a few hundred variants.

See file: https://s3.amazonaws.com/iobio/platinum/spikein/jan2016/Sample12_combined_filtered_normalized.vcf.gz

Try zooming in to see the moderate impact variant showing missense & splice region consequences with filter = '.'.

**Comment by AlistairNWard** [comment]
This is the same as #312 in the 'ready to validate'. Was this supposed to be something else, or should this be removed?

**Comment by tonydisera** [comment]
I added this one since I didn't think that #312 adequately address the issue of zooming into see a particular variant.  However, with your suggestion of showing the rectangle to indicate the position of the moused-over/selected variant, this one can be closed. :-)
