### ISSUE TITLE
Polyphen badge not showing on gene

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#364]
Enter the wgs platinum vcf for the proband (https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz, NA12878) and type in gene BRCA1.  Notice that there is a variant with a  'probably damaging' polyphen classification in the feature matrix; however, the gene button does not show the polyphen badge. 

<img width="830" alt="screenshot 2016-07-20 14 32 21" src="https://cloud.githubusercontent.com/assets/8420103/17002091/0990d4d8-4e87-11e6-9361-ab08f5c20838.png">

**Comment by AlistairNWard** [comment]
Yup, this does appear to be fixed.
