### ISSUE TITLE
Can't call variants with new devkit/minion - bcftools error

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#366]

**Comment by tonydisera** [comment]
Error from console:

vcflib Error: vt Error: stderr - 
  undefined -- Required argument missing: <in.vcf>

normalize v0.5

description : normalizes variants in a VCF file

usage : vt normalize [options] <in.vcf>

options : -o  output VCF file [-]
          -d  debug [false]
          -q  do not print options and summary [false]
          -n  do not fail when REF is inconsistent with reference sequence for non SNPs [false]
          -w  window size for local sorting of variants [10000]
          -I  file containing list of intervals []
          -i  intervals []
          -r  reference sequence fasta file []
          -?  displays help
          

variantCard.js:1403 A problem occurred while calling variants.
bam.iobio.js:775 vcflib Error: prog process exited with code 1
bam.iobio.js:775 vcflib Error: vt Error: prog process exited with code 1
bam.iobio.js:775 vcflib Error: vt Error: stderr - 
  undefined -- Required argument missing: <in.vcf>

normalize v0.5

description : normalizes variants in a VCF file

usage : vt normalize [options] <in.vcf>

options :

**Comment by AlistairNWard** [comment]
What is the command line you are passing?

**Comment by tonydisera** [comment]
Fixed by adding '-' to the argments for vt.
