### ISSUE TITLE
Make parallel iobio commands during 'Analyze all' to speed up processing

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#369]

**Comment by tonydisera** [comment]
There is an experimental feature that I just added tonight.  There is a default "batch size" of 5 set for 'Analyze all', meaning that up to 5 genes will be analyzed simultaneously.  As a gene is analyzed for the samples, the batch will drop down.  After all genes in the batch are processed, another 5 genes are kicked off.  

Ideally, this would be changed to keep the batch size at a constant of 5 until all genes have been analyzed.   I'll work on that next.

For now, you can use the super secret argument 'batchSize' in the url to control how many genes are analyzed concurrently.  I've tried setting it to 10 and then 20, with less that stellar response.  So for now, feel free to play around with the batch size to see what is optimal. 

Right now, the last commit is set to nv-prod, using the old (pre-devkit) api to annotate the variants.  I hesitate to point to nv-dev with concurrent analysis since this is a single node.

**Comment by AlistairNWard** [comment]
Sweet! I'll play with this today.

**Comment by AlistairNWard** [comment]
This is in and works. Any problems down the road can be separate issues.
