### ISSUE TITLE
ExAC and 1000G AF not filled in on Freebayes variants

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#37]
Need to send through contig appender service first.  af.iobio expects all contigs on human genome to be present in order to index properly.  Send reference numbers 1-23, x, y, m on command line to cntgapndr.iobio.

**Comment by tonydisera** [comment]
Yi figured this out.  So the afserver needs contig header records for all of the references including the reference for the gene of interest since Yi is using indexing based on the contigs to determine the appropriate reference.  
Right now, bcftools on the iobio amazon instance is out-of-date and doesn't support the bcftools annotate command.  Once bcftools is updates, AFs for ExAC and 1000G should start showing up on the Freebayes called variants.

**Comment by AlistairNWard** [comment]
I don't believe that Freebayes outputs the contig header records. If these are necessary, are you pulling header information from another source or including the contig lines from somewhere else?

**Comment by tonydisera** [comment]
Fixed.
