### ISSUE TITLE
Sort genes by relevance is incorrect

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#373]
Some genes with lower impact are ordered before high impact genes.

**Comment by tonydisera** [comment]
http://localhost/gene.iobio/?rel0=proband&rel1=mother&rel2=father&rel=mother&name0=NA19240&vcf0=https://s3.amazonaws.com/iobio/samples/vcf/exome-trio.vcf.gz&bam0=https://s3.amazonaws.com/iobio/samples/bam/NA19240.bam&sample0=NA19240&name1=NA19238&vcf1=https://s3.amazonaws.com/iobio/samples/vcf/exome-trio.vcf.gz&bam1=https://s3.amazonaws.com/iobio/samples/bam/NA19238.bam&sample1=NA19238&name2=NA19239&vcf2=https://s3.amazonaws.com/iobio/samples/vcf/exome-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/samples/bam/NA19239.bam&sample2=NA19239&gene=KLK3&genes=RAI1,BRCA2,AR,BRCA1,CDH1,RAD51,CHEK2,TP53,ATM,BARD1,BRIP1,ESR1,AKT1,RAD51C,PALB2,FGFR2,PTEN,CASP3,MYC,CASP8,SMAD3,NBN,CDKN1A,KLK3,KRAS,MDM2,EP300,STK11,CCND1,MRE11A,PIK3CA,RAD50,CTNNB1,CREBBP,NFKB1,RAD51D,JUN,PHB,FANCD2,ETS1,MAPK1,XRCC3,MSH2,RB1,HDAC1,MLH1,ABL1,E2F1,SP1,ATR,EGFR,RAD54L,GSK3B,MDM4,CDK1,HMMR,SMAD4,FOXO1,IRS1,RELA,RAF1,RB1CC1,BCL2,PML,BLM,ZMIZ1,RAD51B,CDK2,TGFBR2,TWIST1,CDK6,STAT3,PIK3R1,KAT2B,E2F4,CDKN1B,FGFR3,PIAS1,FGFR1,MAPK14,GRB2,IGF1R,STAT1,TCF7L2,CALM1,PRKCA,MMP2,PDGFRA,PLK1,CDK4,AKT2,CREB1,CDC25B,PPM1D,CDKN2B,TSC2,HIF1A,NQO1,MAPK8,MTOR,PLCG2

**Comment by AlistairNWard** [comment]
I'm seeing expected behaviour.

**Comment by AlistairNWard** [comment]
I see some problems with the ordering. Running A359 CVID family (proband - 108591X1, mother 108591X3, Father 108591X2) on the following gene list:

AICDA,AKT1,BLNK,BTK,CD19,CD27,CD40,CD40LG,CD79A,CD79B,CD81,CD86,CR2,CTLA4,CXCL12,CXCR4,DCLRE1C,GATA2,ICOS,IGHM,IGLL1,IKBKB,IKBKG,IL17A,IL17F,IL21,IL21R,IRF4,LRRC8A,MLH1,MS4A1,NFKB1,NFKBIA,PDCD1,PIK3CD,PIK3R1,RAG1,RAG2,SH2D1A,STAT1,STAT3,TCF7L1,TFRC,TGFB1,TGFB2,TGFB3,TNFRSF13B,TNFRSF13C,TNFRSF4,TNFSF10,TNFSF13,TNFSF13B

Analyze all, reorder by relevance and I get some genes with nothing in them ranking higher than variants with e.g. de novos. See, for example CD40 followed by CD40LG.

![screen shot 2016-09-12 at 2 13 27 pm](https://cloud.githubusercontent.com/assets/523111/18447196/8ec00200-78f3-11e6-8fed-04f75258ac67.png)

**Comment by AlistairNWard** [comment]
This has been resolved by numerous updates to filtering.
