### ISSUE TITLE
Gene badge shows de novo inheritance but no variants show this inheritance.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#375]

**Comment by tonydisera** [comment]
<img width="542" alt="screenshot 2016-07-25 20 35 54" src="https://cloud.githubusercontent.com/assets/8420103/17124416/2be7137e-52a8-11e6-8073-025b2a72c494.png">

**Comment by tonydisera** [comment]
The auto filter for 'PASS' only strikes again.  So the badge is examining variants that have been filtered out (rec filter=.).

**Comment by AlistairNWard** [comment]
Ok, do you want to talk about this tomorrow? It seems that both of us have been caught out by this on a number of occasions. I'm thinking that we should maybe default to show everything. It is then at the users discretion to filter to PASS only.

**Comment by tonydisera** [comment]
Yes, I'm inclined to get rid of the auto-filtering as well.  That would be great to chat about this tomorrow.  We could 'flag' the non-passed variants in the matrix as well as the tooltip in such a way that it is highlights the variant as 'questionable'.

**Comment by AlistairNWard** [comment]
Yes, let's talk about it tomorrow. But I think flagging the variants as questionable in the table is a good idea. We could include in the mouseover/inspect variants panel, the filter value prominently as well.

**Comment by AlistairNWard** [comment]
Solved with addition of grey bars. #382 is dealing with this.
