### ISSUE TITLE
No bookmark glyph in rank variants table

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#378]
http://127.0.0.1:4000/?rel0=proband&rel1=mother&rel2=father&name0=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.bam&name1=&vcf1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12892.bam&name2=&vcf2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12891.bam&sample0=NA12878&sample1=NA12891&sample2=NA12892&genes=RAI1&gene=RAI1

Bookmark the pathogenic variant. The bookmark glyph does not appear in the rank variants table.

**Comment by AlistairNWard** [comment]
I've put this as high priority so that I can finish the blog post on bookmarks.

**Comment by tonydisera** [comment]
Sounds good.

**Comment by AlistairNWard** [comment]
Also, if you bookmark a variant, in the mouseover, there is a bookmark glyph randomly floating in the upper left. Should that be there?

**Comment by AlistairNWard** [comment]
...and, if I go to the bookmarks tab, click edit and delete a bookmark, the highlighting box around the variant in the proband card remains.

**Comment by AlistairNWard** [comment]
All three observations are resolved. The blog post on bookmarks will be ready to go when we push to production.
