### ISSUE TITLE
Get rid of auto filtering on non-pass variants; highlight variants in tooltip and feature matrix instead

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#382]

**Comment by AlistairNWard** [comment]
I like this. The only thing is that we don't have anywhere that explains what the grey bars in the rank variant table represent? I'm not sure exactly how to do this.

Another suggestion. I think that this is an update that would benefit from a blog post. I'll create an issue to do this, but in the future, if you think an update is worth a post, create an issue and assign me to it.

**Comment by tonydisera** [comment]
I added the label at the top of Ranked Variants to explain what the grey background means.

**Comment by AlistairNWard** [comment]
This is way better.
