### ISSUE TITLE
No variants and SIFT deleterious low confidence are very similar glyphs

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#383]

**Comment by AlistairNWard** [comment]
![screen shot 2016-08-03 at 1 24 30 pm](https://cloud.githubusercontent.com/assets/523111/17375125/be5d4080-597d-11e6-9deb-4dd066a7896e.png)

**Comment by tonydisera** [comment]
I would hardly call a 1px round on the triangle trivial.  ;0)

**Comment by AlistairNWard** [comment]
No longer an issue as the SIFT glyph no longer appears in the gene badge.
