### ISSUE TITLE
If site specific gene source set, still allow gene source dropdown to be changed.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#388]

**Comment by tonydisera** [comment]
To test:
http://localhost/gene.iobio/?rel0=proband&rel1=mother&rel2=father&genes=BRCA2,MTHFR,AC002429.5,BLACAT1&gene=BRCA2&name0=NA12878&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&affectedSibs=&unaffectedSibs=

In globalsDeployment.js, set siteGeneSource='refseq'

Select BRCA2 first, now switch to Gencode gene source in the dropdown.  Select MTHFR.  Now select BLACAT1 and notice how dropdown switches back to RefSeq.  Click on BRCA2 and notice how we switch back to Gencode.  Try similar test with AC002429.5, which is a Gencode only gene.

**Comment by AlistairNWard** [comment]
I have the siteGeneSource set, change to gencode from BRCA2 and then click on other genes. I stay on Gencode until I hit a refseq only gene.

**Comment by tonydisera** [comment]
This is intentionally coded this way.  My reasoning was that if a user changes the gene source dropdown, that that this was meant to be a change that lasts the entire session, excepting cases where a gene only belongs to the non-selected gene source.

**Comment by AlistairNWard** [comment]
You win! I kind of misread the instructions, and was expecting to change back to refseq, since that was the site specific source, but I think the current method of operation makes the most sense.
