### ISSUE TITLE
Reorder gene list can clear glyphs

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#394]
Not sure how repeatable this is, but I have on a couple of occasions had the glyphs wiped from the gene badges. The last tim it happened, I did the following:
1. Import a gene list
2. Analyze all
3. Reorder by relevance
4. Looked at some genes
5. Reorder by gene name

After the last step, everything is cleared out.

**Comment by tonydisera** [comment]
Whoa Nellie.  (Cowboy slang).  That must have sucked.  I'll take a look at this.  Feel free to move anything over to the in progress column if you would like me to start working on it.  I'll probably hold off on commits until after the release.

**Comment by AlistairNWard** [comment]
Ha - believe me, I feel free to pile things into the progress column!! It's actually less of an issue than you think. I had reordered on relevance and looked at everything I needed to (really useful), but then just tried to reorder. I didn't need the data anymore, so no harm done,  just needs to be recorded! Not a high priority for now.

**Comment by AlistairNWard** [comment]
Updates to filtering seem to have removed this problem.
