### ISSUE TITLE
Simplify gene links and dropdowns

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#399]
I'm wondering if there is a way to simplify the interface for the gene buttons.  Right now, we have 3 links to the left ('Analyze all', 'Remove all', and 'cache...) and a Sort dropdown and 'view 50' | 'all' links to the right.

<img width="1190" alt="screenshot 2016-08-10 17 09 41" src="https://cloud.githubusercontent.com/assets/8420103/17574304/4e995c16-5f1d-11e6-9c0a-b2627dfaf0ec.png">

Here are a few of suggestions:
1.  Perhaps 'cache...' should be moved to a 'Settings' side panel since it is not a typical operation.  In face, once we come up with a more sensible local caching strategy, perhaps this button will go away entirely or only appear when local cache is filled up.
1.  'Remove all' is usually only used when analyzing a new set of genes, by either importing a new set or running phenolyzer on a new phenotype term.  Prompt user 'Remove current genes?"  in both of these cases before new genes are shown.  If we want to keep the 'Remove all' link, perhaps rename it to 'Clear all' and move over to the right side.
2.  Rename 'Sort' to 'Order genes' in the dropdown on the right side.  Change links for View 50  and View all to a dropdown that has 'View...' with options for '20 per page', '50 per page', or 'all genes'.  The other option would be to combine the sort and view (paging) options under 1 dropdown called 'View', containing the following menu items:  Order by gene name, Order by relevance, Show in original order, View 40 genes per page, View all genes

**Comment by AlistairNWard** [comment]
This has been addressed.
