### ISSUE TITLE
Min coverage selector fails

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#4]
Putting in a minimum coverage doesn't effect the displayed variants.

**Comment by tonydisera** [comment]
This is the same issue raised in https://github.com/tonydisera/gene.iobio/issues/6.  I propose a small 'go' button beside the Coverage input and the AF range input fields.

**Comment by tonydisera** [comment]
Added 'go' button beside coverage and af input fields.

**Comment by tonydisera** [comment]
Fixed by cloning variant before placing in vcfData (for feature matrix).
