### ISSUE TITLE
ARUP would like ability to export variants to excel spreadsheet

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#403]

**Comment by AlistairNWard** [comment]
I'm moving this to prepare to validate as it deals with the output to Excel functionality.

**Comment by AlistairNWard** [comment]
The HGVSc and HGVSp identifiers in the Excel report export as the loading image.

<img class=gene-badge-loader glyph" style="width: 12px;height: 12px;" src="assets/images/wheel.gif"><span style="font-style:italic;margin-left:4px">loading</span>"

Once the HGVS codes are loaded, do they get cached? It appears that they reload every time I reselect the variant.

**Comment by tonydisera** [comment]
Oops!  The feature went a bit above and beyond its intended purpose!

**Comment by tonydisera** [comment]
This is fixed now.

**Comment by AlistairNWard** [comment]
Yes it is.
