### ISSUE TITLE
Calling variants with alignments doesn't get Clinvar annotations

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#411]
After troubleshooting this problem, I noticed that some clinvar annotations were being captured, but never refreshed in the ranked variants table.  In fact, this problem was occurring not only for called variants, but for loaded variants as well.  The timing of the "refresh charts" was off, causing the refresh too occur before the last batches of clinvar data had been loaded to the variants.

**Comment by AlistairNWard** [comment]
I ran a known EIEE case with a clinvar variant in SCN8A. This was where I first noticed that called variants weren't annotated with ClinVar. Now they are annotated as expected.
