### ISSUE TITLE
Colour exons based on coverage

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#419]

**Comment by tonydisera** [comment]
I've created a Jasmine unit test that runs samtools mpileup on the each coding region of the a gene to compare to the output from Al's gene coverage service.  For the most part, the numbers correspond, but there are some differences.  This output shows the each coding region's coverage metric, and beside it, the one generated from samtools mpileup.  The ones with a asterisk have a delta greater than the standard deviation.

Although this script doesn't shift coverage based on deletions, or exclude soft/hard clips or insertions, I've run a script (see comment below) and get similar stats as this jasmine unit test.

GENE AIRE
1 45705890-45706021    sd=2         mean=45 vs. 44          min=39 vs. 39          max=49 vs. 48 
2 45706440-45706614    sd=6         mean=49 vs. 47          min=39 vs. 36          max=63 vs. 62 
3 45706861-45707016    sd=0         mean=0 vs. 0          min=0 vs. 0          max=0 vs. 0 
4 45707400-45707474    sd=4         mean=50 vs. 48          min=43 vs. 40          max=55 vs. 55 
5 45708228-45708341    sd=4         mean=60 vs. 56          min=50 vs. 46          max=65 vs. 64 
6 45709540-45709685    sd=5         mean=47 vs. 44          min=36 vs. 32          max=55 vs. 52 
7 45709871-45709951    sd=6         mean=49 vs. 48          min=39 vs. 38          max=58 vs. 57 
8 45710978-45711093    sd=2         mean=43 vs. 40*         min=39 vs. 35*         max=47 vs. 45 
9 45712185-45712284    sd=4         mean=49 vs. 46          min=43 vs. 41          max=56 vs. 53 
10 45712876-45713058    sd=7         mean=47 vs. 45          min=35 vs. 30          max=62 vs. 61 
11 45713672-45713793    sd=6         mean=34 vs. 0*         min=25 vs. 0*         max=41 vs. 0*
12 45714284-45714386    sd=3         mean=31 vs. 30          min=24 vs. 19*         max=36 vs. 35 
13 45716266-45716328    sd=3         mean=38 vs. 36          min=33 vs. 31          max=43 vs. 42 
14 45717539-45717610    sd=3         mean=48 vs. 46          min=42 vs. 41          max=52 vs. 52 
AIRE NA    sd=8         mean=45 vs. 37          min=24 vs. 0*         max=65 vs. 64 


GENE PDHA1
1 19362156-19362212    sd=3         mean=41 vs. 38*         min=36 vs. 33*         max=44 vs. 43 
2 19364628-19364741    sd=0         mean=0 vs. 0          min=0 vs. 0          max=0 vs. 0 
3 19367430-19367489    sd=3         mean=76 vs. 71*         min=69 vs. 65*         max=80 vs. 77 
4 19368055-19368228    sd=4         mean=55 vs. 53          min=45 vs. 44          max=64 vs. 61 
5 19369399-19369525    sd=11         mean=84 vs. 81          min=65 vs. 64          max=103 vs. 101 
6 19371200-19371291    sd=3         mean=51 vs. 48          min=44 vs. 41          max=56 vs. 54 
7 19372609-19372701    sd=6         mean=50 vs. 49          min=36 vs. 34          max=57 vs. 56 
8 19373467-19373622    sd=5         mean=53 vs. 50          min=38 vs. 33          max=61 vs. 60 
9 19373804-19373875    sd=3         mean=51 vs. 48          min=43 vs. 39*         max=55 vs. 54 
10 19375770-19375837    sd=3         mean=59 vs. 57          min=51 vs. 50          max=63 vs. 61 
11 19377034-19377142    sd=2         mean=44 vs. 41*         min=39 vs. 38          max=48 vs. 45*
12 19377607-19377771    sd=4         mean=49 vs. 48          min=40 vs. 39          max=58 vs. 56 
PDHA1 NA    sd=13         mean=55 vs. 42          min=36 vs. 0*         max=103 vs. 101

**Comment by tonydisera** [comment]
You can run this script on nv-dev-new to compare the mean coverage using samtools mpileup, excluding soft and hard clips as well as insertions.

~/minion/bin/samtools view -h https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam 21:45705890-45706021 | awk '($6 !~ /S/ && $6 !~ /H/ && $6 !~ /I/) || $1 ~ /@/' | ~/minion/bin/samtools view -b | ~/minion/bin/samtools mpileup - | awk '$5 !~ /*/ && $2 >= 45705890 && $2 <= 45706021' | awk -v N=4 '{ sum += $N } END { if (NR > 0) print sum / NR }'

**Comment by AlistairNWard** [comment]
In the list above, are the samtools values listed first or second?

**Comment by tonydisera** [comment]
The second value is from samtools mpileup.

**Comment by AlistairNWard** [comment]
Instead of providing the coverage stats by hovering over the exclamation mark for failing exons, should we just include them in the normal mouse over the exon? As it stands, I cannot find any of the stats for exons that pass.

**Comment by tonydisera** [comment]
Hi Al.  I just revised the unit test output for genes AIRE and PDHA1.  As we suspected, the exon with the 0 mean,min,max for AIRE was due to a unit test problem.  Thanks!

**Comment by tonydisera** [comment]
Hi Al.  The latest gene.iobio on stage now has the fix so that the gene coverage stats show when hovering over any exon.
