### ISSUE TITLE
Incorrect hgvsc for variant

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#424]

**Comment by tonydisera** [comment]
To reproduce:  Run the platinum exome (demo) variants for the proband.  Select gene RAI1, filter with AF < 1% and PASS filter.  2 variants show.  Click on the first one in the ranked variants table.  Note that the hgvsc shows C->T, but the variant is C->T.

**Comment by tonydisera** [comment]
This is weird.  I cannot reproduce this.  It seems like the wrong data was getting parsed from VEP, but I don't see how this could have happened.

**Comment by tonydisera** [comment]
This would an excellent test case

**Comment by nielsonphu** [comment]
Test case implemented on dev:

gulp e2e --test e2e/spec/hgvsc_matches_up_with_matrix_tooltip_info_spec.js -e chrome
