### ISSUE TITLE
Hover information doesn't show when hovering directly above triangles, diamonds, and circles in VEP matrix row

### ISSUE THREAD

**Issue by nielsonphu** [tonydisera/gene.iobio#427]
Using BRCA1 gene under the platinum trio sample dataset.

The hover works fine for rectangles. It also works when hovering inside the box, but not directly over the symbol.

**Comment by tonydisera** [comment]
Good find!  This is probably a high priority issue.

**Comment by tonydisera** [comment]
Thanks for catching this, Neilson. I just pushed the fix to the dev branch if you want to give it a try. :-)

**Comment by AlistairNWard** [comment]
This is a weird one. I was just checking on this and noticed that when running from the dev branch, the number of displayed variants seems way off. The proband card still reports that 44 variants are loaded, but I'm only seeing 8 variants displayed and only 8 in the rank variants table. There are no longer any non-SNPs displayed, so I can't check the fix!

**Comment by AlistairNWard** [comment]
![screen shot 2016-11-01 at 9 01 18 am](https://cloud.githubusercontent.com/assets/523111/19890548/d8d96d28-a011-11e6-96da-1ef860aa857b.png)

**Comment by nielsonphu** [comment]
I'll look into this.

**Comment by nielsonphu** [comment]
As discussed with Alistair yesterday, I refactored the filtering code to actually filter on afMin and afMax, whereas previously all variants were being accepted when afMin=0 and afMax=1. Unfortunately, the filtering code now excludes afExAC = -100 so those variants are not being loaded. The solution seems to add a different flag in place of afExAC=-100. Once everything is resolved, we should make the af range text fields visible so that they can be used.

**Comment by tonydisera** [comment]
Hi Nielson.  Are you fixing this or should I?  I noticed that the dev branch is still filtering out variants because of this bug.
