### ISSUE TITLE
Cannot tell if analyze all is finished with multiple pages of genes

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#436]
1. Load a data set (demo exome should work).
2. Add the ACMG56 genes so we have gene badges spread over 2 pages.
3. Analyze all.
4. When the first page of genes have been analyzed, analysis continues on page 2. But there is no indication on the first page is still proceeding. I could easily think analysis is finished and reorder by relevance and finish my analysis. The remaining genes continue analysing, but were not included in the reordering. If one of these last genes harboured an important variant, I might miss it!

**Comment by AlistairNWard** [comment]
Possible solutions:

1. Move Analyze all and gene sorting to left panel

2. Add the gene currently being analyzed and working symbol next to or under analyze all, so it's always clear that work is ongoing.

3. Maybe change drop down to buttons.

4. Have something that indicates that genes are sorted by coverage, relevance or unsorted. If we now apply filters, this is always updated to say unsorted requiring user input to resort.

**Comment by nielsonphu** [comment]
Solution #2 implemented.

Branch: issue_436
PR: https://github.com/tonydisera/gene.iobio/pull/456
