### ISSUE TITLE
Sort by relevance resetting when changing pages

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#439]

**Comment by AlistairNWard** [comment]
This is the same as #437.

**Comment by tonydisera** [comment]
Damn.  You are scaring me.  I hadn't even entered the description......  I think we need to fix this in the next release.  Thoughts?

**Comment by AlistairNWard** [comment]
Things don't get by me...!

**Comment by tonydisera** [comment]
Apparently not.  Your Slack account showed as inactive this morning, so I thought I was safe entering duplicate bug reports.

**Comment by AlistairNWard** [comment]
And yes, #437 is close to the top of the priority list, so we can put it in the next release. Once we get into the groove, I think this will work well. Once we get the stuff in the next release through to validate, we can then barter over the things that get moved in for the next release.
