### ISSUE TITLE
All gene names not showing in lookup list

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#44]
From Al -
I think there may be a problem with the way the gene list operates. Basically, it appears that the list is limited to having 10 entries in the drop down list. There may be other genes with the same prefix, but they're not displayed because there are already 10 in the list. If you add another character to the name, the list will update etc. My guess is that the problem with tp53 is that there are many other genes that being with this prefix, so the drop down is giving me 10 possible genes with this prefix, but the gene tp53 isn't one of them. Because I can't just press enter to select tp53, there is no way I can get to the gene. As I see it there are two solutions:

a) If you want to limit the list to 10, then the list needs to be sorted, shortest gene name first. This still does not guarantee solution, but would likely do a lot better. At the least, if what appears in the box is a valid gene, this gene should be the first in the list. This would guarantee that you can always type the gene name and get the gene.

b) Allow the user to press enter in the gene box when the name is typed in. Only do anything if the name is valid.

c) Display all available genes in a scrollable drop down. Early in the search, this would be massive, so I can see why this wasn't the choice gone with.

I would likely go with a), but I think this would solve the problem. Does this make sense?

**Comment by tonydisera** [comment]
Comment for Chase and Al -
The size limit of lists is coming from the underlying library. I'm sure it's configurable, but I didn't realize it was cutting the list. I think we should be able to handle massive lists, but it'll need to be tested.

As for pressing enter, yes it should select the gene. We need to add this to the gene list widget.

**Comment by tonydisera** [comment]
Chase was right.  There is an option for increasing the length of the dropdown.  I've pushed a workaround by increasing the list to 20 (now all of the tp53 genes show).  The real fix is to deal with scrolling and make the list limit even larger or provide a '...more' link.

**Comment by AlistairNWard** [comment]
I think this should be raised up the list. We don't want people unable to find required genes. If this is not a big fix, I'm going to move this up the milestone list.

**Comment by AlistairNWard** [comment]
This has been updated. What is the current status? Is there still a limit, or do we see all possible genes? If this is fixed, we can close.

**Comment by tonydisera** [comment]
This is fixed.  A vertical scrollbar has been added to the gene dropdown, so there shouldn't be any limit how the number of genes shown.
