### ISSUE TITLE
Warning badge (orange triange with !) is disappearing on gene buttons after sorting or paging

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#445]

**Comment by nielsonphu** [comment]
Added a selenium test for this on branch issue_445:

gulp e2e --test e2e/spec/gene_badges/paginating_should_not_remove_warning_badge_spec.js -e chrome

This test should pass once this is fixed.

**Comment by nielsonphu** [comment]
When testing this, I ran across another issue:
"Annotating variants with VEP" hangs and gets caught in an infinite loop when selecting a gene badge with a warning sign. To replicate, choose the sample platinum data and select "S100A3". It hangs. Note that analyzing all gives this gene a warning sign.

**Comment by tonydisera** [comment]
Interesting.  I fixed a bug a few weeks ago that seemed to be the same problem described in this issue.  Let me look back through the commit logs to if I can locate the fix and see if it is on the dev branch.

**Comment by nielsonphu** [comment]
I merged dev into this branch yesterday. I'll see if I can replicate on dev to confirm.

**Comment by tonydisera** [comment]
I can't reproduce the bug.  So I'm wondering if a bug fix was merged to dev that has resolved this issue.  Nielson, can you give it another try?

**Comment by nielsonphu** [comment]
Fixed with passing selenium test. Pull request: https://github.com/tonydisera/gene.iobio/pull/505
