### ISSUE TITLE
Variant calling only occurs on zoomed in region

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#446]
Is this by design? For example, use the link at the end of the email, zoom in on the far right couple of exons and call variants. Nothing is called. Zoom out, recall and we call a variant in the third exon. Do we only want to call on the zoomed region? If we do, we should be explicit that that is what is happening. Especially since, after calling, zoom out, we just see a summary of variants called and have no indication that we only looked in a small region.

http://nv-dev.iobio.io/gene.iobio/?rel0=proband&rel1=mother&rel2=father&rel=mother&name0=NA12878&vcf0=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz&bam0=https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam&sample0=NA12878&name1=NA12892&vcf1=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz&bam1=https://s3.amazonaws.com/iobio/samples/bam/NA12892.exome.bam&sample1=NA12892&name2=NA12891&vcf2=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz&bam2=https://s3.amazonaws.com/iobio/samples/bam/NA12891.exome.bam&sample2=NA12891&gene=MYLK2&genes=RAI1,AIRE,MYLK2&affectedSibs=&unaffectedSibs=

**Comment by tonydisera** [comment]
No.  This is a bug in my book.

**Comment by AlistairNWard** [comment]
This needs to be fixed.

**Comment by AlistairNWard** [comment]
Superseded by #608.
