### ISSUE TITLE
Coverage tooltip fixed distance from the cursor

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#447]
Open up the demo data set and hover over the coverage track to get info on the depth of coverage. The tooltip is quite a distance from the cursor and as you move to the right, the tooltip stays in the same relative position. Ultimately, this means you can't see the depth as you get to the right of the screen.

Should add a test for this.

**Comment by AlistairNWard** [comment]
![screen shot 2016-09-16 at 11 00 30 am](https://cloud.githubusercontent.com/assets/523111/18590439/d221e174-7bfc-11e6-8512-106d93bbbac0.png)

**Comment by AlistairNWard** [comment]
You can see the tooltip disappearing off the edge of the screen.

**Comment by nielsonphu** [comment]
Fixed with an improvement to responsiveness to hover: 

Branch: issue_447
PR: https://github.com/tonydisera/gene.iobio/pull/452

**Comment by AlistairNWard** [comment]
@nielsonphu Is it possible to implement the same fix for hovering over the gene model. For example, open the demo data set, go to the Proband card and hover over an exon. The tooltip is centred on the middle of the exon. Now zoom in on an exon. The tooltip is always in the centre of the screen.

**Comment by AlistairNWard** [comment]
![screen shot 2016-10-05 at 8 36 35 am](https://cloud.githubusercontent.com/assets/523111/19113299/f770f3dc-8ad6-11e6-9e08-7ca2b8857167.png)
