### ISSUE TITLE
Trio information in the mouse over

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#46]
I think it would be good to see information on all samples in the mouse over information. For example, in the RAI1 example, the proband is homozygous for a deleterious mutation. This mutation is recessive, so we know that both parents are hets, but only because the variant appears in the rank matrix. I think it would be valuable to have all information in the pop-up. So under zygosity, we should show the zygosity of the parents as well (zygosity HOM [Mother: HET, Father: HET]). If we're hovering over a mutation in the mother, we would see the same, but the proband in the brackets. This may not be scalable to arbitrary samples, but maybe it is.

**Comment by tonydisera** [comment]
Excellent suggestion.

**Comment by tonydisera** [comment]
Implemented in variant tooltip (and examine variant side panel) for proband variants.  When hovering over variant in mother or father variant, only zygosity the variant in review is shown in the tooltip.
<img width="340" alt="screen shot 2016-01-03 at 8 08 41 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082814/d1da2a58-b255-11e5-802b-f68ba675d08c.png">

Tooltip for mother/father:
<img width="342" alt="screen shot 2016-01-03 at 8 09 07 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082821/e46176e0-b255-11e5-9e93-fb39bf169def.png">
