### ISSUE TITLE
Name of VCF filter is cut short

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#472]
Open the ExAC data set in BRCA1:

http://gene.iobio.io/?rel0=proband&rel1=mother&rel2=father&name0=&affectedSibs=&unaffectedSibs=&genes=BRCA1&gene=BRCA1&vcf0=https://s3.amazonaws.com/iobio/samples/vcf/ExAC.r0.3.1.sites.vep.noInfo.vcf.gz

then open the filter menu. In the VCF Filter Status, we see the list of all the different filter fields in the VCF. Couple of comments:
1. The name has a fixed width, so there is no way of differentiating most of these values.
2. If the filter value is not defined in the header, VEP will fail. I had to doctor the VCF to get it to work in gene. I'm wondering if there is a way that we can manually update the header, or find another workaround where this happens. Basically, the ExAC vcf as given cannot be loaded into gene.

**Comment by tonydisera** [comment]
The first problem is easily fixed.  The svg width needs to be bumped up from 90 to 190px.

We use bcftools to doctor the header for contig records, so I don't see why we couldn't do the same for missing filter header records.  Can you still have the header records you doctored in?  If so, would you mind including in a comment?

**Comment by AlistairNWard** [comment]
In the ExAC data, I added the line:

##FILTER=<ID=AC_Adj0_Filter,Description="Filter">

I think VEP fails if this is missing.

**Comment by AlistairNWard** [comment]
##FILTER=\<ID=AC_Adj0_Filter,Description="Filter">

**Comment by tonydisera** [comment]
Awesome.  Thanks Al!!

**Comment by AlistairNWard** [comment]
Superseded by #735.
