### ISSUE TITLE
Freebayes variants do not get coloured by effect

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#476]
In default mode, variants are coloured by impact. Call variants and get variants in the called and loaded frames. Now colour by effect, not impact. The loaded variants change, but the called variants do not.

As as example, we were looking at FOXN1 in A358.

**Comment by AlistairNWard** [comment]
I just reran this and cannot recreate. Perhaps this is worth generating a Selenium test for @nielsonphu ?

**Comment by tonydisera** [comment]
This seems to be working.  Closing issue.
