### ISSUE TITLE
Symbols for siblings

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#479]
I've looked at a few cases with affected and unaffected sibs and the symbols appearing the Rank Variants table aren't always obvious. We should revisit these.

**Comment by AlistairNWard** [comment]
![screen shot 2016-11-22 at 10 34 31 am](https://cloud.githubusercontent.com/assets/523111/20529771/50a44588-b09f-11e6-9aa3-93f170a18172.png)

**Comment by AlistairNWard** [comment]
![screen shot 2016-11-22 at 10 35 22 am](https://cloud.githubusercontent.com/assets/523111/20529787/6d515752-b09f-11e6-973c-bc8e4c79d267.png)

**Comment by tonydisera** [comment]
# Current Solution:

## Affected Sibs

### When proband variant follows recessive inheritance mode:
1. recessive_none:  cross through recessive symbol indicate that none of the affected sibs recessive 
2. recessive_all:   recessive symbol               indicate that all affected sibs are recessive 
3. recessive_some:  recessive symbol, small        indicate that some of the affected sibs are not recessive
###Proband variant is NOT recessive, currently showns as checkmarks:
1. present_none:    red checkmark                  indicate that affected sib does not have this same variant
2. present_all:     green checkmark                indicate that all of the affected sibs have this same variant
3. present_some:    green checkmark, small         indicate that some of the affected sibs have this same variant  

## Unaffected Sibs
### When proband variant follows recessive inheritance mode:
1. recessive_none:  n/a
2. recessive_all:   recessive symbol               indicate that all unaffected sibs are recessive 
3. recessive_some:  recessive symbol, small        indicate that some of the unaffected sibs are not recessive
### Proband variant is NOT recessive, currently showns as checkmarks:
1. present_none:    blank                          indicate that unaffected sib does not have this same variant
2. present_all:     red checkmark                  indicate that all of the unaffected sibs have this same variant
3. present_some:    red checkmark, small           indicate that some of the unaffected sibs have this same variant  `

**Comment by tonydisera** [comment]
# Proposed Solution:

## Affected Sibs
### When proband variant follows recessive inheritance mode:
1. recessive_none:  exclamation mark       
2. recessive_all:   check mark                     
3. recessive_some:  exclamation mark with count
### Proband variant is NOT recessive, currently showns as checkmarks:
1. present_none:    exclamation mark
2. present_all:     check mark
3. present_some:    exclamation mark with count

## Unaffected Sibs
### When proband variant follows recessive inheritance mode:
1. recessive_none:  n/a
2. recessive_all:   exclamation mark
3. recessive_some:  exclamation mark with count
### Proband variant is NOT recessive, currently showns as checkmarks:
1. present_none:    blank
2. present_all:     exclamation mark
3. present_some:    exclamation mark with count

**Comment by tonydisera** [comment]
Actually, I came up with another solution.   
1.  Show a simple glyph of thumbs up, thumbs down, or question mark in each cell.
2.  The Ranked Variants table row labels are renamed to 'Present in Affected sibs' and 'Absent in Unaffected sibs'.
3. For 'Present in Affected sibs', thumbs-up is shown when all affected sibs have  the current variant; thumbs-down when none of the affected sibs have the variant; question mark when SOME affected sibs have the current variant.  For a proband recessive variant, only show thumbs up if ALL of the affected sibs are recessive.
4. Show the opposite glyphs for 'Absent in Unaffected sibs'.
5.  The tooltip will show the zygosity for all affected and unaffected sibs.

**Comment by tonydisera** [comment]
You can try out this enhancement on http://nv-dev.iobio.io. Click on the gene.iobio (2.2.1) release.

**Comment by AlistairNWard** [comment]
Should we give gene.iobio access to bam files for sibs? The tooltip just gives het, homref etc without the allele counts. If we have bam files, we can give the allele counts as well.

**Comment by tonydisera** [comment]
Actually, we could show the allele counts without the bams since the total depth is the ref read counts + the alt read counts or the depth field (if provided) from the vcf.  Would you like to see the allele counts for this next release (2.2.1)?

**Comment by AlistairNWard** [comment]
Not a push for this release, but it would be nice to have the same allele count information as the main trio.

**Comment by tonydisera** [comment]
I'll open up a new issue on showing the allele counts for the sibs.
