### ISSUE TITLE
Explore expanding gene list based on pathways.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#487]
Also, be able to expand gene list based on gene family.

**Comment by mvelinder** [comment]
![screenshot from 2016-11-07 15-31-19](https://cloud.githubusercontent.com/assets/22081541/20078809/516cd27e-a4ff-11e6-9b36-e9a3264cc919.png)

**Comment by mvelinder** [comment]
See "Analysis Resources" document for pathway tools

**Comment by AlistairNWard** [comment]
Should be part of gene list app.
