### ISSUE TITLE
Load ExAC 0.3.1 to af database

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#493]
We need to load 0.3.1 (released March 2016) to the af db

**Comment by tonydisera** [comment]
Loaded on nv-dev.iobio in /mnt/af.db

**Comment by AlistairNWard** [comment]
We should take a look at the new and improved gnomAD. 

http://gnomad.broadinstitute.org/about

**Comment by tonydisera** [comment]
Very cool.
