### ISSUE TITLE
Adding gene before data doesn't work

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#497]
1. Open a fresh instance of nv-dev.iobio.io/gene.iobio
2. Select a gene name (MYLKS2) prior to adding data. The gene model doesn't load in - in fact, nothing happens. 
3. Add data then click "Load". The gene entry panel then shakes at you, but there is a gene defined.

I'm adding Nielson to this as well, since it would be good to include a Selenium test that ensures that when a gene is entered, the gene model appears even if no data is added.

**Comment by tonydisera** [comment]
I can't reproduce this.  When I type in MYLKS2 in the gene search box, the gene isn't found.

**Comment by tonydisera** [comment]
I just fixed a number of bugs related to unknown genes.  So now, if a gene is specified in the URL or imported and it isn't found (from our RefSeq and Gencode gene list), the user is warned and the unknown genes are removed from the list.

<img width="669" alt="screenshot 2017-01-18 17 20 02" src="https://cloud.githubusercontent.com/assets/8420103/22088607/8dd4508a-dda2-11e6-94c6-9ec36b7ea536.png">
