### ISSUE TITLE
Call variants on all genes

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#498]
Add a button to call variants on all genes (like the analyze all).

**Comment by AlistairNWard** [comment]
We have an up-to-date count of the number of analyzed genes, do we also need one that shows progress on called genes? Obviously, we don't want to start cluttering up the display, so maybe we do something with colour in the currant summary bar? Currently it is blue and while for analyzed or not analyzed. Maybe it goes red when calling has also been done? Maybe we then list under the box text to say how many have been analyzed and called?

**Comment by AlistairNWard** [comment]
We probably need something in the gene badge to show if calling has happened on that gene. Maybe a second checkmark, but in a different colour.

**Comment by AlistairNWard** [comment]
If you out up multiple genes, then click on call all genes, the gene badges then show glyphs on contained variants, and the number of analyzed genes is updated. I'm assuming that when calling occurs, we also "analyze" the loaded genes at the same time?

**Comment by AlistairNWard** [comment]
Open demo data and let the first gene analyze. Call variants in all genes. When analysis of the first gene completes, the panels are not updated to show the called variants.

**Comment by tonydisera** [comment]
Hi Al.  I don't think I understand the bug.  The first gene in the demo dataset 'RAI1' doesn't have any called variants.

**Comment by AlistairNWard** [comment]
Sorry, I wasn't clear. There are no called variants, but the panel where the called variants should go don't appear, and the count of called variants (which would be 0) is not present, so as far as can be ascertained from the proband card, no calling has taken place.

If it makes it clearer, try this. Open demo data and analyze all. Now move to MYLK2 and call on all genes. We step through all the genes, but the visualizations aren't updated (there is a called variant in MYLK2).  Click on MYLK2 (even though) I'm already looking at it, and the called variants appear.

**Comment by AlistairNWard** [comment]
![screen shot 2017-04-05 at 12 46 50 pm](https://cloud.githubusercontent.com/assets/523111/24716776/161da2e2-19fe-11e7-8cd2-de22fd221846.png)

**Comment by AlistairNWard** [comment]
In the above, the bar shows all genes have had variants called, but the proband card shows no evidence of this!

**Comment by tonydisera** [comment]
I see, so the currently selected gene should have its variant cards refreshed after variants have been called on it during 'Call variants on all genes'.

**Comment by AlistairNWard** [comment]
Yes, that would be a more understandable way of saying it!

**Comment by AlistairNWard** [comment]
Yep, I'm seeing the visualizations update.
