### ISSUE TITLE
Ranking on AF

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#5]
The AF ranking has the unknown AF as the highest rank. This should be prioritized the least and <0.01% should have the highest priority.

**Comment by tonydisera** [comment]
Fixed.  Now the 'unknown' AF's are assigned the lowest rank.  Also changed glyph from red to outline in black.

**Comment by AlistairNWard** [comment]
Although, maybe I'm misunderstanding the interpretation. By unknown, do we mean that the variant is in the 1000G/Exac data set, but there is no AF to extract, or is it not present in the data set? If not present, then this would imply a novel variant and should be the highest ranking. If 'unknown' means that we just don't have information on a known variant, then it should be prioritized low.

**Comment by tonydisera** [comment]
Excellent point.  I've gone back and forth about this in my mind, but you articulate the point more clearly.

Right now, unknown can mean either not found or found but equal to 0, although I suspect this second case never occurs.  You bring up an interesting scenario that I had not considered in that the AF hasn't been determined but the variant exists in the population dataset.  This is probably worth investigating.

For now, should I back out the 'fix' or leave it alone.  (I'm pretty sure we can get a better understanding from Yi on this matter tomorrow.)

**Comment by AlistairNWard** [comment]
We should probably discuss this and make sure we do the right thing. I would let your changes stand for now. My initial assumption would be that if the variant is not found in the database, then this is a private mutation and thus should be the most highly ranked variant. I am not totally sure what AF=0 means. In these cases, is the AC field present? This would tell us how many chromosomes were observed with the alternate allele. The question is whether they round to zero. If this is a singleton, e.g. only a single chromosome in the entire 5,000+ sequenced chromosomes in 1kG, do they round the AF to 0? I guess the true value would be AF=0.0002, but I honestly not sure what the meaning of AF=0 is.

**Comment by tonydisera** [comment]
Fixed.  AF=0 for ExAC splits into two categories:  private (in coding region) and unknown (not in coding region).
