### ISSUE TITLE
gnomAD

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#503]
Get allele frequencies from gnomAD browser. This will also handle exons.

**Comment by tonydisera** [comment]
very good.  And what a name.

**Comment by mvelinder** [comment]
I'd like to make a further case for this. As well as including a link out to the Gnomad detailed frequency page like this: http://gnomad.broadinstitute.org/variant/16-3639827-G-A

Use case where gene.iobio reports 0% in ExAC and 1000G but Gnomad is 6%
![image](https://cloud.githubusercontent.com/assets/22081541/24918995/8a359432-1e9f-11e7-9323-9478c2b2e14e.png)
http://gnomad.broadinstitute.org/variant/16-3639827-G-A

Oddly though ExAC actually has 6%, but gene.iobio is reporting 0%

This variant was called with freebayes, would there be reason to think gene.iobio isn't correctly annotating frequencies from freebayes called variants?

**Comment by AlistairNWard** [comment]
Seems odd that it would successfully pull the correct rsid and not get the AF. Definitely should look into this.

**Comment by AlistairNWard** [comment]
I was just looking at this and noticed that some of the gnomAD AF values are listed as n/a. Does this still have relevance now that gnomAD is whole genome, not just exome?

**Comment by tonydisera** [comment]
Excellent eyes, my friend!  I'll look into this.
