### ISSUE TITLE
Show number of genes passing filter at top of filter panel for current filter applied

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#516]

**Comment by AlistairNWard** [comment]
I don't see this number.

**Comment by tonydisera** [comment]
Do you see this?

<img width="1346" alt="screenshot 2017-01-20 14 27 25" src="https://cloud.githubusercontent.com/assets/8420103/22166124/c3d82492-df1c-11e6-8b32-4e296522dc70.png">

**Comment by AlistairNWard** [comment]
Sorry, throwing this back, since I'm seeing a discrepancy.

1. Open gene.
2. Select demo data.
3. Analyze all.
4. Filter panel - select moderate, 1 gene passed filter.
5. In "manage genes", add BRCA2.
6. Click on BRCA2 to analyze,

When this is done, there is still only 1 passed gene, but BRCA2 does have a moderate variant, so it should be 2.

**Comment by AlistairNWard** [comment]
I think it doesn't update with new genes. I removed all, then typed AIRE in at the top. This has no moderate variants, but I'm still seeing that 1 passed filter.

**Comment by AlistairNWard** [comment]
Check.

**Comment by tonydisera** [comment]
Should we try to get this prompt for 'Analyze all' into this release?

**Comment by AlistairNWard** [comment]
I'm not personally a fan of forcing an analyze all on the user. If new genes are added, so long as the count of analyzed genes is accurate, I think that's ok. The filter counts are based on analyzed genes, but maybe we include text in the filter panel to warn the user if there are unanalyzed genes?

**Comment by tonydisera** [comment]
That's what I was thinking.  I'll move this issue back over to 'In progress' unless you think we can hold on this one for a while.

**Comment by AlistairNWard** [comment]
I don't think this is super critical. The information is all there. On the main display, the user can see that not all genes are analyzed, so applying filters logically cannot work on all genes. We need to make sure it's crystal clear, but I think we can hold on this for a while.
