### ISSUE TITLE
Manage gene input box closes with click

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#518]
In gene.iobio 2.2.0 clicking within the opened Manage box causes it to close

**Comment by mvelinder** [comment]
![image](https://cloud.githubusercontent.com/assets/22081541/21942046/a5abbdce-d988-11e6-86ec-03437df7d90a.png)

**Comment by tonydisera** [comment]
Good to know.  Thanks for reporting this!

**Comment by AlistairNWard** [comment]
If I use this feature to remove all genes, they don't all get removed. I have the demo genes AIRE, RAI1, MYLK2 and click remove all genes, click 'OK' in the pop up, and only one gene is removed every time.

**Comment by tonydisera** [comment]
I can't reproduce this, but I do believe you (just not in you).  It must be some combo of genius keystrokes.  Can you see if you can reproduce this bug?

**Comment by AlistairNWard** [comment]
I don't believe in myself either. So, just updated and things are slightly different now. Now I click remove all genes, the popup comes up, I press OK, and nothing happens. If I keep hammering OK, it eventually goes away and all the genes are gone, and I'm left in the gene that I had open, but there is no gene badge. If I then add another gene at the top of the page, a badge appears for the new gene, I move to it, and the gene I was in is not there. It seems as though remove all genes makes me click OK in the popup for each gene to be removed?

When all genes removed, I'm still looking at one gene, but with no badge. Select a new gene and there is a single badge, but I thought if I only had one gene open, there shouldn't be a badge, just details of the one gene? Also, I think remove all, should either:

1. remove all genes but the one you're currently in. Adding another gene would then mean you have two gene badges, or
2. All genes are removed, but you no longer have a gene model or variant data showing. Essentially clear the screen.

Sorry this is a total ramble.

**Comment by AlistairNWard** [comment]
This removes all genes, but I still see the info about the gene I was in before clicking remove. When I add a new gene, the gene I was just looking at is no longer available. Let's discuss this one.

**Comment by tonydisera** [comment]
I think we should clear out the currently selected gene, hiding all cards.  Then when the user types in a new gene or selects or imports a new gene list, the cards will appear with the new gene(s).

**Comment by AlistairNWard** [comment]
Works for me.
