### ISSUE TITLE
Show welcome panel rather than single 'Load demo data' button on gene.iobio launch

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#521]

**Comment by AlistairNWard** [comment]
One comment in addition to the email responses about reducing the volume of text. When you click Try it out, it takes a little while for the data to load, but the welcome panel remains in the meantime. Maybe the panel should clear away immediately, making it more obvious something is happening?

**Comment by tonydisera** [comment]
agreed.

**Comment by tonydisera** [comment]
Chase's suggestion:

Disease-Causing Variant Discovery & Interrogation 
- On the fly annotation
    - Functional impact (e.g. VEP, Sift, Polyphen
    - Allele Frequency (e.g. 1000G, ExAC)
    - Inheritance Mode
- Visualize Variants and Read Coverage together
- Analyze Trio's and unaffected siblings
- Instantly analyze VCF and BAM files both on your hard drive or on the web with no need to upload the entire file
