### ISSUE TITLE
When gene not found, need to warn user and remove from list

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#522]
Xiaomeng discovered a few bugs related to genes not found in Gencode or RefSeq.

1.  Import gene list with a gene not found (example: C2ORF91).  Click 'Analyze all' will 'stop' when it encounters an unknown gene. 
2.  If you click on the unknown gene, the 'loading' gif continues to show and the app errors without reporting the problem to the user.

To solve this, when genes are imported (from 'Import genes' or 'Manage genes' dropdowns), the app should validate the genes and notify the user of genes that will be bypassed.

Another bug we are seeing is that even if the gene list is changed, the 'Analyze all' seems to hold onto the old genes (in the local cache) so that the progress (example 19 of 30 genes) shows a denominator that is the 'old' genes still in the cache.

To address this, removing all genes, or removing single genes, or importing a new gene list should clear out the cache for genes that are no longer in the list.

**Comment by tonydisera** [comment]
It turns out that C2orf91 exists in the geneinfo db.  So the backend server has been changed to use a case insensitive search when looking up the gene model for a given gene name.

**Comment by AlistairNWard** [comment]
Ok, spotting some odd behaviour here.

1. Open with demo data.
2. Analyze all.
3. Import gene set and add c2orf91, bob.
4. Click done. BOB is correctly thrown away, and C2ORF91 added to the list, but I see '3 analyzed', not 3 of 4 analyzed.
5. Click analyze all and AIRE and MYLK2 appear to be analyzed even though they already have been.
6. When finished, I see '3 of 4 analyzed', but they've all been analyzed.
