### ISSUE TITLE
When variant is bookmarked, have link in tooltip to clear bookmark

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#526]

**Comment by AlistairNWard** [comment]
When I bookmark, a glyph appears marking it as bookmarked and the link changes to "remove bookmark". If I remove the bookmark, the bookmark glyph is removed from the table, but not from the tooltip, and the link should revert to "bookmark this variant".

**Comment by tonydisera** [comment]
Hmm....  this is working for me....
