### ISSUE TITLE
Make selection of transcript in transcripts dropdown easier.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#529]
From Al -

 When you open the transcript dropdown, it can be difficult to select a transcript. If you hover over an exon in one of the alternate transcripts, the mouse arrow changes to the selection arrow and it's easy. When you're over introns, you have to hover over the very thin line. Is it possible to have the vertical height for the transcript selection set to the height of the exon across the whole transcript? Or draw invisible introns, so hovering anywhere over the transcript acts the same way as hovering over the exon?

**Comment by AlistairNWard** [comment]
Way better!
