### ISSUE TITLE
When multi-sample vcf encountered, warn and indicate that only first sample will be analyzed

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#53]

**Comment by AlistairNWard** [comment]
We should include in this issue that the ultimate goal is to allow multisample vcf files and subset on the required samples. The data entry could be modified to pull available samples from the single vcf and the pedigree is defined based on the sample IDs.

**Comment by tonydisera** [comment]
Added new issue for long term solution of sample dropdown in data card.
