### ISSUE TITLE
Update demo data set

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#530]
Can we update the demo data set to the exome version of the Platinum data?

Paths:

VCF:
https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz

BAMs:
https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam

https://s3.amazonaws.com/iobio/samples/bam/NA12891.exome.bam

https://s3.amazonaws.com/iobio/samples/bam/NA12892.exome.bam

**Comment by AlistairNWard** [comment]
These work much better than the ones selected and have interesting variants that we can use the release 2.2.0 blog post.

**Comment by tonydisera** [comment]
Sure thing.  I wonder if the sample names were wrong.  The demo data pointed to 'NA19240' , 'NA19238', and 'NA19239'.

**Comment by AlistairNWard** [comment]
The names were wrong in the original demo data. The NA19240 etc were the exomes, not the platinum whole genomes.

**Comment by AlistairNWard** [comment]
I just checked the demo data and it's still the old data set. I'm throwing this back to "In progress".
