### ISSUE TITLE
Gene model not correctly chosen if no vcf provided

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#532]
This occurs on production and dev.

1. Open gene.iobio (production or dev)
2. Enter BRAF.
3. Enter the BAM:

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.bam

gene.iobio correctly identifies this as GRCh38.

4. Load. Yes to call variants.
5. The gene model lists GRCh37 coords for BRAF, and it says GRCh37 at the top of the page.

I also see the error:
BamMultiReader::LocatingIndexes: error while locating index files: 
	BamReader::LocateIndex: could not locate index: 
	BamRandomAccessController::LocateIndex: could not find index file for:/home/iobio/iobio/fifos/fifo-SJxWuGHwe

but not sure what this refers to.

6. Add in the vcf:

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.union.vcf.gz

**************
Ok, I think the problem is the order in which you do things. Repeat the instructions, but do 3 and 4, then 2, e.g. enter the gene name after entering the data. Then we see GRCh38!

**Comment by tonydisera** [comment]
Thank you for troubleshooting this!  I will try to fix this today. :-)

**Comment by AlistairNWard** [comment]
I went through these steps again, and it is fixed with respect to the reference genome. However, when I add the vcf, the variants are not loaded - I still only see the called variants. Since this is different, I'll close this issue and open #535.
