### ISSUE TITLE
Analyzing glyphs can disappear when switching views

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#534]
Need to replicate, but I open the demo dataset, select ACMG56 genes, analyse all, then while analysis is happening change between "View 40" and "View all". The yellow analyzing marker disappears from genes being analyzed, so I'm not sure what is being analyzed. Gene.iobio tells me a gene that is currently being analyzed, but the marker isn't attached to it.

**Comment by AlistairNWard** [comment]
![gene](https://cloud.githubusercontent.com/assets/523111/22300649/1efed488-e2f6-11e6-835f-5fdc3640c061.png)

**Comment by AlistairNWard** [comment]
Here's an odd little addition to this one. I started with the demo dataset, added C2ORF91, analyzed all, then selected ACMG56 and then analyzed all again. gene.iobio finished the ACMG56, but is telling me it is analyzing C2ORF91, even though that is not in the list.

**Comment by AlistairNWard** [comment]
![screen shot 2017-01-25 at 12 22 12 pm](https://cloud.githubusercontent.com/assets/523111/22301446/1d99aa48-e2f9-11e6-848b-6221ebe9299e.png)

**Comment by AlistairNWard** [comment]
I'm still seeing the second comment regarding C2ORF91.

**Comment by tonydisera** [comment]
You are such a good tester.  Yep, the problem was still there.  It should be fixed now.

**Comment by AlistairNWard** [comment]
Yep, I'm seeing this as fixed now.
