### ISSUE TITLE
Not all information is in tooltip

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#538]
Load the following vcf:

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.union.vcf.gz

in BRAF. There is a clinVar pathogenic SNP at chr7:140794409. Click on the column and the tooltip gives you the clinVar link, Sift/PolyPhen annotations etc. Click on the variant and the tooltip is missing all of this information.

**Comment by tonydisera** [comment]
I might be missing something...  


When I click on SNP chr7:140794409 in the ranked variants table I see the high impact variant, which doesn't have SIFT, PolyPhen, or Clinvar annotations.  

<img width="800" alt="screenshot 2017-01-25 17 41 53" src="https://cloud.githubusercontent.com/assets/8420103/22315703/9ec8968e-e325-11e6-88ad-766bfd49f8b4.png">

However, the first variant in the ranked variants table does have these annotations and shows them in the tooltip of the variant chart as well.

<img width="765" alt="screenshot 2017-01-25 17 41 59" src="https://cloud.githubusercontent.com/assets/8420103/22315718/b02f264a-e325-11e6-9df3-4882a03666ad.png">
