### ISSUE TITLE
The allele count bars are too thin to show counts when low coverage exists in a region of a gene

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#540]
The allele count bar widths are proportional to the coverage range for a particular gene. So, for example, if one variant has low coverage (10) and another variant has high coverage (200), then the variant with the low coverage shows a narrow box with an even narrower sliver for the allele count.  Xiaomeng suggested either setting the min and max to the second and third quartile or perhaps using intervals for the allele count bar widths.

**Comment by AlistairNWard** [comment]
Superseded by #422.
