### ISSUE TITLE
Update ACMG genes

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#541]
The ACMG gene list has been updated and we should be up to date.

1. Remove MYLK
2. Add ATP7B, BMPR1A, SMAD4, OTC
3. Link to paper: http://www.nature.com/gim/journal/vaop/ncurrent/full/gim2016190a.html

**Comment by AlistairNWard** [comment]
We should additionally include the ACMG version number, since they have agreed on versioning nomenclature. When these updates are included, we are at v2.0.

**Comment by tonydisera** [comment]
I updated the gene list, removed the '56' notation, and added the citation under 'Software and Resoures'.  Also, the Version dialog now shows ACMG v2

**Comment by AlistairNWard** [comment]
Make sure it's v2.0, just in case we miss a 2.1 update and become ambiguous.

**Comment by tonydisera** [comment]
Yep.  I just checked.
