### ISSUE TITLE
The vcf header records are truncated when parsed from a local file

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#544]
Download https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.union.vcf.gz. 

The header record is truncating contig records.

<img width="691" alt="screenshot 2017-01-26 09 43 07" src="https://cloud.githubusercontent.com/assets/8420103/22340799/e62dc7fc-e3ab-11e6-8e5c-cbdebf828a40.png">

**Comment by tonydisera** [comment]
Here is a diff between the header when coming from a URL (via tabix.iobio) and when parsed from a local file.

**Comment by AlistairNWard** [comment]
Retested the local files from Brandi in BRAF and everything is working well now.
