### ISSUE TITLE
Link out to ExAC in tooltip.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#545]

**Comment by AlistairNWard** [comment]
Do we still want to link out to ExAC now we are linking out to gnomAD? Probably yes.

**Comment by tonydisera** [comment]
Actually, I think that the gnomAD link should suffice once we know that VEP supports ALL gnomAD frequencies, including those from whole genome.

**Comment by AlistairNWard** [comment]
Ok, this is therefore complete.
