### ISSUE TITLE
Space in list of genes causes a failure

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#569]
I added the following comma separated list of genes in gene.iobio:

ALDH7A1,ALG13,ARFGEF2,ARFGEF2,ARGGEF15,ARHGEF9,ARX,CACNA2D2,CASK,CDKL5,CLCN4,DNM1,DOCK7,EEF1A2,EFHE1,GABRA1,GNAO1,GRIN2A,GRIN2B,HCN1,KCNA2,KCNB1,KCNH5,KCNQ2,KCNT1,NECAP1,PCD

H19,PLCB1,PNKP,PNPO,POLG,SCN1A,SCN2A,SCN8A,SLC13A5,SLC25A22,SLC2A1,SPTAN1,ST3GAL3,ST3GAL5,STXBP1,SYNGAP1,SZT2,TBC1D24,WWOX

and it totally fails. I copied the list from UNIX, and didn't notice that there was a space in the list, and it isn't clear when pasting into the box in gene that the space is there. The response from gene is to fail the whole list - nothing gets in.

**Comment by AlistairNWard** [comment]
<img width="972" alt="screen shot 2017-02-28 at 9 13 34 am" src="https://cloud.githubusercontent.com/assets/523111/23413729/da16536c-fd96-11e6-9940-2fc293100090.png">

**Comment by tonydisera** [comment]
Oops.  That is a pretty serious bug.  Should I patch this on our production release?

**Comment by AlistairNWard** [comment]
Works now.
