### ISSUE TITLE
Discrepancy in gene count

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#570]
I put in this gene list:

ALDH7A1, ALG13, ARFGEF2, ARFGEF2, ARHGEF9, ARX, CACNA2D2, CASK, CDKL5, CLCN4, DNM1, DOCK7, EEF1A2, GABRA1, GNAO1, GRIN2A, GRIN2B, HCN1, KCNA2, KCNB1, KCNH5, KCNQ2, KCNT1, NECAP1, PCDH19, PLCB1, PNKP, PNPO, POLG, SCN1A, SCN2A, SCN8A, SLC13A5, SLC25A22, SLC2A1, SPTAN1, ST3GAL3, ST3GAL5, STXBP1, SYNGAP1, SZT2, TBC1D24, WWOX

I think that there are 43 genes, and after analyze all, gene shows 43 analyzed genes. However, clicking on Known causative, 0 of 42 genes have a variant. There are only 42 gene badges, so I assume one of the genes was removed as unknown, but it is unclear which gene this is.

**Comment by AlistairNWard** [comment]
<img width="1437" alt="screen shot 2017-02-28 at 9 34 39 am" src="https://cloud.githubusercontent.com/assets/523111/23414426/29b1aa6e-fd99-11e6-90c3-10803ab2f324.png">

**Comment by AlistairNWard** [comment]
I played with the opening and closing the gene lists, so managed to get it to say 0 of 43 for known causative, but 1 of 42 for De novo. If I then click on de novo (as shown), go to select genes, import gene set, click ok, then go back to filters, de novo also has 1 of 43.

**Comment by tonydisera** [comment]
Good catch.  Thank you.

**Comment by tonydisera** [comment]
The main problem with the counts was that duplicate genes were not considered in the 'Import genes' logic.  In this particular case, gene ARFGEF2 was listed twice, so the true gene count was 42, not 43.    The import code now removes duplicate gene names and warns the user:

**Comment by AlistairNWard** [comment]
Confirmed to be working.
