### ISSUE TITLE
Team input on UI, including simplified nav bar, analyze all progress bar, no wiggle, gene input in data dialog

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#572]
During our IOBIO meeting in early March, the team made the following suggestions:

1. (done) Instead of wiggle animation use a border or arrow to bring attention to a UI component.
2. (done) If gene isn't entered when user enters Files dialog, force the user to select a gene before load button is enabled.
3. (done) Combine Analyzed and Filtered progress bars into one bar show passed, analyzed, not analyzed.
4. (done) Replace 'Clear all' link on Filters side panel with a button that shows before the standard filters (different width).
5. (done) De-select standard filter when an filter is subsequently clicked, which changes the filter criteria.

**Comment by AlistairNWard** [comment]
The "Clear all" button is not centred with respect to the standard filter buttons.

**Comment by tonydisera** [comment]
Wow.  You are good.  I had to look at it a few times to see that the button is, in fact, not centered.

**Comment by AlistairNWard** [comment]
Ha! I do try!

**Comment by tonydisera** [comment]
The "Clear all" button is now centered (with the standard filter buttons)

**Comment by AlistairNWard** [comment]
Yes it is!
