### ISSUE TITLE
Allow .tbi and .bai index files to be specified in a separate URL.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#579]
Chase: I’ve added a section to the bam url input to explicitly add the bai url.
this is for when the bai url is not just the bam url + .bai.
i have an updated version of od_samtools on nv-dev-new that works with the DNANexus data

so basically if the bai url is explicitly set then use od_samtools and add the bai url at the end of the command. we need to do the same thing for tabix_od and tbi url's. i’ve updatd the tabix_od service on nv-dev-new to work as well, but I haven’t had a chance to test it yet

**Comment by AlistairNWard** [comment]
Do we want the bai, tbi entries always visible on the data entry card? It is looking very cluttered, and adding the indexes is not the common mode of operation. Maybe have a toggle you have to select to see the entries boxes for them?

**Comment by tonydisera** [comment]
Agreed.  How about a checkbox at the top of the data dialog ( 'separate URLs for index files')

**Comment by AlistairNWard** [comment]
Yeah, that would work.

**Comment by tonydisera** [comment]
There is a new 'Separate URL for index files' checkbox on the 'Files' dialog.  The .tbi and .bai URL inputs only appear when this is checked.

**Comment by AlistairNWard** [comment]
The .tbi and .bai boxes only appear for the proband, not the parents, when putting in data for a trio.

**Comment by tonydisera** [comment]
Shit.  You are right.

**Comment by AlistairNWard** [comment]
Agreed, this is now working. One last comment. When I open http://nv-dev-new.iobio.io and click on Files, then click the button to see the separate index file inputs. The "accessing file header" then appears and spins, but not files have been supplied.

**Comment by tonydisera** [comment]
I'm glad you noticed this problem.  The code was a bit overzealous.  It has been dialed down to only attempt to refresh the samples if a .tbi was previously entered and is now being blanked out.

**Comment by AlistairNWard** [comment]
Yup. Fixed.
