### ISSUE TITLE
Hovering over rank variants column is odd

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#582]
Im using the data:

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.union.vcf.gz

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.bam

Hover over column in rank variants table. If I hover over the AF rows, everything is fine, but if I hover in the top rows, the whole column flashes as I move the mouse, and I have to be over the middle of the column for the tooltip to appear.

**Comment by AlistairNWard** [comment]
This is less critical, so can be put off to when you have time or the desire!

**Comment by AlistairNWard** [comment]
If the variant is bookmarked, hovering over the bookmark glyph will lose focus.

**Comment by AlistairNWard** [comment]
The last comment is still in effect. Not something to hold up the release.

**Comment by tonydisera** [comment]
Oh yeah.  And did you noticed that the wide bookmark shows up with duplicated glyphs.  This is a 2 second change.  Going for it now.

**Comment by tonydisera** [comment]
Okay.  This is fixed.  For reals.

**Comment by AlistairNWard** [comment]
Fixed it is!
