### ISSUE TITLE
Matt and Al suggestions for UI (Apr 6th)

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#584]
1.  (done)Hover over bookmark in bookmarks side panel should show full tooltip (like current click behavior, minus actually loading the gene?
2. (done) Show HGVSp (abbreviated) in bookmarks side panel.
3.  (done) Rename to version 2.3
4. (done) Variant tooltip should show - for empty values (e.g. blank for SIFT, PolyPhen, etc.)
5. (done)  ACMG loading gif when user clicks on button to indicate progress
6. (done) Navbar offset for 'Genes' hover highlight overlaps 'or'
7. When Phenolyzer returns empty results, show message 'No genes for phenotype'

**Comment by AlistairNWard** [comment]
I just did an analysis with 87 genes, and it takes a second or two for the standard filters to operate. Let's stick the loading glyph in the filter button while analysis is happening here as well!

**Comment by AlistairNWard** [comment]
Also on the Clear All filter. It actually just took a while (>10 seconds) after I clicked this for anything to happen, and the page was frozen in this time.
