### ISSUE TITLE
Unify progress bar / gene counts for 'Analyze all', 'Call all'

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#586]
2 stacked progress bars with no labels, just counts.  Top bar is for 'loaded variants'; bottom for 'called variants';  When filter applied, break 'analyzed' gene count into 'pass' and 'fail'.

Replace standard filter gene counts with these same stacked gene count bars.

**Comment by AlistairNWard** [comment]
If the stacked bar is a bit much next to the standard filter gene counts, we could just have a binary indicator of whether there are or aren't variants in the gene that pass the filter. You would then have to click the filter to see the stacked bar in the main window to see the actual counts.

**Comment by AlistairNWard** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/523111/24800113/b3080b46-1b6c-11e7-8ca5-4772c7929998.png)

**Comment by AlistairNWard** [comment]
This is looking good. I think the simple coloured box with number in is the right way to go.

**Comment by tonydisera** [comment]
A warning glyph will appear if filter counts if there are unanalyzed genes.

<img width="334" alt="screen shot 2017-04-17 at 2 47 45 pm" src="https://cloud.githubusercontent.com/assets/8420103/25104262/e4978250-237c-11e7-8aa3-d7f610e64e98.png">

**Comment by AlistairNWard** [comment]
I like this. I can't see it yet nv-dev-new, but I noticed one odd thing. Open the demo data and let RAI1 analyze. Apply the known causative feature and one gene is found. There is a spurious '0' in the main bar.

**Comment by AlistairNWard** [comment]
<img width="1072" alt="screen shot 2017-04-17 at 4 55 08 pm" src="https://cloud.githubusercontent.com/assets/523111/25104526/af7cc82a-238e-11e7-9f6f-c43d10b5df7d.png">

**Comment by tonydisera** [comment]
Good catch, Al.  I've fixed this problem with the '0' showing up in the progress bar after the filter is applied.  The latest is now available on http://nv-dev-new.iobio.io.

**Comment by AlistairNWard** [comment]
Yep, fixed and the warning glyph is there as well.
