### ISSUE TITLE
Analyze all followed by 'Call variants selected gene' results in incorrect variant chart (Al)

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#589]

**Comment by AlistairNWard** [comment]
I don't remember what the error was here, but is it fixed? I just did an analyze all followed by calling on a selected gene, and everything updated as expected.

**Comment by tonydisera** [comment]
Yes, this was fixed with a commit yesterday.  I'll move it to validated.  Thank you!
