### ISSUE TITLE
Het, Hom in tooltip appear as clickable

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#590]
Click on a variant and look at the allele counts for the three samples. If you hover over the box that tells the genotype, it appears as clickable, but it isn't.

**Comment by tonydisera** [comment]
Are you referring to the 'Proband' label that is shown in a bright blue font color?
<img width="271" alt="screen shot 2017-04-07 at 10 22 11 am" src="https://cloud.githubusercontent.com/assets/8420103/24809315/56712b3c-1b7c-11e7-9939-0839251b1bde.png">

This color indicates that this is the current sample.  For example, if you hover over a variant in the Mom's variant card, the blue color is shown for the "Mother" label.  We could use another device to indicating "current sample" like an asterisk or an arrow.
