### ISSUE TITLE
On nv-dev 2.3 the gene suggestion drop down doesn't pop to front

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#593]
See screenshot

**Comment by mvelinder** [comment]
![image](https://cloud.githubusercontent.com/assets/22081541/24918280/1c815d24-1e9d-11e7-86a2-83f31cb1f553.png)

**Comment by AlistairNWard** [comment]
I don't see this behaviour. Can you give a specific example of the steps you took?

**Comment by mvelinder** [comment]
Link to data: http://nv-dev.iobio.io/gene.iobio.next/?batchSize=5&species=Human&rel0=proband&rel1=mother&rel2=father&genes=HBB,GATA1,HBA2,FANCG,BRCA2,FANCD2,FANCC,BRIP1,FANCA,RAD51C,SPTA1&gene=FANCD2&name0=&bam0=https://ugp.chpc.utah.edu/gnomex/URLLinks/f63ae770-cad9-4fe9-8f46-b2e16067c24du0691312/1521670.cram.bam&bai0=&name1=&bam1=https://ugp.chpc.utah.edu/gnomex/URLLinks/f63ae770-cad9-4fe9-8f46-b2e16067c24du0691312/1521671.cram.bam&bai1=&name2=&bam2=https://ugp.chpc.utah.edu/gnomex/URLLinks/f63ae770-cad9-4fe9-8f46-b2e16067c24du0691312/1521672.cram.bam&bai2=&affectedSibs=&unaffectedSibs=

Was able to reproduce by clicking to open the variant expanded info tooltip, then going back to the gene entry box and typing -- but it appears the expanded variant tooltip has to be locked for it to happen

**Comment by AlistairNWard** [comment]
I still can't reproduce. I did the following:

1. Clicked the link,
2. Allowed automatic variant calling (no vcf is specified in the link), 
3. Clicked on a variant to open the expanded tooltip,
4. Started typing in the gene entry box

Everything was working totally fine. Did you use different steps to above?

**Comment by mvelinder** [comment]
1. Click link
2. Load data
3. Call from alignments
4. Open filters panel
5. Click FANCD2 high impact red triangle variant and lock tooltip
6. Go to gene entry box and start typing

Does it for me

**Comment by AlistairNWard** [comment]
Ok, specifically, you need to select the variant from the "ranked variants" table and this does indeed fail. If you select the variant in the proband card, everything is fine.

**Comment by tonydisera** [comment]
I'm pretty sure this is fixed.  Can you give it a try?

**Comment by AlistairNWard** [comment]
I don't see the issue with the gene box anymore, but calling on alignments by default seems to have gone away.

1. Go to http://nv-dev-new.iobio.io/gene.iobio.next/
2. Click files, select the Platinum trio for alignments,

The coverage is loaded, but no calling happens.

**Comment by tonydisera** [comment]
Oops.  I will look into this.

**Comment by tonydisera** [comment]
I took the automatic calling on alignments out.  It was causing grief with the code.  My rational was that a user can click on 'Call variants... all genes' instead.  Does that jive with you?

**Comment by AlistairNWard** [comment]
Hmm, I think in the EIEE paper, we specifically state that calling is automatic. Also, if no calling happens, you just have a blank trio and it isn't necessarily obvious to go and click something else. If it's a real problem in the code, that's fine, but I think it's definitely preferable to automatically prompt the user. Maybe even just a prompt telling them to manually call would be better?

**Comment by tonydisera** [comment]
Good point.  Let me see how hard it would be to re-introduce now that the code has been refactored.
