### ISSUE TITLE
Able to load data and try to analyze a gene without selecting sample from VCF

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#594]
On 2.3 you're able to enter gene analysis without selecting a sample from dropdown - causing analysis to run indefinitely. Importantly, there's no error to point you towards you need to select a sample from dropdown. Maybe include a red box and require user to select a sample (similar to the requirements for selecting a genome build)? 

![image](https://cloud.githubusercontent.com/assets/22081541/24958291/0e9a4a04-1f4c-11e7-9002-ef76c8fbe24c.png)
![image](https://cloud.githubusercontent.com/assets/22081541/24958318/22571e78-1f4c-11e7-9489-db2e6d9171c6.png)

**Comment by AlistairNWard** [comment]
1. Open gene.iobio 2.3, 
2. Click Files,
3. Add  the vcf url :https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz
4. Add a gene,

You can now click load. You don't need to specify a sample, or the reference build. In this case, an error does appear, but it isn't informative.

"TypeError: Cannot read property 'toString' of null"
