### ISSUE TITLE
After calling variants from alignments, loaded variants (filter = '.') now show up as NOT PASSING FILTER CRITERIA

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#595]

**Comment by AlistairNWard** [comment]
I'm seeing this even with calling variants.

1. Open gene and load demo data
2. Before RAI1 is analyzed, click "analyze all genes"

All variants in RAI1 will be grayed out. If you don't hit analyze all, or wait till RAI1 is loaded before analyzing all, they won't be grayed out.

**Comment by tonydisera** [comment]
Good find, Al.  I can fix this bug.  

In general, the problem is that the variants with a recfilter of '.' are only marked as 'NOT PASSING FILTER CRITERIA'  if there are other 'PASS' variants for that gene.  Instead, it seems like we need to know if any recfilters have been applied across the vcf records in the vcf file.  Is there a way that the header could be interrogated?

**Comment by tonydisera** [comment]
For now, I'm going to change the code so that the recfilters are considered for variants across ALL genes that have been analyzed, so that RAI1 will show all variants with grey background in Ranked Variants table since all have a filter of '.'  (There are vcf records with PASS in the demo platinum trio exome dataset -- mostly for HOMREFs for some reason).

**Comment by tonydisera** [comment]
Fixed.  Please validate on nv-dev-new.iobio.io.  I would like to push this to production in the morning if it looks okay.

**Comment by AlistairNWard** [comment]
Yeah, I think this is ok. At some point, we might want to come back and rethink how we handle the vcf filter field.
