### ISSUE TITLE
The filter panel shows vcf rec filters to filter only for currently selected gene rather than possible filter values across all genes

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#596]
The VCF Filter values (e.g., PASS, ., etc) are populated based on the variants that have been analyzed across all loaded genes. This isn't a complete solution, because variants with '.' filters won't be considered as 'FLAGGED FOR NOT MEETING FILTER CRITERIA' until a variant with a 'PASS' filter is encountered. Take, for example the demo data. When first loaded, variants for RAI1, which all have a filter of '.', are not flagged.

<img width="1088" alt="screen shot 2017-04-27 at 9 56 02 pm" src="https://cloud.githubusercontent.com/assets/8420103/25513791/37334fba-2b95-11e7-9d31-472796baff28.png">

After gene PDGFB is selected, a variant with a 'PASS' filter is encountered.

<img width="946" alt="screen shot 2017-04-27 at 9 56 26 pm" src="https://cloud.githubusercontent.com/assets/8420103/25513798/428f3e6e-2b95-11e7-9cf9-73a9f610e8f1.png">

Select RAI1 again. Now its variants are flagged for not meeting filter criteria.

<img width="962" alt="screen shot 2017-04-27 at 9 56 37 pm" src="https://cloud.githubusercontent.com/assets/8420103/25513802/49ab22c6-2b95-11e7-99cf-e6a3825d576e.png">

I think that the solution is to have a priori knowledge of all possible filter values used in the loaded VCF.

**Comment by AlistairNWard** [comment]
Issue #653 removes the column shading and red message in the tooltip. Instead, the tooltip should just include the VCF filter value and the user can interpret.

Superseded by #653.
