### ISSUE TITLE
AF selector fails

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#6]
I changed the AF to filter on 1000G and then put in a range, but nothing happens to the displayed variants.

**Comment by tonydisera** [comment]
For some reason, I can't reproduce this bug, Al.  It is a bit odd how you have to press enter in the field in order for the filtering to be triggered.  

Perhaps we need 'go' button next to the Coverage and AF range text input fields.

**Comment by tonydisera** [comment]
Added 'go' button to right of af range input fields.  Should work now.
