### ISSUE TITLE
A gene isn't counted as having has variants called if there are no variants

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#600]
1. Open demo data,
2. Add gene NNMT,
3. Call on all genes,
4. When complete, all 6 genes show as analyzed, but only 5 have variants called. NNMT has no second checkmark either.

While waiting for step 3 to finish, the loaded variants appear, along with coverage. Then the ranked variants table appears populated, and the working glyph is no longer present in the gene badge. So it looks like everything is done. Out of the blue, a while later, the called variants pop in, but there was no indication that work was still ongoing.

I started in MYLK2, and here is the first screenshot:

<img width="821" alt="screen shot 2017-04-20 at 1 43 11 pm" src="https://cloud.githubusercontent.com/assets/523111/25244639/94102ba2-25cf-11e7-856b-d5faaea10487.png">

Looks like everything is done. 20 seconds or so later:

<img width="1123" alt="screen shot 2017-04-20 at 1 43 56 pm" src="https://cloud.githubusercontent.com/assets/523111/25244658/a16eb048-25cf-11e7-9552-b53e01b32d01.png">

Here you can see both issue #595 (the loaded variants are now grayed out), the called variants now appear, and that NNMT doesn't show up as having had variants called. I've waited a long time to see if this state changes (e.g. that called variants check mark, and the count of called genes updates), but it does not.

If you click on NNMT, you can see that no variants were called for the parents, but there is nothing about called variants for the proband, i.e. the variants loaded box shows 0 in the proband card, but the variants loaded box is missing.

<img width="908" alt="screen shot 2017-04-20 at 1 49 07 pm" src="https://cloud.githubusercontent.com/assets/523111/25244819/39526ecc-25d0-11e7-8441-006173a046cf.png">

If you have NNMT as the only gene, let it load the zero variants, then call on it, the calling never seems to complete. Maybe this explains some of the above?

**Comment by tonydisera** [comment]
I can reproduce this problem.  I will look at it first thing in the morning.
