### ISSUE TITLE
Bookmarking a variant closes the tooltip

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#602]
1. Click on a variant in the "Ranked variants" table to open the tooltip,

2. Bookmark the variant,

The tooltip closes, so I need to reselect the variant to see the details.

**Comment by tonydisera** [comment]
Hi Al.  I coded it this way on purpose.  I thought it would be a way to let the user know that the bookmark did occur and is registered in the left panel.  Should I back this out?

**Comment by AlistairNWard** [comment]
Let's get other opinions. Personally, I'd prefer it stay open. The "bookmark this variant" text changes to "bookmarked" which is enough indication for me!

**Comment by tonydisera** [comment]
Na.  Let's not vote by committee.  Let me back this puppy out.  That is what I get for taking initiative. ;-)
