### ISSUE TITLE
Cannot export starred variants

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#603]
We can only export all bookmarked variants, not starred only. Was this by design?

**Comment by tonydisera** [comment]
I was trying to simplify the interface.  The 'starred' flag is shown in the exported csv file and the INFO field in the vcf.   Thoughts?

**Comment by AlistairNWard** [comment]
Fine by me. I just hadn't noticed. I guess the only issue is that it feels kind of redundant inside of gene, but that might be ok. If I star it, there is nothing that makes it clear what the point of that was, but I don't really have a problem with that. It's more of an advanced feature.
