### ISSUE TITLE
Problems with calling variants

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#605]
1. Open gene and select the demo data
2. Analyze all
3. When everything is analyzed, call variants in the selected gene (e.g. RAI1),
4. When it has called, click on PHDA1, but before all the info is loaded, call on the selected gene

It starts to call, but then visuals are updated and calling appears to have been forgotten. Click on PDHA1 again, and then the called variants appear, so the calling happened, just the visual updates didn't happen.

5. Click on MYLK2 and then call on selected gene.

This isn't the same 100% of the time, but sometimes the called variant is in ClinVar sometimes not.

**Comment by AlistairNWard** [comment]
![screen shot 2017-04-26 at 3 54 34 pm](https://cloud.githubusercontent.com/assets/523111/25454059/32d1aea0-2a99-11e7-9cee-eca0afcf2c6b.png)

![screen shot 2017-04-26 at 3 54 27 pm](https://cloud.githubusercontent.com/assets/523111/25454063/361c7ff4-2a99-11e7-84d6-2a650dc2a85a.png)

**Comment by tonydisera** [comment]
I can reproduce this problem.  I'll look into this.

**Comment by tonydisera** [comment]
Fixed.

**Comment by AlistairNWard** [comment]
One minor thing that's still there. When I do step 4, everything is now fine, except that the working glyph is not present in the gene badge while calling is in progress.

**Comment by tonydisera** [comment]
Yes, I couldn't get that part to coordinate as expected so that the gene badge shows the 'loading gif'.  I figured since this is an edge case, the fix is probably sufficient.
