### ISSUE TITLE
Our "No" option on confirm dialogues says "No, just show the coverage"

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#613]
![image](https://cloud.githubusercontent.com/assets/22081541/25663100/00f42f30-2fd4-11e7-85c9-a00385db4e97.png)

For things unrelated to coverage, such as removing genes from the list.

**Comment by tonydisera** [comment]
Oops.  These are the buttons from another prompt.  I'll fix this today.
