### ISSUE TITLE
Use different set of glyphs to represent recessive and de novo inheritance modes

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#620]
The glyphs for recessive and de novo inheritance are faint and are too similar to provide an easy visual cue to the user.  Also, show the inheritance glyph in the gene badge when the 'harmful variant' (e.g. lightning) is detected and this variant has either a recessive or de novo inheritance mode.

**Comment by tonydisera** [comment]
<img width="99" alt="screen shot 2017-06-05 at 5 22 00 pm" src="https://cloud.githubusercontent.com/assets/8420103/26807423/955299a6-4a13-11e7-9960-7c41f3dc9194.png">
<img width="624" alt="screen shot 2017-06-05 at 5 22 06 pm" src="https://cloud.githubusercontent.com/assets/8420103/26807427/9a5616c6-4a13-11e7-99f4-427c727caf5d.png">
<img width="64" alt="screen shot 2017-06-05 at 5 22 21 pm" src="https://cloud.githubusercontent.com/assets/8420103/26807432/9c9e6d3e-4a13-11e7-9878-23f4b909a958.png">

**Comment by AlistairNWard** [comment]
I agree this is better than what we have. Would it make sense to show the two dots vertically? Would keep the gene badges smaller.

**Comment by tonydisera** [comment]
Good idea.  I will give that a try.

**Comment by tonydisera** [comment]
It turns out that the vertical space is needed for the de novo inheritance glyph, so showing the dots side-by-side works better for 14x14 - 20x20 glyph.  I did change the color to gold thinking that the pink clashed with the red thunder glyph.

**Comment by AlistairNWard** [comment]
This makes sense. I was going to suggest getting rid of the little lines on the de novo glyph, but then I figured that we would drop the lines for dominant. We could also use a pair of these to represent a compound het?
