### ISSUE TITLE
"Thumbs up" glyph for absent in unaffected not correct for recessive variant

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#622]
![image](https://user-images.githubusercontent.com/22081541/26889430-698f21d2-4b6b-11e7-9be1-cdbe8d9b763d.png)

Seen in the screenshot we have thumbs down for Absent in Unaffected sibs, despite the unaffected sib being homozygous reference. It should be thumbs up, in that it's absent (not recessive) in the unaffected sib (despite whether the unaffected sib is het or homozygous reference, just not homozygous alternate).

**Comment by tonydisera** [comment]
Good find, Matt!  Yes, there is a bug.  For recessive variants present in proband, the glyph should have been a grey thumbs up, indicating that that the recessive variant (either a het or a homref) is not present in the unaffected sibs.  Also, the other variant that showed "gt_unknown" was addressed in the bug fix, treating this as 'variant not present' and thus homref for the unaffected sib, showing an thumbs up glyph.
