### ISSUE TITLE
Top panel disappears on tooltip

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#625]
1. Open demo data.

2. Hover over a variant in the ranked variants table and the tooltip pops up and sits over the blue panel at the top of the screen.

3. Open the filter side panel and repeat. The blue panel now disappears when the tooltip opens.

**Comment by tonydisera** [comment]
Hi Al.  I can't replicate this problem on Chrome, Firefox, or Safari.   Was this problem happening on a specific variant?  Does it only happen on hover over (not click)?

**Comment by AlistairNWard** [comment]
It was on hover over, but try it when you're not hooked up to a monitor.

**Comment by tonydisera** [comment]
I still can't reproduce this on my Macbook Pro screen.  What resolution are you running?

**Comment by AlistairNWard** [comment]
Actually works on the monitor too. You just need to scroll first. I'll attach a video on Slack.
