### ISSUE TITLE
Not all Clinvar variants in vcf show Clinvar designation in gene.iobio

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#627]
Pull up ClinVar vcf in VCF for a gene (e.g. BRCA2, MTHFR).  Notice how some of the Ranked Variant columns do not have a ClinVar designation.  
<img width="901" alt="screen shot 2017-06-12 at 8 08 44 pm" src="https://user-images.githubusercontent.com/8420103/27062843-3aacbe9e-4fab-11e7-84cc-f2115144cc52.png">

**Comment by tonydisera** [comment]
Could it be that eutils returns a different list than the downloaded clinvar vcf or is the Alt->Ref designation different?

**Comment by AlistairNWard** [comment]
It could be. The downloaded VCF (which is probably not current anymore), contains many lines of variants at the same coordinate. eutils may just return one record which is possibly not the one that contains this variant. Can you use eutils and see what is returned at that coordinate?

**Comment by tonydisera** [comment]
See RAI1 in demo dataset.  (Called variant)
<img width="174" alt="screen shot 2017-07-26 at 1 56 16 pm" src="https://user-images.githubusercontent.com/8420103/28641342-1a23394a-720c-11e7-8ba8-a3b97ac59208.png">
