### ISSUE TITLE
Hover over on 'harmful variants' and 'exon coverage' glyphs displays information for why these glyphs are being displayed

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#628]
![image](https://user-images.githubusercontent.com/22081541/27181371-99dc5074-5194-11e7-8ca8-dfd77e812c7f.png)

In demo data:
Example: hover over on RAI1 harmful variants glyph would display "Contains ClinVar pathogenic variant"
Example: hover over on GRIP1 exon coverage glyph would display "Exon 10 has insufficient coverage in proband, mother and father"

**Comment by tonydisera** [comment]
This is a great suggestion, Matt.  I'll look into doing this today.
