### ISSUE TITLE
Suggested variants UI

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#629]
Here is a quick screenshot of my mockup.

**Comment by AlistairNWard** [comment]
![suggested_variants](https://user-images.githubusercontent.com/523111/27486751-922a21c8-57ff-11e7-8e79-e9bcdeeb741d.png)

**Comment by AlistairNWard** [comment]
Tony has already implemented a bunch of stuff here, but I would suggest having the coordinates for the gene underneath instead of above the scale.

**Comment by tonydisera** [comment]
Here are a few tasks for showing suggested variants:

ClinVar variants histogram
 - gene tnt freezes
 - tooltip hover
 - on hover, show clinvar variants and phenotype?

ClinVar
 - build 37 vs 38
 - use weekly vcf or eutils?

Cache server side for promiseGetKnownVariants
