### ISSUE TITLE
Median threshold text

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#634]
In the new production version, the text showing the median value covers the coverage. I wonder if there is a better of way of implementing this?

**Comment by AlistairNWard** [comment]
<img width="438" alt="screen shot 2017-07-10 at 9 10 05 am" src="https://user-images.githubusercontent.com/523111/28020809-9b33bd90-6553-11e7-9378-ba7c9553b0ce.png">

**Comment by tonydisera** [comment]
We moved the label over to the right and used a dashed line instead.
