### ISSUE TITLE
The coverage isn't spanning full region for gene TPR

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#64]
<img width="1321" alt="screen shot 2015-07-06 at 7 26 09 pm" src="https://cloud.githubusercontent.com/assets/8420103/8536924/fc285908-2414-11e5-81c5-dd75d2577837.png">

**Comment by AlistairNWard** [comment]
I'm also seeing this for multiple genes (AIRE and MYLK2, for example).

**Comment by tonydisera** [comment]
It turns out that the coverage service needed to zero fill positions to account for regions with no coverage.  Revamped coverage service to zero fill and also fixed critical bugs that were not handling iterations through lists properly.  Also, reworked reducePoints to spread remaining elements over entire array of reduced points.
