### ISSUE TITLE
Remove shaded rows for variants not passing filtering criteria

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#653]
This is a complex concept that really can't be adequately dealt with. Remove the shading, and in the tooltip add text to the effect that the VCF filter is not PASS. Or just include the VCF filter value in the tooltip.

**Comment by tonydisera** [comment]
The VCF rec filters only populate when user clicks on gene.  They should populate during 'Analyze all'.  Also, the filter is getting clear each time a gene is selected.
