### ISSUE TITLE
In Data dialog, vcf url or file specified, then gene name entered, load button enabled even though genome build is not specified

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#664]

**Comment by AlistairNWard** [comment]
I was able to recreate this (with 2.5). Open gene, open the Files dialog and select the Platinum vcf, then enter a gene, and I was able to click load without selecting the genome build resulting in the error "TypeError: Cannot read property 'toString' of null".

**Comment by tonydisera** [comment]
Sorry.   I can't reproduce this bug.   Would you mind giving it another try?
