### ISSUE TITLE
Not all of the allele frequencies for 1000 G are being found in the af server

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#67]
I loaded the 1000G phase 3 vcf as the proband and discovered that 2 of the variants aren't getting an allele frequency from the af server.

**Comment by tonydisera** [comment]
<img width="491" alt="screen shot 2015-07-10 at 2 04 08 pm" src="https://cloud.githubusercontent.com/assets/8420103/8628047/b1304f78-270c-11e5-8b16-575c2870ad1f.png">

**Comment by AlistairNWard** [comment]
Is this still an issue? Do we have a test case?
