### ISSUE TITLE
Known variants - switching quickly between counts and variants shows both charts

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#671]

**Comment by AlistairNWard** [comment]
I was able to recreate this bug this morning using BRCA1 on the demo data.

**Comment by tonydisera** [comment]
I can't seem to reproduce this problem.

**Comment by AlistairNWard** [comment]
I just added a video on Slack. Sometimes I can get this to work immediately, but in the video, it takes a couple of attempts.

**Comment by AlistairNWard** [comment]
Tried really hard to break it. I failed! This passes!
