### ISSUE TITLE
Call progress bar not cleared out when data sources (Files dialog) changes

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#680]
Load demo data and select MYLK2.  After variants loaded, click 'Call Variants... selected gene'.  After the variants are called, the progress bars show 1 gene loaded, 1 gene called.  Now click on 'Files' to change one of the data sources.  Press 'Load' button.  Only the progress bar for 'Loaded' genes clears.

**Comment by AlistairNWard** [comment]
Not sure if this hasn't been pushed, but I just tried this, and the called progress bar still showed 1 called gene.
