### ISSUE TITLE
Tooltip on standard filter counts

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#689]
After applying standard filters, we get numbers showing how many genes pass the filters. We should add a tooltip if you hover over these numbers. We could state, e.g. 3 genes contain a variant that pass this filter. Maybe also state the number of genes that have or have not been analyzed. Maybe a list of the genes?

**Comment by tonydisera** [comment]
I also changed the 'unanalyzed warning' to a ! rather than a glyph, one next to the loaded variant count and one next to the called variant count.

Also, now the 'Insufficient coverage' filter only shows the loaded gene count.

**Comment by AlistairNWard** [comment]
Sorry to be a pedant (but obviously not sorry at all), but if there is 1 gene, the text is "1 gene contain loaded variants that pass filters" - should be contains.
