### ISSUE TITLE
Change reorder arrows in ranked variants table to || drag and drop function

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#700]
![image](https://user-images.githubusercontent.com/22081541/30405454-3e03b448-98a9-11e7-8898-11a4befe1c86.png)

Change the arrows to || or horizontal lines to be able to grab one term and slide it up and down instead of clicking one terms up arrow a bunch of times.

**Comment by AlistairNWard** [comment]
See #654.
