### ISSUE TITLE
Make it clear tooltip is scrollable

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#734]
I clicked on a variant and thought data was missing, but the tooltip can be scrolled. It was unclear that there was additional information available.

**Comment by AlistairNWard** [comment]
<img width="683" alt="screen shot 2017-10-16 at 9 45 21 am" src="https://user-images.githubusercontent.com/523111/31615284-1577af62-b257-11e7-8270-b2a9f4d126ef.png">

**Comment by tonydisera** [comment]
fixed with #730
