### ISSUE TITLE
'Enter URL for VCF' non functional

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#74]
According to the tour, clicking the 'Enter URL for VCF' will auto-populate with the Platinum trio data. No data is entered, however.

**Comment by tonydisera** [comment]
Thanks for testing!  I will be working on the app tour today.  It is still in a rough state.

**Comment by tonydisera** [comment]
Fixed to match new dropdown menu items.  This step now includes more text on how to specify a vcf data source.
