### ISSUE TITLE
Tour text needs revision

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#75]
Suggestions.

1. Type in the gene name BRCA2 and select from the drop down list.
2. This shows the gene model for the canonical transcript.
3. Select 'Single' to view variants for a single sample. Select 'Trio' to analyze an affected child with an unaffected mother and father.
4. This is where the 'Proband' variant file is selected. Select 'Enter URL for VCF' and the URL for the variant file for NA12878 (from the Illumina Platinum data set) will be selected.
5. This is where the 'Proband' alignment file is optionally selected. Select 'Enter URL for BAM' and the alignment file for NA12878 will be selected.

Maybe we need to add a new point of two here.

5a. Click 'Load' to load all of the selected data into the app.
5b. Click the minimize button to hide the data selection card and increase the space available for analysis.

6. Other transcript for this gene can be selected from this dropdown.
7. Drag and drop to select a region to zoom into. To zoom back out, click anywhere on the gene model.
8. Adjust this value to display modify the size of displayed DNA upstream and downstream of the gene.

**Comment by AlistairNWard** [comment]
Only just noticed that additional points are added once the data is loaded. I would suggest that the numbering scheme continues as a follow on to the steps in the data loading part of the tour.

**Comment by AlistairNWard** [comment]
Steps after data loading:

3. significance is misspelled.
4. When an alignment file is specified, the base coverage chart is displayed, allowing the user to identify regions of abnormal or unexpected sequence coverage.
5. Push the Find Missing Variants button to call variants using Freebayes. Variants not present in the VCF file will be displayed above the loaded variants. (Are we going to stick with 'Find missing variants' or should we rename this?).
6. multiple is misspelled
7. The variants are ranked according to different criteria. These criteria can be reordered by clicking on their respective arrows. Click on a column to see the variant in the variant chart below.

**Comment by tonydisera** [comment]
Wow!  Thanks for all of your suggestions.  Rewording the guide based on this issue right now.
