### ISSUE TITLE
Approx coverage is unclear

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#80]
If I hover over a variant and this is not present in one of the other samples, the coverage is listed as 'approx 40x', for example. I'm assuming that this is because gene is calculating the coverage at variant positions and approximating everywhere else. A general user would not understand the underlying logic and may be confused why this is approx for one sample and not another (with the variant). I don't necessarily have a suggestion! This is the eternal battle of not misrepresenting data, but striving to remain clear...!

**Comment by tonydisera** [comment]
Best post I've seen in a bug report in my career!  Go Al!

Yep.  This was my attempt to workaround the issue that we don't have a variant at this position to grab the exact coverage.  But now that I think about it, there is no reason why the app couldn't send in the union of positions from the trio to the coverage service.  The only drawback would be timing - the coverage service could only be accessed after all variant for the trio have been returned.  For now, should I get rid of 'approx'?

**Comment by AlistairNWard** [comment]
I think we should get the groups opinion, but I would probably just remove 'approx' as you suggested. With 'approx' there, there needs to be an explanation and I see no good way of providing the explanation.

**Comment by tonydisera** [comment]
I removed 'approx' from the label and created an issue for getting exact coverage for non-variant positions in trio data.
