### ISSUE TITLE
Circled coverage under 'no variant' position on trio sets only shows approximated coverage based on averaged coverage.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#81]
App should send in the union of positions from the trio to the coverage service.  Need to wait until all trio variants are returned to send in positions.

**Comment by AlistairNWard** [comment]
Is this still an issue?

**Comment by AlistairNWard** [comment]
Can this be wrapped in #274, or is this a distinct, unrelated issue?

**Comment by tonydisera** [comment]
Yes, let's combine these.

**Comment by tonydisera** [comment]
Actually, this has been fixed.  We now gather the coverage by position.
