### ISSUE TITLE
Hide mouse over

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#88]
Click on a variant and the mouseover text remains fixed. Now zoom in on the transcript and the mouseover remains. If there are no variants, there isn't an obvious way to get the mouseover to go away. A very minor issue, and may well be ignorable. Maybe when the screen is modified, e.g. by a zoom, selections on the variants cards are cleared. Even if you zoom in on a region containing the selected variant, the text position may not be in a sensible position relative to the variant and it can't necessarily be clicked to remove the selection. You actually need to select and then deselect another variant to get the mouseover to work again.

**Comment by tonydisera** [comment]
I'm glad you entered this issue.  I've been fretting a bit over this one.  It definitely needs to be reworked before release.  I agree that the click to 'unlock' the variant and tooltip isn't intuitive.  I'll think about this today and perhaps we can bat around some ideas tomorrow when you are back in the office.
